#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# AUREA · установка приёмника заявок с квиз-лендинга.
#
# Запуск под root:   bash install.sh
# Повторный запуск безопасен.
#
# Что делает:
#   1. осматривает сервер и печатает, что на нём стоит;
#   2. проверяет, не займёт ли он чужое (порт, имя юнита, конфиг nginx, домен);
#   3. ставит службу в СВОЙ каталог, под СВОИМ пользователем, СВОЕЙ службой,
#      СО СВОИМ отдельным файлом конфигурации nginx.
#
# Чего НЕ делает:
#   * не трогает существующие сайты, конфиги nginx, юниты systemd и их данные;
#   * не переписывает уже существующий файл настроек — только дописывает
#     недостающие строки;
#   * не ставит пакеты и не меняет политику SELinux без явного разрешения;
#   * не печатает токен ни в лог, ни на экран.
#
# Настройки через переменные окружения (все необязательны):
#   AUREA_KVIZ_DOMAIN     домен приёма заявок  (по умолчанию kviz.aureadesign.ru)
#   AUREA_KVIZ_ORIGINS    разрешённые Origin через запятую
#   AUREA_KVIZ_PORT       локальный порт       (по умолчанию 8787)
#   AUREA_KVIZ_EMAIL      почта для Let's Encrypt
#   AUREA_KVIZ_SKIP_TLS=1 не выпускать сертификат
#   AUREA_KVIZ_ALLOW_APT=1 разрешить установку certbot через пакетный менеджер
#   AUREA_KVIZ_ALLOW_SELINUX=1 разрешить setsebool httpd_can_network_connect
# ---------------------------------------------------------------------------
set -euo pipefail

SVC=aurea-kviz
SVC_USER=aureakviz
APP_DIR=/opt/$SVC
CFG_DIR=/etc/$SVC
DATA_DIR=/var/lib/$SVC
ACME_DIR=/var/www/$SVC-acme
UNIT=/etc/systemd/system/$SVC.service
ENV_FILE=$CFG_DIR/kviz.env
MARKER="# managed-by: aurea-kviz installer"

DOMAIN="${AUREA_KVIZ_DOMAIN:-kviz.aureadesign.ru}"
ORIGINS="${AUREA_KVIZ_ORIGINS:-https://kirill-design367.github.io}"
LE_EMAIL="${AUREA_KVIZ_EMAIL:-}"
SKIP_TLS="${AUREA_KVIZ_SKIP_TLS:-0}"
ALLOW_APT="${AUREA_KVIZ_ALLOW_APT:-0}"
ALLOW_SELINUX="${AUREA_KVIZ_ALLOW_SELINUX:-0}"

RED=$'\033[31m'; GRN=$'\033[32m'; YEL=$'\033[33m'; BLD=$'\033[1m'; RST=$'\033[0m'
step() { printf '\n%s── %s ──────────────────────────%s\n' "$BLD" "$1" "$RST"; }
ok()   { printf '  %s✓%s %s\n' "$GRN" "$RST" "$1"; }
warn() { printf '  %s!%s %s\n' "$YEL" "$RST" "$1"; }
die()  { printf '\n%sОстановлено:%s %s\n' "$RED" "$RST" "$1" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

[ "$(id -u)" = "0" ] || die "нужен root. Запустите: sudo bash $0"
have systemctl || die "нет systemd — этот установщик рассчитан на systemd"

# Порт: сначала то, что уже записано в настройках, потом переменная, потом
# значение по умолчанию. Иначе автоподбор при каждом запуске давал бы новый
# порт, и nginx проксировал бы в пустоту.
PORT_FROM_ENV=""
[ -f "$ENV_FILE" ] && PORT_FROM_ENV=$(sed -n 's/^AUREA_KVIZ_PORT=\([0-9]\+\).*/\1/p' "$ENV_FILE" | head -1)
PORT="${PORT_FROM_ENV:-${AUREA_KVIZ_PORT:-8787}}"

# ===========================================================================
step "1. Что стоит на сервере"
# ===========================================================================
[ -r /etc/os-release ] && . /etc/os-release || true
echo "  ОС:            ${PRETTY_NAME:-неизвестно}"
echo "  Ядро:          $(uname -r)"
echo "  Python:        $(python3 -V 2>&1 || echo 'НЕТ')"
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 7) else 1)' 2>/dev/null \
  || die "нужен Python 3.7 или новее"

echo "  Веб-серверы:"
FOUND_WEB=0
for s in nginx apache2 httpd caddy angie; do
  if have "$s"; then echo "                 $s  ($("$s" -v 2>&1 | head -1))"; FOUND_WEB=1; fi
done
[ "$FOUND_WEB" = "1" ] || echo "                 не найдены"

echo "  Панели управления хостингом:"
PANEL=""
for p in /usr/local/mgr5:ISPmanager /usr/local/fastpanel2:FASTPANEL \
         /opt/psa:Plesk /usr/local/hestia:HestiaCP /usr/local/cpanel:cPanel \
         /usr/local/vesta:VestaCP /opt/cloudpanel:CloudPanel; do
  if [ -d "${p%%:*}" ]; then PANEL="${p##*:}"; echo "                 НАЙДЕНА: $PANEL"; fi
done
[ -n "$PANEL" ] || echo "                 не найдены"

echo "  Работающие службы (без системных):"
systemctl list-units --type=service --state=running --no-legend --no-pager 2>/dev/null \
  | awk '{print $1}' \
  | grep -Ev '^(systemd-|dbus|cron|rsyslog|ssh|polkit|getty|user@|networkd|resolved|udev|logind|timesyncd|accounts-daemon|unattended|snapd)' \
  | sed 's/^/                 /' || true

if have nginx; then
  echo "  Сайты в nginx (server_name):"
  nginx -T 2>/dev/null | grep -E '^[[:space:]]*server_name' | tr -s ' ' | sed 's/^ *//; s/;$//' \
    | sort -u | sed 's/^/                 /' || true
  echo "  Файлы конфигурации nginx:"
  nginx -T 2>/dev/null | grep -E '^# configuration file' | sed 's/^# configuration file //; s/:$//' \
    | sed 's/^/                 /' || true
fi

echo "  Занятые порты:"
have ss && ss -tlnpH 2>/dev/null | awk '{print $4"  "$6}' | sed 's/^/                 /' | head -30

echo "  Адреса:"
ip -4 addr show scope global 2>/dev/null | awk '/inet /{print "                 IPv4 "$2}'
ip -6 addr show scope global 2>/dev/null | awk '/inet6 /{print "                 IPv6 "$2}'
V6ROUTE=$(ip -6 route show default 2>/dev/null | head -1)
echo "                 маршрут IPv6 по умолчанию: ${V6ROUTE:-НЕТ}"
V6DISABLED=$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null || echo '?')
echo "                 net.ipv6.conf.all.disable_ipv6 = $V6DISABLED"

echo "  Доступность api.telegram.org (полный HTTPS-запрос, не только TCP):"
TG_V4=нет; TG_V6=нет
if have curl; then
  c4=$(curl -4 -s -o /dev/null -w '%{http_code}' --max-time 8 https://api.telegram.org/ 2>/dev/null || true)
  c6=$(curl -6 -s -o /dev/null -w '%{http_code}' --max-time 8 https://api.telegram.org/ 2>/dev/null || true)
  [ -n "${c4:-}" ] && [ "$c4" != "000" ] && TG_V4="да (HTTP $c4)"
  [ -n "${c6:-}" ] && [ "$c6" != "000" ] && TG_V6="да (HTTP $c6)"
fi
echo "                 по IPv4: $TG_V4"
echo "                 по IPv6: $TG_V6"
if [ "$TG_V4" = "нет" ] && [ "$TG_V6" = "нет" ]; then
  warn "Ни один путь до Telegram сейчас не отвечает. Служба всё равно поставится:"
  warn "заявки будут сохраняться на диск и уйдут, как только связь появится."
fi

have getenforce && echo "  SELinux:       $(getenforce 2>/dev/null)"

# ===========================================================================
step "2. Проверка, что ничего чужого не будет затронуто"
# ===========================================================================
if [ -f "$UNIT" ] && ! grep -q "SyslogIdentifier=$SVC" "$UNIT"; then
  die "файл $UNIT существует и создан не нами. Разбирайтесь вручную."
fi

# Владелец порта определяется по cgroup процесса, а не по имени: чужой
# telegram-бот почти наверняка тоже на python3, и совпадение по имени
# означало бы попытку встать поверх него.
port_owner_is_ours() {
  local pid
  pid=$(ss -tlnpH 2>/dev/null | awk -v p=":$PORT\$" '$4 ~ p {print $0}' \
        | grep -o 'pid=[0-9]*' | head -1 | cut -d= -f2)
  [ -n "$pid" ] || return 1
  grep -qs "$SVC" "/proc/$pid/cgroup"
}

if have ss && ss -tlnH 2>/dev/null | awk -v p=":$PORT\$" '$4 ~ p' | grep -q .; then
  if port_owner_is_ours; then
    ok "порт $PORT занят нашей же службой — это перезапуск"
  elif [ -n "$PORT_FROM_ENV" ]; then
    die "порт $PORT записан в $ENV_FILE, но занят чужим процессом. Освободите его или укажите другой в файле настроек."
  else
    warn "порт $PORT занят кем-то другим:"
    ss -tlnpH 2>/dev/null | awk -v p=":$PORT\$" '$4 ~ p' | sed 's/^/      /'
    for try in $(seq $((PORT + 1)) $((PORT + 20))); do
      if ! ss -tlnH 2>/dev/null | awk -v p=":$try\$" '$4 ~ p' | grep -q .; then PORT=$try; break; fi
    done
    ok "выбран свободный порт $PORT"
  fi
else
  ok "порт $PORT свободен"
fi

for p in "$APP_DIR" "$DATA_DIR"; do
  if [ -e "$p" ] && [ ! -e "$p/.aurea-kviz" ] && [ -n "$(ls -A "$p" 2>/dev/null)" ]; then
    die "каталог $p существует, не пуст и не наш. Остановился."
  fi
done
ok "чужих файлов на пути установки нет"

if [ -n "$PANEL" ]; then
  warn "На сервере стоит $PANEL. Панели перегенерируют конфиги nginx из шаблонов"
  warn "и могут снести добавленный вручную файл. Если после действий в панели"
  warn "форма перестанет отправляться — заведите поддомен $DOMAIN средствами"
  warn "панели и пропишите проксирование на http://127.0.0.1:$PORT"
fi

# ===========================================================================
step "3. Пользователь и каталоги"
# ===========================================================================
if id "$SVC_USER" >/dev/null 2>&1; then
  ok "пользователь $SVC_USER уже есть"
else
  useradd --system --no-create-home --shell /usr/sbin/nologin --home-dir "$APP_DIR" "$SVC_USER" 2>/dev/null \
    || useradd --system --no-create-home --shell /sbin/nologin --home-dir "$APP_DIR" "$SVC_USER"
  ok "создан системный пользователь $SVC_USER"
fi

install -d -m 0755 -o root -g root "$APP_DIR"
install -d -m 0750 -o root -g "$SVC_USER" "$CFG_DIR"
install -d -m 0750 -o "$SVC_USER" -g "$SVC_USER" "$DATA_DIR"
install -d -m 0750 -o "$SVC_USER" -g "$SVC_USER" "$DATA_DIR/outbox"
install -d -m 0750 -o "$SVC_USER" -g "$SVC_USER" "$DATA_DIR/sent"
install -d -m 0755 -o root -g root "$ACME_DIR"
: > "$APP_DIR/.aurea-kviz"
: > "$DATA_DIR/.aurea-kviz"
chown "$SVC_USER:$SVC_USER" "$DATA_DIR/.aurea-kviz"
ok "каталоги на месте: $APP_DIR, $CFG_DIR, $DATA_DIR"

# ===========================================================================
step "4. Код службы"
# ===========================================================================
CHANGED=0
TMP_APP=$(mktemp)
base64 -d > "$TMP_APP" <<'AUREA_KVIZ_APP_B64'
IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwojIC0qLSBjb2Rpbmc6IHV0Zi04IC0qLQoiIiIKQVVSRUEg
wrcg0L/RgNC40ZHQvNC90LjQuiDQt9Cw0Y/QstC+0Log0YEg0LrQstC40Lct0LvQtdC90LTQuNC9
0LPQsC4KCtCi0L7Qu9GM0LrQviDRgdGC0LDQvdC00LDRgNGC0L3QsNGPINCx0LjQsdC70LjQvtGC
0LXQutCwIFB5dGhvbiAzIOKAlCDQvdCwINGB0LXRgNCy0LXRgNC1INC90LjRh9C10LPQviDQvdC1
INGB0YLQsNCy0LjRgtGB0Y8g0YfQtdGA0LXQtyBwaXAuCtCh0LvRg9GI0LDQtdGCIDEyNy4wLjAu
MSwg0L3QsNGA0YPQttGDINCy0YvRgdGC0LDQstC70Y/QtdGC0YHRjyDRh9C10YDQtdC3INC+0YLQ
tNC10LvRjNC90YvQuSDQutC+0L3RhNC40LMgbmdpbnguCgrQk9C70LDQstC90YvQtSDRgdCy0L7Q
udGB0YLQstCwOgogICog0LfQsNGP0LLQutCwINC/0LjRiNC10YLRgdGPINC90LAg0LTQuNGB0Log
0YEgZnN5bmMg0JTQniDQvtGC0LLQtdGC0LAg0LHRgNCw0YPQt9C10YDRgyDigJQg0L7QvdCwINC9
0LUg0YLQtdGA0Y/QtdGC0YHRjywKICAgINC00LDQttC1INC10YHQu9C4IFRlbGVncmFtINC90LXQ
tNC+0YHRgtGD0L/QtdC9OwogICogYXBpLnRlbGVncmFtLm9yZyDQsiDQoNC+0YHRgdC40Lgg0L3Q
tSDQvtGC0LLQtdGH0LDQtdGCINC/0L4gSVB2NCwg0L3QviDQvtGC0LLQtdGH0LDQtdGCINC/0L4g
SVB2NiDigJQKICAgINGB0LXRgNCy0LjRgSDQv9GA0L7QsdGD0LXRgiDQvtCx0LAg0L/Rg9GC0Lgs
INC30LDQv9C+0LzQuNC90LDQtdGCINGA0LDQsdC+0YfQuNC5INC4INC/0LXRgNC40L7QtNC40YfQ
tdGB0LrQuCDQv9C10YDQtdC/0YDQvtCy0LXRgNGP0LXRgjsKICAqINC90LUg0YPRiNC10LTRiNC4
0LUg0YHQvtC+0LHRidC10L3QuNGPINGB0LrQu9Cw0LTRi9Cy0LDRjtGC0YHRjyDQsiBvdXRib3gg
0Lgg0L/QtdGA0LXQvtGC0L/RgNCw0LLQu9GP0Y7RgtGB0Y8g0YEg0L/QsNGD0LfQsNC80LguCgrQ
n9C10YDQtdC80LXQvdC90YvQtSDQvtC60YDRg9C20LXQvdC40Y8gKNGE0LDQudC7IC9ldGMvYXVy
ZWEta3Zpei9rdml6LmVudiwg0L/RgNCw0LLQsCA2MDAsINGH0LjRgtCw0LXRgiBzeXN0ZW1kKToK
ICBBVVJFQV9LVklaX0JPVF9UT0tFTiAgICAgICAg0YLQvtC60LXQvSDQsdC+0YLQsCAgICAgICAg
ICAgICAgICjQvtCx0Y/Qt9Cw0YLQtdC70YzQvdC+KQogIEFVUkVBX0tWSVpfQ0hBVF9JRCAgICAg
ICAgICBpZCDQv9C+0LvRg9GH0LDRgtC10LvRjyAgICAgICAgICAgICjQvtCx0Y/Qt9Cw0YLQtdC7
0YzQvdC+KQogIEFVUkVBX0tWSVpfQklORCAgICAgICAgICAgICDQsNC00YDQtdGBLCDQv9C+INGD
0LzQvtC70YfQsNC90LjRjiAxMjcuMC4wLjEKICBBVVJFQV9LVklaX1BPUlQgICAgICAgICAgICAg
0L/QvtGA0YIsINC/0L4g0YPQvNC+0LvRh9Cw0L3QuNGOIDg3ODcKICBBVVJFQV9LVklaX0RBVEFf
RElSICAgICAgICAg0LrQsNGC0LDQu9C+0LMg0LTQsNC90L3Ri9GFLCDQv9C+INGD0LzQvtC70YfQ
sNC90LjRjiAvdmFyL2xpYi9hdXJlYS1rdml6CiAgQVVSRUFfS1ZJWl9BTExPV0VEX09SSUdJTlMg
INGB0L/QuNGB0L7QuiBPcmlnaW4g0YfQtdGA0LXQtyDQt9Cw0L/Rj9GC0YPRjiwg0L/QviDRg9C8
0L7Qu9GH0LDQvdC40Y4gKgogIEFVUkVBX0tWSVpfSVBfRkFNSUxZICAgICAgICBhdXRvIHwgaXB2
NiB8IGlwdjQsINC/0L4g0YPQvNC+0LvRh9Cw0L3QuNGOIGF1dG8KICBBVVJFQV9LVklaX1JBVEVf
UEVSX0hPVVIgICAg0LfQsNGP0LLQvtC6INGBINC+0LTQvdC+0LPQviDQsNC00YDQtdGB0LAg0LIg
0YfQsNGBLCDQv9C+INGD0LzQvtC70YfQsNC90LjRjiA4CiIiIgoKaW1wb3J0IGh0dHAuY2xpZW50
CmltcG9ydCBodHRwLnNlcnZlcgppbXBvcnQganNvbgppbXBvcnQgbG9nZ2luZwppbXBvcnQgb3MK
aW1wb3J0IHJlCmltcG9ydCBzb2NrZXQKaW1wb3J0IHNvY2tldHNlcnZlcgppbXBvcnQgc3NsCmlt
cG9ydCBzeXMKaW1wb3J0IHRocmVhZGluZwppbXBvcnQgdGltZQppbXBvcnQgdXVpZApmcm9tIGRh
dGV0aW1lIGltcG9ydCBkYXRldGltZSwgdGltZWRlbHRhLCB0aW1lem9uZQoKIyAtLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0gIwojINCa0L7QvdGE0LjQs9GD0YDQsNGG0LjRjwojIC0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LSAjCgpBUFBfTkFNRSA9ICJhdXJlYS1rdml6IgpWRVJTSU9OID0gIjEuMC4wIgoKQk9UX1RPS0VO
ID0gb3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfQk9UX1RPS0VOIiwgIiIpLnN0cmlwKCkKQ0hB
VF9JRCA9IG9zLmVudmlyb24uZ2V0KCJBVVJFQV9LVklaX0NIQVRfSUQiLCAiIikuc3RyaXAoKQpC
SU5EID0gb3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfQklORCIsICIxMjcuMC4wLjEiKS5zdHJp
cCgpClBPUlQgPSBpbnQob3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfUE9SVCIsICI4Nzg3Iikp
CkRBVEFfRElSID0gb3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfREFUQV9ESVIiLCAiL3Zhci9s
aWIvYXVyZWEta3ZpeiIpCkFMTE9XRURfT1JJR0lOUyA9IFsKICAgIG8uc3RyaXAoKS5yc3RyaXAo
Ii8iKQogICAgZm9yIG8gaW4gb3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfQUxMT1dFRF9PUklH
SU5TIiwgIioiKS5zcGxpdCgiLCIpCiAgICBpZiBvLnN0cmlwKCkKXQpJUF9GQU1JTFlfUFJFRiA9
IG9zLmVudmlyb24uZ2V0KCJBVVJFQV9LVklaX0lQX0ZBTUlMWSIsICJhdXRvIikuc3RyaXAoKS5s
b3dlcigpClJBVEVfUEVSX0hPVVIgPSBpbnQob3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfUkFU
RV9QRVJfSE9VUiIsICI4IikpCgpURUxFR1JBTV9IT1NUID0gImFwaS50ZWxlZ3JhbS5vcmciCkxF
QURTX0xPRyA9IG9zLnBhdGguam9pbihEQVRBX0RJUiwgImxlYWRzLmpzb25sIikKT1VUQk9YX0RJ
UiA9IG9zLnBhdGguam9pbihEQVRBX0RJUiwgIm91dGJveCIpClNFTlRfRElSID0gb3MucGF0aC5q
b2luKERBVEFfRElSLCAic2VudCIpCk1BWF9CT0RZID0gMTYgKiAxMDI0Ck1TSyA9IHRpbWV6b25l
KHRpbWVkZWx0YShob3Vycz0zKSkKIyDQkNC00YDQtdGB0LAsINC+0YIg0LrQvtGC0L7RgNGL0YUg
0L/RgNC40L3QuNC80LDRjtGC0YHRjyDQt9Cw0LPQvtC70L7QstC60LggWC1SZWFsLUlQINC4IFgt
Rm9yd2FyZGVkLUZvci4KIyDQn9C+INGD0LzQvtC70YfQsNC90LjRjiDRgtC+0LvRjNC60L4g0LvQ
vtC60LDQu9GM0L3QsNGPINC/0LXRgtC70Y86INGB0LXRgNCy0LjRgSDRgdC70YPRiNCw0LXRgiAx
MjcuMC4wLjEg0Lgg0YHRgtC+0LjRgiDQt9CwIG5naW54LgpUUlVTVEVEX1BST1hJRVMgPSB7CiAg
ICBhLnN0cmlwKCkKICAgIGZvciBhIGluIG9zLmVudmlyb24uZ2V0KCJBVVJFQV9LVklaX1RSVVNU
RURfUFJPWElFUyIsICIxMjcuMC4wLjEsOjoxIikuc3BsaXQoIiwiKQogICAgaWYgYS5zdHJpcCgp
Cn0KCmxvZ2dpbmcuYmFzaWNDb25maWcoCiAgICBsZXZlbD1sb2dnaW5nLklORk8sCiAgICBmb3Jt
YXQ9IiUoYXNjdGltZSlzICUobGV2ZWxuYW1lKXMgJShtZXNzYWdlKXMiLAogICAgc3RyZWFtPXN5
cy5zdGRvdXQsCikKbG9nID0gbG9nZ2luZy5nZXRMb2dnZXIoQVBQX05BTUUpCgoKIyAtLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0gIwojINCi0YDQsNC90YHQv9C+0YDRgiDQtNC+IFRlbGVncmFtOiDQv9GA0LjQ
vdGD0LTQuNGC0LXQu9GM0L3Ri9C5INCy0YvQsdC+0YAgSVB2NiAvIElQdjQKIyAtLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0gIwoKY2xhc3MgRmFtaWx5SFRUUFNDb25uZWN0aW9uKGh0dHAuY2xpZW50LkhUVFBT
Q29ubmVjdGlvbik6CiAgICAiIiJIVFRQUy3RgdC+0LXQtNC40L3QtdC90LjQtSwg0LrQvtGC0L7R
gNC+0LUg0YXQvtC00LjRgiDRgdGC0YDQvtCz0L4g0L/QviDRg9C60LDQt9Cw0L3QvdC+0LzRgyDR
gdC10LzQtdC50YHRgtCy0YMg0LDQtNGA0LXRgdC+0LIuCgogICAg0JIg0YjRgtCw0YLQvdC+0Lkg
0LHQuNCx0LvQuNC+0YLQtdC60LUg0L3QtdGCINGB0L/QvtGB0L7QsdCwINGB0LrQsNC30LDRgtGM
IMKr0YLQvtC70YzQutC+IElQdjbCuzogc29ja2V0LmNyZWF0ZV9jb25uZWN0aW9uCiAgICDQv9C1
0YDQtdCx0LjRgNCw0LXRgiDQsNC00YDQtdGB0LAg0LIg0L/QvtGA0Y/QtNC60LUgZ2V0YWRkcmlu
Zm8g0Lgg0L3QsCDRgdC10YDQstC10YDQsNGFINCyINCg0KQg0L/QtdGA0LLRi9C8INC+0LHRi9GH
0L3QviDQuNC00ZHRggogICAgSVB2NC3QsNC00YDQtdGBIGFwaS50ZWxlZ3JhbS5vcmcsINC60L7R
gtC+0YDRi9C5INC90LUg0L7RgtCy0LXRh9Cw0LXRgi4g0KHQvtC10LTQuNC90LXQvdC40LUg0LLQ
uNGB0LjRgiDQtNC+INGC0LDQudC80LDRg9GC0LAsCiAgICDQuCDQsdC+0YIg0LLRi9Cz0LvRj9C0
0LjRgiDRgdC70L7QvNCw0L3QvdGL0LwuINCX0LTQtdGB0Ywg0YHQtdC80LXQudGB0YLQstC+INC3
0LDQtNCw0ZHRgtGB0Y8g0Y/QstC90L4uCiAgICAiIiIKCiAgICBkZWYgX19pbml0X18oc2VsZiwg
aG9zdCwgZmFtaWx5LCB0aW1lb3V0LCBjb250ZXh0KToKICAgICAgICBzdXBlcigpLl9faW5pdF9f
KGhvc3QsIHRpbWVvdXQ9dGltZW91dCwgY29udGV4dD1jb250ZXh0KQogICAgICAgIHNlbGYuX2Zh
bWlseSA9IGZhbWlseQoKICAgIGRlZiBjb25uZWN0KHNlbGYpOgogICAgICAgIGxhc3RfZXJyb3Ig
PSBOb25lCiAgICAgICAgdHJ5OgogICAgICAgICAgICBpbmZvcyA9IHNvY2tldC5nZXRhZGRyaW5m
byhzZWxmLmhvc3QsIHNlbGYucG9ydCwgc2VsZi5fZmFtaWx5LCBzb2NrZXQuU09DS19TVFJFQU0p
CiAgICAgICAgZXhjZXB0IE9TRXJyb3IgYXMgZXhjOgogICAgICAgICAgICByYWlzZSBPU0Vycm9y
KCLQvdC1INGA0LDQt9GA0LXRiNCw0LXRgtGB0Y8gJXM6ICVzIiAlIChzZWxmLmhvc3QsIGV4Yykp
CiAgICAgICAgaWYgbm90IGluZm9zOgogICAgICAgICAgICByYWlzZSBPU0Vycm9yKCLQvdC10YIg
0LDQtNGA0LXRgdC+0LIg0LTQu9GPINGB0LXQvNC10LnRgdGC0LLQsCAlcyIgJSBzZWxmLl9mYW1p
bHkpCiAgICAgICAgZm9yIGFmLCBzb2NrdHlwZSwgcHJvdG8sIF9jYW5vbiwgc2EgaW4gaW5mb3M6
CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHNvY2sgPSBzb2NrZXQuc29ja2V0KGFm
LCBzb2NrdHlwZSwgcHJvdG8pCiAgICAgICAgICAgIGV4Y2VwdCBPU0Vycm9yIGFzIGV4YzoKICAg
ICAgICAgICAgICAgIGxhc3RfZXJyb3IgPSBleGMKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAg
ICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHNvY2suc2V0dGltZW91dChzZWxmLnRpbWVv
dXQpCiAgICAgICAgICAgICAgICBzb2NrLmNvbm5lY3Qoc2EpCiAgICAgICAgICAgIGV4Y2VwdCBP
U0Vycm9yIGFzIGV4YzoKICAgICAgICAgICAgICAgIGxhc3RfZXJyb3IgPSBleGMKICAgICAgICAg
ICAgICAgIHNvY2suY2xvc2UoKQogICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAg
c2VsZi5zb2NrID0gc2VsZi5fY29udGV4dC53cmFwX3NvY2tldChzb2NrLCBzZXJ2ZXJfaG9zdG5h
bWU9c2VsZi5ob3N0KQogICAgICAgICAgICByZXR1cm4KICAgICAgICByYWlzZSBsYXN0X2Vycm9y
IGlmIGxhc3RfZXJyb3IgZWxzZSBPU0Vycm9yKCLQvdC1INGD0LTQsNC70L7RgdGMINC/0L7QtNC6
0LvRjtGH0LjRgtGM0YHRjyIpCgoKY2xhc3MgVGVsZWdyYW1UcmFuc3BvcnQ6CiAgICAiIiLQl9C9
0LDQtdGCLCDQv9C+INC60LDQutC+0LzRgyDRgdC10LzQtdC50YHRgtCy0YMg0LDQtNGA0LXRgdC+
0LIgVGVsZWdyYW0g0L7RgtCy0LXRh9Cw0LXRgiwg0Lgg0L/QvtC80L3QuNGCINGN0YLQvi4iIiIK
CiAgICBPUkRFUiA9IHsKICAgICAgICAiYXV0byI6IFtzb2NrZXQuQUZfSU5FVDYsIHNvY2tldC5B
Rl9JTkVUXSwKICAgICAgICAiaXB2NiI6IFtzb2NrZXQuQUZfSU5FVDZdLAogICAgICAgICJpcHY0
IjogW3NvY2tldC5BRl9JTkVUXSwKICAgIH0KICAgIE5BTUVTID0ge3NvY2tldC5BRl9JTkVUNjog
IklQdjYiLCBzb2NrZXQuQUZfSU5FVDogIklQdjQifQoKICAgIGRlZiBfX2luaXRfXyhzZWxmLCB0
b2tlbiwgcHJlZmVyZW5jZT0iYXV0byIsIHRpbWVvdXQ9MTIuMCk6CiAgICAgICAgc2VsZi5fdG9r
ZW4gPSB0b2tlbgogICAgICAgIHNlbGYuX2NhbmRpZGF0ZXMgPSBzZWxmLk9SREVSLmdldChwcmVm
ZXJlbmNlLCBzZWxmLk9SREVSWyJhdXRvIl0pCiAgICAgICAgc2VsZi5fdGltZW91dCA9IHRpbWVv
dXQKICAgICAgICBzZWxmLl9wcmVmZXJyZWQgPSBOb25lCiAgICAgICAgc2VsZi5fc3NsID0gc3Ns
LmNyZWF0ZV9kZWZhdWx0X2NvbnRleHQoKQogICAgICAgIHNlbGYuX2xvY2sgPSB0aHJlYWRpbmcu
TG9jaygpCgogICAgQHByb3BlcnR5CiAgICBkZWYgd29ya2luZ19wYXRoKHNlbGYpOgogICAgICAg
IGlmIHNlbGYuX3ByZWZlcnJlZCBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4gItC90LXQuNC3
0LLQtdGB0YLQvdC+IgogICAgICAgIHJldHVybiBzZWxmLk5BTUVTLmdldChzZWxmLl9wcmVmZXJy
ZWQsICLQvdC10LjQt9Cy0LXRgdGC0L3QviIpCgogICAgZGVmIHByb2JlKHNlbGYpOgogICAgICAg
ICIiItCf0YDQvtCy0LXRgNGP0LXRgiDQvtCx0LAg0L/Rg9GC0Lgg0Lgg0L/QuNGI0LXRgiDQsiDQ
u9C+0LMsINC60LDQutC+0Lkg0L7RgtCy0LXRh9Cw0LXRgi4g0JLRi9C30YvQstCw0LXRgtGB0Y8g
0L/RgNC4INGB0YLQsNGA0YLQtS4iIiIKICAgICAgICByZXN1bHRzID0ge30KICAgICAgICBmb3Ig
ZmFtaWx5IGluIChzb2NrZXQuQUZfSU5FVDYsIHNvY2tldC5BRl9JTkVUKToKICAgICAgICAgICAg
bmFtZSA9IHNlbGYuTkFNRVNbZmFtaWx5XQogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAg
ICBpbmZvcyA9IHNvY2tldC5nZXRhZGRyaW5mbyhURUxFR1JBTV9IT1NULCA0NDMsIGZhbWlseSwg
c29ja2V0LlNPQ0tfU1RSRUFNKQogICAgICAgICAgICBleGNlcHQgT1NFcnJvciBhcyBleGM6CiAg
ICAgICAgICAgICAgICByZXN1bHRzW25hbWVdID0gItC90LXRgiDQsNC00YDQtdGB0LAgKCVzKSIg
JSBleGMKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGlmIG5vdCBpbmZvczoK
ICAgICAgICAgICAgICAgIHJlc3VsdHNbbmFtZV0gPSAi0L3QtdGCINCw0LTRgNC10YHQsCIKICAg
ICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGFkZHJlc3MgPSBpbmZvc1swXVs0XVsw
XQogICAgICAgICAgICBzdGFydGVkID0gdGltZS5tb25vdG9uaWMoKQogICAgICAgICAgICBjb25u
ID0gTm9uZQogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAjINCf0YDQvtCy0LXRgNGP
0LXQvCDQv9C+0LvQvdC+0YbQtdC90L3Ri9C5IEhUVFBTLdC30LDQv9GA0L7RgSwg0LAg0L3QtSDR
gtC+0LvRjNC60L4gVENQLWNvbm5lY3QuCiAgICAgICAgICAgICAgICAjINCk0LjQu9GM0YLRgNCw
0YbQuNGPINGD0LzQtdC10YIg0L/RgNC40L3Rj9GC0YwgVENQINC4INC+0LHQvtGA0LLQsNGC0Ywg
0YHQvtC10LTQuNC90LXQvdC40LUg0YPQttC1CiAgICAgICAgICAgICAgICAjINC90LAgVExTOiDR
h9C40YHRgtGL0LkgY29ubmVjdCgpINC00LDQuyDQsdGLINC70L7QttC90L7QtSDCq9GA0LDQsdC+
0YLQsNC10YLCuy4KICAgICAgICAgICAgICAgIGNvbm4gPSBGYW1pbHlIVFRQU0Nvbm5lY3Rpb24o
VEVMRUdSQU1fSE9TVCwgZmFtaWx5LCA4LjAsIHNlbGYuX3NzbCkKICAgICAgICAgICAgICAgIGNv
bm4ucmVxdWVzdCgiR0VUIiwgIi8iLCBoZWFkZXJzPXsiVXNlci1BZ2VudCI6ICIlcy8lcyIgJSAo
QVBQX05BTUUsIFZFUlNJT04pfSkKICAgICAgICAgICAgICAgIHN0YXR1cyA9IGNvbm4uZ2V0cmVz
cG9uc2UoKS5zdGF0dXMKICAgICAgICAgICAgICAgIHJlc3VsdHNbbmFtZV0gPSAi0L7RgtCy0LXR
h9Cw0LXRgiDQt9CwICVkINC80YEgKCVzLCBIVFRQICVzKSIgJSAoCiAgICAgICAgICAgICAgICAg
ICAgaW50KCh0aW1lLm1vbm90b25pYygpIC0gc3RhcnRlZCkgKiAxMDAwKSwKICAgICAgICAgICAg
ICAgICAgICBhZGRyZXNzLAogICAgICAgICAgICAgICAgICAgIHN0YXR1cywKICAgICAgICAgICAg
ICAgICkKICAgICAgICAgICAgICAgIHdpdGggc2VsZi5fbG9jazoKICAgICAgICAgICAgICAgICAg
ICBpZiBzZWxmLl9wcmVmZXJyZWQgaXMgTm9uZSBhbmQgZmFtaWx5IGluIHNlbGYuX2NhbmRpZGF0
ZXM6CiAgICAgICAgICAgICAgICAgICAgICAgIHNlbGYuX3ByZWZlcnJlZCA9IGZhbWlseQogICAg
ICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzogICMgbm9xYTogQkxFMDAxCiAgICAgICAg
ICAgICAgICByZXN1bHRzW25hbWVdID0gItC90LUg0L7RgtCy0LXRh9Cw0LXRgiAoJXMpIiAlIGV4
YwogICAgICAgICAgICBmaW5hbGx5OgogICAgICAgICAgICAgICAgaWYgY29ubiBpcyBub3QgTm9u
ZToKICAgICAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgICAgIGNvbm4u
Y2xvc2UoKQogICAgICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246ICAjIG5vcWE6IEJM
RTAwMQogICAgICAgICAgICAgICAgICAgICAgICBwYXNzCiAgICAgICAgZm9yIG5hbWUsIHZlcmRp
Y3QgaW4gcmVzdWx0cy5pdGVtcygpOgogICAgICAgICAgICBsb2cuaW5mbygiVGVsZWdyYW0g0L/Q
viAlczogJXMiLCBuYW1lLCB2ZXJkaWN0KQogICAgICAgIGlmIHNlbGYuX3ByZWZlcnJlZCBpcyBO
b25lOgogICAgICAgICAgICBsb2cud2FybmluZygKICAgICAgICAgICAgICAgICLQndC4INC+0LTQ
uNC9INC/0YPRgtGMINC00L4gJXMg0L3QtSDQvtGC0LLQtdGC0LjQuyDQv9GA0Lgg0YHRgtCw0YDR
gtC1LiAiCiAgICAgICAgICAgICAgICAi0JfQsNGP0LLQutC4INCx0YPQtNGD0YIg0YHQvtGF0YDQ
sNC90Y/RgtGM0YHRjyDQsiBvdXRib3gg0Lgg0L/QtdGA0LXQvtGC0L/RgNCw0LLQu9GP0YLRjNGB
0Y8uIiwKICAgICAgICAgICAgICAgIFRFTEVHUkFNX0hPU1QsCiAgICAgICAgICAgICkKICAgICAg
ICBlbHNlOgogICAgICAgICAgICBsb2cuaW5mbygi0JLRi9Cx0YDQsNC9INC/0YPRgtGMINC00L4g
VGVsZWdyYW06ICVzIiwgc2VsZi53b3JraW5nX3BhdGgpCiAgICAgICAgcmV0dXJuIHJlc3VsdHMK
CiAgICBkZWYgX29yZGVyKHNlbGYpOgogICAgICAgIHdpdGggc2VsZi5fbG9jazoKICAgICAgICAg
ICAgcHJlZmVycmVkID0gc2VsZi5fcHJlZmVycmVkCiAgICAgICAgaWYgcHJlZmVycmVkIGlzIE5v
bmU6CiAgICAgICAgICAgIHJldHVybiBsaXN0KHNlbGYuX2NhbmRpZGF0ZXMpCiAgICAgICAgcmV0
dXJuIFtwcmVmZXJyZWRdICsgW2YgZm9yIGYgaW4gc2VsZi5fY2FuZGlkYXRlcyBpZiBmICE9IHBy
ZWZlcnJlZF0KCiAgICBkZWYgc2VuZF9tZXNzYWdlKHNlbGYsIHRleHQpOgogICAgICAgICIiItCS
0L7Qt9Cy0YDQsNGJ0LDQtdGCIChUcnVlLCBOb25lKSDQu9C40LHQviAoRmFsc2UsICfQv9GA0LjR
h9C40L3QsCcpLiIiIgogICAgICAgIGlmIG5vdCBzZWxmLl90b2tlbiBvciBub3QgQ0hBVF9JRDoK
ICAgICAgICAgICAgcmV0dXJuIEZhbHNlLCAi0L3QtSDQt9Cw0LTQsNC90YsgQVVSRUFfS1ZJWl9C
T1RfVE9LRU4g0LjQu9C4IEFVUkVBX0tWSVpfQ0hBVF9JRCIKCiAgICAgICAgcGF5bG9hZCA9IGpz
b24uZHVtcHMoCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJjaGF0X2lkIjogQ0hBVF9J
RCwKICAgICAgICAgICAgICAgICJ0ZXh0IjogdGV4dCwKICAgICAgICAgICAgICAgICJwYXJzZV9t
b2RlIjogIkhUTUwiLAogICAgICAgICAgICAgICAgImRpc2FibGVfd2ViX3BhZ2VfcHJldmlldyI6
IFRydWUsCiAgICAgICAgICAgIH0KICAgICAgICApLmVuY29kZSgidXRmLTgiKQoKICAgICAgICBl
cnJvcnMgPSBbXQogICAgICAgIGZvciBmYW1pbHkgaW4gc2VsZi5fb3JkZXIoKToKICAgICAgICAg
ICAgbmFtZSA9IHNlbGYuTkFNRVNbZmFtaWx5XQogICAgICAgICAgICBjb25uID0gTm9uZQogICAg
ICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBjb25uID0gRmFtaWx5SFRUUFNDb25uZWN0aW9u
KAogICAgICAgICAgICAgICAgICAgIFRFTEVHUkFNX0hPU1QsIGZhbWlseSwgc2VsZi5fdGltZW91
dCwgc2VsZi5fc3NsCiAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICBjb25uLnJlcXVl
c3QoCiAgICAgICAgICAgICAgICAgICAgIlBPU1QiLAogICAgICAgICAgICAgICAgICAgICIvYm90
JXMvc2VuZE1lc3NhZ2UiICUgc2VsZi5fdG9rZW4sCiAgICAgICAgICAgICAgICAgICAgYm9keT1w
YXlsb2FkLAogICAgICAgICAgICAgICAgICAgIGhlYWRlcnM9ewogICAgICAgICAgICAgICAgICAg
ICAgICAiQ29udGVudC1UeXBlIjogImFwcGxpY2F0aW9uL2pzb24iLAogICAgICAgICAgICAgICAg
ICAgICAgICAiQ29udGVudC1MZW5ndGgiOiBzdHIobGVuKHBheWxvYWQpKSwKICAgICAgICAgICAg
ICAgICAgICAgICAgIlVzZXItQWdlbnQiOiAiJXMvJXMiICUgKEFQUF9OQU1FLCBWRVJTSU9OKSwK
ICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAg
cmVzcG9uc2UgPSBjb25uLmdldHJlc3BvbnNlKCkKICAgICAgICAgICAgICAgIHJhdyA9IHJlc3Bv
bnNlLnJlYWQoNjQgKiAxMDI0KQogICAgICAgICAgICAgICAgaWYgcmVzcG9uc2Uuc3RhdHVzID09
IDIwMDoKICAgICAgICAgICAgICAgICAgICB3aXRoIHNlbGYuX2xvY2s6CiAgICAgICAgICAgICAg
ICAgICAgICAgIHNlbGYuX3ByZWZlcnJlZCA9IGZhbWlseQogICAgICAgICAgICAgICAgICAgIHJl
dHVybiBUcnVlLCBOb25lCiAgICAgICAgICAgICAgICAjINCi0L7QutC10L0v0YfQsNGCINC90LXQ
stC10YDQvdGLIOKAlCDQv9C10YDQtdCx0LjRgNCw0YLRjCDRgdC10LzQtdC50YHRgtCy0LAg0LHQ
tdGB0YHQvNGL0YHQu9C10L3QvdC+LgogICAgICAgICAgICAgICAgZGV0YWlsID0gX2Rlc2NyaWJl
X3RlbGVncmFtX2Vycm9yKHJlc3BvbnNlLnN0YXR1cywgcmF3KQogICAgICAgICAgICAgICAgZXJy
b3JzLmFwcGVuZCgiJXM6ICVzIiAlIChuYW1lLCBkZXRhaWwpKQogICAgICAgICAgICAgICAgaWYg
cmVzcG9uc2Uuc3RhdHVzIGluICg0MDAsIDQwMSwgNDAzLCA0MDQpOgogICAgICAgICAgICAgICAg
ICAgIGJyZWFrCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOiAgIyBub3FhOiBC
TEUwMDEg4oCUINC90LDRgNGD0LbRgyDRg9GF0L7QtNC40YIg0YLQtdC60YHRgtC+0Lwg0LIg0LvQ
vtCzCiAgICAgICAgICAgICAgICBlcnJvcnMuYXBwZW5kKCIlczogJXMiICUgKG5hbWUsIGV4Yykp
CiAgICAgICAgICAgIGZpbmFsbHk6CiAgICAgICAgICAgICAgICBpZiBjb25uIGlzIG5vdCBOb25l
OgogICAgICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICAgICAgY29ubi5j
bG9zZSgpCiAgICAgICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjogICMgbm9xYTogQkxF
MDAxCiAgICAgICAgICAgICAgICAgICAgICAgIHBhc3MKICAgICAgICB3aXRoIHNlbGYuX2xvY2s6
CiAgICAgICAgICAgIHNlbGYuX3ByZWZlcnJlZCA9IE5vbmUKICAgICAgICByZXR1cm4gRmFsc2Us
ICI7ICIuam9pbihlcnJvcnMpIG9yICLQvdC10LjQt9Cy0LXRgdGC0L3QsNGPINC+0YjQuNCx0LrQ
sCIKCgpkZWYgX2Rlc2NyaWJlX3RlbGVncmFtX2Vycm9yKHN0YXR1cywgcmF3KToKICAgIHRyeToK
ICAgICAgICBkYXRhID0ganNvbi5sb2FkcyhyYXcuZGVjb2RlKCJ1dGYtOCIsICJyZXBsYWNlIikp
CiAgICAgICAgcmV0dXJuICJIVFRQICVzICVzIiAlIChzdGF0dXMsIGRhdGEuZ2V0KCJkZXNjcmlw
dGlvbiIsICIiKSkKICAgIGV4Y2VwdCBFeGNlcHRpb246ICAjIG5vcWE6IEJMRTAwMQogICAgICAg
IHJldHVybiAiSFRUUCAlcyIgJSBzdGF0dXMKCgojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAjCiMg0KXR
gNCw0L3QuNC70LjRidC1INC30LDRj9Cy0L7QugojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAjCgpkZWYg
X2ZzeW5jX2RpcihwYXRoKToKICAgIHRyeToKICAgICAgICBmZCA9IG9zLm9wZW4ocGF0aCwgb3Mu
T19ESVJFQ1RPUlkpCiAgICBleGNlcHQgKEF0dHJpYnV0ZUVycm9yLCBPU0Vycm9yKToKICAgICAg
ICByZXR1cm4KICAgIHRyeToKICAgICAgICBvcy5mc3luYyhmZCkKICAgIGZpbmFsbHk6CiAgICAg
ICAgb3MuY2xvc2UoZmQpCgoKY2xhc3MgTGVhZFN0b3JlOgogICAgIiIi0JbRg9GA0L3QsNC7INCy
0YHQtdGFINC30LDRj9Cy0L7QuiArINC+0YfQtdGA0LXQtNGMINC90LXQvtGC0L/RgNCw0LLQu9C1
0L3QvdGL0YUuCgogICAgbGVhZHMuanNvbmwg4oCUINCy0LXRh9C90YvQuSDQttGD0YDQvdCw0Lss
INGC0YPQtNCwINC/0LjRiNC10YLRgdGPINC60LDQttC00LDRjyDQt9Cw0Y/QstC60LAuCiAgICBv
dXRib3gvICAgICDigJQg0L/QviDRhNCw0LnQu9GDINC90LAg0L3QtdC+0YLQv9GA0LDQstC70LXQ
vdC90YPRjiDQt9Cw0Y/QstC60YMuCiAgICBzZW50LyAgICAgICDigJQg0YLQviwg0YfRgtC+INCy
INC40YLQvtCz0LUg0YPRiNC70L4gKNGH0YLQvtCx0Ysgb3V0Ym94INC90LUg0YDQvtGBINC4INCx
0YvQu9C+INCy0LjQtNC90L4g0LjRgdGC0L7RgNC40Y4pLgogICAgIiIiCgogICAgZGVmIF9faW5p
dF9fKHNlbGYsIGRhdGFfZGlyKToKICAgICAgICBzZWxmLmRhdGFfZGlyID0gZGF0YV9kaXIKICAg
ICAgICBzZWxmLl9sb2NrID0gdGhyZWFkaW5nLkxvY2soKQogICAgICAgIGZvciBwYXRoIGluIChk
YXRhX2RpciwgT1VUQk9YX0RJUiwgU0VOVF9ESVIpOgogICAgICAgICAgICBvcy5tYWtlZGlycyhw
YXRoLCBleGlzdF9vaz1UcnVlKQoKICAgIGRlZiBhcHBlbmQoc2VsZiwgbGVhZCk6CiAgICAgICAg
bGluZSA9IGpzb24uZHVtcHMobGVhZCwgZW5zdXJlX2FzY2lpPUZhbHNlKSArICJcbiIKICAgICAg
ICB3aXRoIHNlbGYuX2xvY2s6CiAgICAgICAgICAgIHdpdGggb3BlbihMRUFEU19MT0csICJhIiwg
ZW5jb2Rpbmc9InV0Zi04IikgYXMgaGFuZGxlOgogICAgICAgICAgICAgICAgaGFuZGxlLndyaXRl
KGxpbmUpCiAgICAgICAgICAgICAgICBoYW5kbGUuZmx1c2goKQogICAgICAgICAgICAgICAgb3Mu
ZnN5bmMoaGFuZGxlLmZpbGVubygpKQoKICAgIGRlZiBlbnF1ZXVlKHNlbGYsIGxlYWQpOgogICAg
ICAgIHBhdGggPSBvcy5wYXRoLmpvaW4oT1VUQk9YX0RJUiwgIiVzLmpzb24iICUgbGVhZFsiaWQi
XSkKICAgICAgICB0bXAgPSBwYXRoICsgIi50bXAiCiAgICAgICAgd2l0aCBvcGVuKHRtcCwgInci
LCBlbmNvZGluZz0idXRmLTgiKSBhcyBoYW5kbGU6CiAgICAgICAgICAgIGpzb24uZHVtcChsZWFk
LCBoYW5kbGUsIGVuc3VyZV9hc2NpaT1GYWxzZSwgaW5kZW50PTEpCiAgICAgICAgICAgIGhhbmRs
ZS5mbHVzaCgpCiAgICAgICAgICAgIG9zLmZzeW5jKGhhbmRsZS5maWxlbm8oKSkKICAgICAgICBv
cy5yZXBsYWNlKHRtcCwgcGF0aCkKICAgICAgICBfZnN5bmNfZGlyKE9VVEJPWF9ESVIpCgogICAg
ZGVmIHBlbmRpbmcoc2VsZik6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBuYW1lcyA9IHNvcnRl
ZChuIGZvciBuIGluIG9zLmxpc3RkaXIoT1VUQk9YX0RJUikgaWYgbi5lbmRzd2l0aCgiLmpzb24i
KSkKICAgICAgICBleGNlcHQgRmlsZU5vdEZvdW5kRXJyb3I6CiAgICAgICAgICAgIHJldHVybiBb
XQogICAgICAgIG91dCA9IFtdCiAgICAgICAgZm9yIG5hbWUgaW4gbmFtZXM6CiAgICAgICAgICAg
IHRyeToKICAgICAgICAgICAgICAgIHdpdGggb3Blbihvcy5wYXRoLmpvaW4oT1VUQk9YX0RJUiwg
bmFtZSksIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGhhbmRsZToKICAgICAgICAgICAgICAgICAgICBv
dXQuYXBwZW5kKGpzb24ubG9hZChoYW5kbGUpKQogICAgICAgICAgICBleGNlcHQgKE9TRXJyb3Is
IFZhbHVlRXJyb3IpIGFzIGV4YzoKICAgICAgICAgICAgICAgIGxvZy5lcnJvcigi0J3QtSDRh9C4
0YLQsNC10YLRgdGPICVzOiAlcyIsIG5hbWUsIGV4YykKICAgICAgICByZXR1cm4gb3V0CgogICAg
ZGVmIG1hcmtfc2VudChzZWxmLCBsZWFkX2lkKToKICAgICAgICBzcmMgPSBvcy5wYXRoLmpvaW4o
T1VUQk9YX0RJUiwgIiVzLmpzb24iICUgbGVhZF9pZCkKICAgICAgICBkc3QgPSBvcy5wYXRoLmpv
aW4oU0VOVF9ESVIsICIlcy5qc29uIiAlIGxlYWRfaWQpCiAgICAgICAgdHJ5OgogICAgICAgICAg
ICBvcy5yZXBsYWNlKHNyYywgZHN0KQogICAgICAgIGV4Y2VwdCBGaWxlTm90Rm91bmRFcnJvcjoK
ICAgICAgICAgICAgcGFzcwoKICAgIGRlZiBwZW5kaW5nX2NvdW50KHNlbGYpOgogICAgICAgIHRy
eToKICAgICAgICAgICAgcmV0dXJuIHN1bSgxIGZvciBuIGluIG9zLmxpc3RkaXIoT1VUQk9YX0RJ
UikgaWYgbi5lbmRzd2l0aCgiLmpzb24iKSkKICAgICAgICBleGNlcHQgRmlsZU5vdEZvdW5kRXJy
b3I6CiAgICAgICAgICAgIHJldHVybiAwCgoKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gIwojINCg0LDQ
t9Cx0L7RgCDQuCDQv9GA0L7QstC10YDQutCwINC30LDRj9Cy0LrQuAojIC0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLSAjCgpQSE9ORV9ESUdJVFMgPSByZS5jb21waWxlKHIiXGQiKQpOQU1FX09LID0gcmUuY29t
cGlsZShyIl5bXHdcc1wtJ+KAmS5dezIsNjB9JCIsIHJlLlVOSUNPREUpCkNIQU5ORUxTID0geyJ0
ZWxlZ3JhbSI6ICJUZWxlZ3JhbSIsICJjYWxsIjogItCX0LLQvtC90L7QuiJ9CgoKUEhPTkVfQUxM
T1dFRCA9IHJlLmNvbXBpbGUociJeW1xkXHMrKClcLS5dKyQiKQoKCmRlZiBhY2NlcHRfcGhvbmUo
cmF3KToKICAgICIiItCf0YDQuNC90LjQvNCw0LXRgiDQvdC+0LzQtdGAINGA0L7QstC90L4g0LIg
0YLQvtC8INCy0LjQtNC1LCDQsiDQutCw0LrQvtC8INC10LPQviDQvdCw0L/QtdGH0LDRgtCw0LvQ
uC4KCiAgICDQndC40YfQtdCz0L4g0L3QtSDQv9C10YDQtdGB0YLQsNCy0LvRj9C10Lwg0Lgg0L3Q
tSDQtNC+0L/QuNGB0YvQstCw0LXQvDog0YfQtdC70L7QstC10Log0LLQstGR0Lsg0LrQsNC6INC1
0LzRgyDRg9C00L7QsdC90L4sCiAgICDQuCDQsiDQt9Cw0Y/QstC60LUg0LLQu9Cw0LTQtdC70LXR
hiDRg9Cy0LjQtNC40YIg0LXQs9C+INC20LUg0LfQsNC/0LjRgdGMLiDQn9GA0L7QstC10YDRj9C1
0Lwg0YLQvtC70YzQutC+LCDRh9GC0L4g0Y3RgtC+CiAgICDQstC+0L7QsdGJ0LUg0L/QvtGF0L7Q
ttC1INC90LAg0L3QvtC80LXRgCDigJQg0L7RgiDQtNC10YHRj9GC0Lgg0LTQviDQv9GP0YLQvdCw
0LTRhtCw0YLQuCDRhtC40YTRgCDQuCDQsdC10Lcg0LHRg9C60LIuCiAgICDQktC+0LfQstGA0LDR
idCw0LXRgiAo0LrQsNC6X9C90LDQv9C10YfQsNGC0LDQvdC+LCDRgtC+0LvRjNC60L5f0YbQuNGE
0YDRiykg0LvQuNCx0L4gKE5vbmUsIE5vbmUpLgogICAgIiIiCiAgICB2YWx1ZSA9IChyYXcgb3Ig
IiIpLnN0cmlwKCkKICAgIGlmIG5vdCB2YWx1ZSBvciBsZW4odmFsdWUpID4gNDA6CiAgICAgICAg
cmV0dXJuIE5vbmUsIE5vbmUKICAgIGlmIG5vdCBQSE9ORV9BTExPV0VELm1hdGNoKHZhbHVlKToK
ICAgICAgICByZXR1cm4gTm9uZSwgTm9uZQogICAgZGlnaXRzID0gIiIuam9pbihQSE9ORV9ESUdJ
VFMuZmluZGFsbCh2YWx1ZSkpCiAgICBpZiBub3QgMTAgPD0gbGVuKGRpZ2l0cykgPD0gMTU6CiAg
ICAgICAgcmV0dXJuIE5vbmUsIE5vbmUKICAgIHJldHVybiB2YWx1ZSwgZGlnaXRzCgoKIyDQndC4
0Log0LIgVGVsZWdyYW06IDXigJMzMiDQt9C90LDQutCwLCDQu9Cw0YLQuNC90LjRhtCwLCDRhtC4
0YTRgNGLINC4INC/0L7QtNGH0ZHRgNC60LjQstCw0L3QuNC1LCDQvdCw0YfQuNC90LDQtdGC0YHR
jwojINGBINCx0YPQutCy0YsuINCf0LjRiNGD0YIg0L/Qvi3RgNCw0LfQvdC+0LzRgyDigJQgwqtA
bmFtZcK7LCDCq25hbWXCuywgwqt0Lm1lL25hbWXCuywg0YHRgdGL0LvQutC+0Lkg0YbQtdC70LjQ
utC+0LwuClRFTEVHUkFNX05JQ0sgPSByZS5jb21waWxlKHIiXltBLVphLXpdW0EtWmEtejAtOV9d
ezQsMzF9JCIpClRFTEVHUkFNX1BSRUZJWCA9IHJlLmNvbXBpbGUociJeKGh0dHBzPzovLyk/KHd3
d1wuKT90KGVsZWdyYW0pP1wubWUvIiwgcmUuSUdOT1JFQ0FTRSkKCgpkZWYgYWNjZXB0X3RlbGVn
cmFtKHJhdyk6CiAgICAiIiLQn9GA0LjQvdC40LzQsNC10YIg0L3QuNC6INGA0L7QstC90L4g0LIg
0YLQvtC8INCy0LjQtNC1LCDQsiDQutCw0LrQvtC8INC10LPQviDQvdCw0L/QtdGH0LDRgtCw0LvQ
uC4KCiAgICDQktC+0LfQstGA0LDRidCw0LXRgiAo0LrQsNC6X9C90LDQv9C10YfQsNGC0LDQvdC+
LCDRgtC+0LvRjNC60L5f0L3QuNC6KSDQu9C40LHQviAoTm9uZSwgTm9uZSkuINCh0LDQvCDQvdC4
0LoKICAgINC90YPQttC10L0g0LTQu9GPINGB0YHRi9C70LrQuCDQsiDRgdC+0L7QsdGJ0LXQvdC4
0Lgg0LLQu9Cw0LTQtdC70YzRhtGDOiDQv9C+INC90LXQvNGDINC+0YLQutGA0YvQstCw0LXRgtGB
0Y8g0LTQuNCw0LvQvtCzLgogICAgIiIiCiAgICB2YWx1ZSA9IChyYXcgb3IgIiIpLnN0cmlwKCkK
ICAgIGlmIG5vdCB2YWx1ZSBvciBsZW4odmFsdWUpID4gODA6CiAgICAgICAgcmV0dXJuIE5vbmUs
IE5vbmUKICAgIG5pY2sgPSBURUxFR1JBTV9QUkVGSVguc3ViKCIiLCB2YWx1ZSkubHN0cmlwKCJA
IikKICAgIG5pY2sgPSByZS5zcGxpdChyIlsvPyNdIiwgbmljaywgMSlbMF0uc3RyaXAoKQogICAg
aWYgbm90IFRFTEVHUkFNX05JQ0subWF0Y2gobmljayk6CiAgICAgICAgcmV0dXJuIE5vbmUsIE5v
bmUKICAgIHJldHVybiB2YWx1ZSwgbmljawoKCmRlZiBjbGVhbl90ZXh0KHZhbHVlLCBsaW1pdCk6
CiAgICBpZiBub3QgaXNpbnN0YW5jZSh2YWx1ZSwgc3RyKToKICAgICAgICByZXR1cm4gIiIKICAg
IHJldHVybiB2YWx1ZS5yZXBsYWNlKCJcciIsICIgIikucmVwbGFjZSgiXG4iLCAiICIpLnN0cmlw
KClbOmxpbWl0XQoKCmRlZiBwYXJzZV9sZWFkKHBheWxvYWQsIHJlbW90ZV9pcCwgdXNlcl9hZ2Vu
dCk6CiAgICBlcnJvcnMgPSB7fQoKICAgIG5hbWUgPSBjbGVhbl90ZXh0KHBheWxvYWQuZ2V0KCJu
YW1lIiksIDYwKQogICAgaWYgbGVuKG5hbWUpIDwgMiBvciBub3QgTkFNRV9PSy5tYXRjaChuYW1l
KToKICAgICAgICBlcnJvcnNbIm5hbWUiXSA9ICLQmNC80Y8g0L3QtSDQv9C+0YXQvtC20LUg0L3Q
sCDQuNC80Y8iCgogICAgY2hhbm5lbCA9IHBheWxvYWQuZ2V0KCJjaGFubmVsIikKICAgIGlmIGNo
YW5uZWwgbm90IGluIENIQU5ORUxTOgogICAgICAgIGVycm9yc1siY2hhbm5lbCJdID0gItCd0LXQ
uNC30LLQtdGB0YLQvdGL0Lkg0YHQv9C+0YHQvtCxINGB0LLRj9C30LgiCgogICAgIyDQp9GC0L4g
0YHQv9GA0LDRiNC40LLQsNC70Lgg0L3QsCDRjdC60YDQsNC90LUsINGC0L4g0Lgg0L/RgNC+0LLQ
tdGA0Y/QtdC8LiDQktGL0LHRgNCw0LsgVGVsZWdyYW0g4oCUINC/0YDQuNGB0LvQsNC7CiAgICAj
INC90LjQuiwg0Lgg0YLQtdC70LXRhNC+0L3QsCDRgyDQvdC10LPQviDQvdC10YI7INCy0YvQsdGA
0LDQuyDQt9Cy0L7QvdC+0Log4oCUINC/0YDQuNGB0LvQsNC7INC90L7QvNC10YAuCiAgICBwaG9u
ZSA9IHBob25lX2RpZ2l0cyA9IE5vbmUKICAgIHRlbGVncmFtID0gdGVsZWdyYW1fbmljayA9IE5v
bmUKICAgIGlmIGNoYW5uZWwgPT0gInRlbGVncmFtIjoKICAgICAgICB0ZWxlZ3JhbSwgdGVsZWdy
YW1fbmljayA9IGFjY2VwdF90ZWxlZ3JhbShwYXlsb2FkLmdldCgidGVsZWdyYW0iKSkKICAgICAg
ICBpZiBub3QgdGVsZWdyYW06CiAgICAgICAgICAgIGVycm9yc1sidGVsZWdyYW0iXSA9ICLQrdGC
0L4g0L3QtSDQv9C+0YXQvtC20LUg0L3QsCDQvdC40Log0LIgVGVsZWdyYW0iCiAgICBlbHNlOgog
ICAgICAgIHBob25lLCBwaG9uZV9kaWdpdHMgPSBhY2NlcHRfcGhvbmUocGF5bG9hZC5nZXQoInBo
b25lIikpCiAgICAgICAgaWYgbm90IHBob25lOgogICAgICAgICAgICBlcnJvcnNbInBob25lIl0g
PSAi0K3RgtC+INC90LUg0L/QvtGF0L7QttC1INC90LAg0L3QvtC80LXRgCDRgtC10LvQtdGE0L7Q
vdCwIgoKICAgIGlmIGNsZWFuX3RleHQocGF5bG9hZC5nZXQoImNvbXBhbnkiKSwgMTAwKToKICAg
ICAgICAjINCb0L7QstGD0YjQutCwINC00LvRjyDQsdC+0YLQvtCyOiDQv9C+0LvQtSDRgdC60YDR
i9GC0L4g0L7RgiDRh9C10LvQvtCy0LXQutCwINC4INCy0YHQtdCz0LTQsCDQtNC+0LvQttC90L4g
0LHRi9GC0Ywg0L/Rg9GB0YLRi9C8LgogICAgICAgIGVycm9yc1siY29tcGFueSJdID0gInNwYW0i
CgogICAgYW5zd2VycyA9IHBheWxvYWQuZ2V0KCJhbnN3ZXJzIikKICAgIGlmIG5vdCBpc2luc3Rh
bmNlKGFuc3dlcnMsIGxpc3QpOgogICAgICAgIGFuc3dlcnMgPSBbXQogICAgc2FmZV9hbnN3ZXJz
ID0gW10KICAgIGZvciBpdGVtIGluIGFuc3dlcnNbOjEyXToKICAgICAgICBpZiBub3QgaXNpbnN0
YW5jZShpdGVtLCBkaWN0KToKICAgICAgICAgICAgY29udGludWUKICAgICAgICBzYWZlX2Fuc3dl
cnMuYXBwZW5kKAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAicXVlc3Rpb24iOiBjbGVh
bl90ZXh0KGl0ZW0uZ2V0KCJxdWVzdGlvbiIpLCAxMjApLAogICAgICAgICAgICAgICAgImFuc3dl
ciI6IGNsZWFuX3RleHQoaXRlbS5nZXQoImFuc3dlciIpLCAxMjApLAogICAgICAgICAgICB9CiAg
ICAgICAgKQoKICAgIHByaWNlID0gcGF5bG9hZC5nZXQoInByaWNlIikgaWYgaXNpbnN0YW5jZShw
YXlsb2FkLmdldCgicHJpY2UiKSwgZGljdCkgZWxzZSB7fQogICAgbG93ID0gcHJpY2UuZ2V0KCJs
b3ciKQogICAgaGlnaCA9IHByaWNlLmdldCgiaGlnaCIpCiAgICBpZiBub3QgaXNpbnN0YW5jZShs
b3csIChpbnQsIGZsb2F0KSkgb3Igbm90IDAgPD0gbG93IDw9IDEwXzAwMF8wMDA6CiAgICAgICAg
bG93ID0gTm9uZQogICAgaWYgbm90IGlzaW5zdGFuY2UoaGlnaCwgKGludCwgZmxvYXQpKSBvciBu
b3QgMCA8PSBoaWdoIDw9IDEwXzAwMF8wMDA6CiAgICAgICAgaGlnaCA9IE5vbmUKCiAgICBzb3Vy
Y2UgPSBwYXlsb2FkLmdldCgic291cmNlIikgaWYgaXNpbnN0YW5jZShwYXlsb2FkLmdldCgic291
cmNlIiksIGRpY3QpIGVsc2Uge30KICAgIHNhZmVfc291cmNlID0gewogICAgICAgIGtleTogY2xl
YW5fdGV4dChzb3VyY2UuZ2V0KGtleSksIDEyMCkKICAgICAgICBmb3Iga2V5IGluICgidXRtX3Nv
dXJjZSIsICJ1dG1fbWVkaXVtIiwgInV0bV9jYW1wYWlnbiIsICJ1dG1fdGVybSIsICJ1dG1fY29u
dGVudCIsICJyZWZlcnJlciIsICJwYWdlIikKICAgICAgICBpZiBzb3VyY2UuZ2V0KGtleSkKICAg
IH0KCiAgICBsZWFkID0gewogICAgICAgICJpZCI6IHV1aWQudXVpZDQoKS5oZXhbOjEyXSwKICAg
ICAgICAicmVjZWl2ZWRfYXQiOiBkYXRldGltZS5ub3codGltZXpvbmUudXRjKS5pc29mb3JtYXQo
dGltZXNwZWM9InNlY29uZHMiKSwKICAgICAgICAibmFtZSI6IG5hbWUsCiAgICAgICAgIyDQoNC+
0LLQvdC+INGC0L4sINGH0YLQviDQvdCw0L/QtdGH0LDRgtCw0Lsg0YfQtdC70L7QstC10LouINCX
0LDQv9C+0LvQvdC10L3QviDRgtC+INC/0L7Qu9C1LCDQutC+0YLQvtGA0L7QtSDQvtC9INCy0LjQ
tNC10LsuCiAgICAgICAgInBob25lIjogcGhvbmUsCiAgICAgICAgIyDQotC+0LvRjNC60L4g0YbQ
uNGE0YDRiyDigJQg0L3Rg9C20L3RiyDQtNC70Y8g0YHRgdGL0LvQutC4LCDQsiDRgdC+0L7QsdGJ
0LXQvdC40Lgg0L3QtSDQv9C+0LrQsNC30YvQstCw0Y7RgtGB0Y8uCiAgICAgICAgInBob25lX2Rp
Z2l0cyI6IHBob25lX2RpZ2l0cywKICAgICAgICAidGVsZWdyYW0iOiB0ZWxlZ3JhbSwKICAgICAg
ICAidGVsZWdyYW1fbmljayI6IHRlbGVncmFtX25pY2ssCiAgICAgICAgImNvbnRhY3QiOiB0ZWxl
Z3JhbSBvciBwaG9uZSBvciAi4oCUIiwKICAgICAgICAiY2hhbm5lbCI6IGNoYW5uZWwsCiAgICAg
ICAgImNoYW5uZWxfbGFiZWwiOiBDSEFOTkVMUy5nZXQoY2hhbm5lbCwgIuKAlCIpLAogICAgICAg
ICJhbnN3ZXJzIjogc2FmZV9hbnN3ZXJzLAogICAgICAgICJwcmljZSI6IHsibG93IjogbG93LCAi
aGlnaCI6IGhpZ2h9LAogICAgICAgICJzb3VyY2UiOiBzYWZlX3NvdXJjZSwKICAgICAgICAiY2xp
ZW50X2lkIjogY2xlYW5fdGV4dChwYXlsb2FkLmdldCgiY2xpZW50SWQiKSwgNjQpLAogICAgICAg
ICJyZW1vdGVfaXAiOiByZW1vdGVfaXAsCiAgICAgICAgInVzZXJfYWdlbnQiOiBjbGVhbl90ZXh0
KHVzZXJfYWdlbnQsIDIwMCksCiAgICB9CiAgICByZXR1cm4gbGVhZCwgZXJyb3JzCgoKZGVmIGVz
Y2FwZV9odG1sKHZhbHVlKToKICAgIHJldHVybiAoCiAgICAgICAgc3RyKHZhbHVlKQogICAgICAg
IC5yZXBsYWNlKCImIiwgIiZhbXA7IikKICAgICAgICAucmVwbGFjZSgiPCIsICImbHQ7IikKICAg
ICAgICAucmVwbGFjZSgiPiIsICImZ3Q7IikKICAgICkKCgpkZWYgZm9ybWF0X21vbmV5KHZhbHVl
KToKICAgIGlmIHZhbHVlIGlzIE5vbmU6CiAgICAgICAgcmV0dXJuICLigJQiCiAgICByZXR1cm4g
Ins6LH0iLmZvcm1hdChpbnQocm91bmQodmFsdWUpKSkucmVwbGFjZSgiLCIsICIgIikgKyAiIOKC
vSIKCgpkZWYgcmVuZGVyX21lc3NhZ2UobGVhZCk6CiAgICByZWNlaXZlZCA9IGRhdGV0aW1lLmZy
b21pc29mb3JtYXQobGVhZFsicmVjZWl2ZWRfYXQiXSkuYXN0aW1lem9uZShNU0spCiAgICBsaW5l
cyA9IFsKICAgICAgICAiPGI+0JfQsNGP0LLQutCwINGBINC60LLQuNC30LA8L2I+IiwKICAgICAg
ICAiIiwKICAgICAgICAiPGI+JXM8L2I+IiAlIGVzY2FwZV9odG1sKGxlYWRbIm5hbWUiXSksCiAg
ICAgICAgIiVzIMK3ICVzIiAlIChlc2NhcGVfaHRtbChsZWFkLmdldCgiY29udGFjdCIpIG9yICLi
gJQiKSwgZXNjYXBlX2h0bWwobGVhZFsiY2hhbm5lbF9sYWJlbCJdKSksCiAgICBdCiAgICBpZiBs
ZWFkLmdldCgidGVsZWdyYW1fbmljayIpOgogICAgICAgIGxpbmVzLmFwcGVuZCgi0J3QsNC/0LjR
gdCw0YLRjDogaHR0cHM6Ly90Lm1lLyVzIiAlIGxlYWRbInRlbGVncmFtX25pY2siXSkKICAgIGVs
aWYgbGVhZFsiY2hhbm5lbCJdID09ICJ0ZWxlZ3JhbSIgYW5kIGxlYWQuZ2V0KCJwaG9uZV9kaWdp
dHMiKToKICAgICAgICAjINCX0LDRj9Cy0LrQuCDRgdGC0LDRgNC+0LPQviDQvtCx0YDQsNC30YbQ
sDog0L3QuNC60LAg0L3QtSDQsdGL0LvQviwg0L7RgdGC0LDQstCw0LvRgdGPINGC0L7Qu9GM0LrQ
viDQvdC+0LzQtdGALgogICAgICAgIGxpbmVzLmFwcGVuZCgi0J3QsNC/0LjRgdCw0YLRjDogaHR0
cHM6Ly90Lm1lLyslcyIgJSBsZWFkWyJwaG9uZV9kaWdpdHMiXSkKCiAgICBsb3cgPSBsZWFkWyJw
cmljZSJdLmdldCgibG93IikKICAgIGhpZ2ggPSBsZWFkWyJwcmljZSJdLmdldCgiaGlnaCIpCiAg
ICBpZiBsb3cgYW5kIGhpZ2g6CiAgICAgICAgbGluZXMgKz0gWyIiLCAi0JLQuNC70LrQsCDQvdCw
INGN0LrRgNCw0L3QtTogPGI+JXMg4oCUICVzPC9iPiIgJSAoZm9ybWF0X21vbmV5KGxvdyksIGZv
cm1hdF9tb25leShoaWdoKSldCgogICAgaWYgbGVhZFsiYW5zd2VycyJdOgogICAgICAgIGxpbmVz
LmFwcGVuZCgiIikKICAgICAgICBmb3IgaW5kZXgsIGl0ZW0gaW4gZW51bWVyYXRlKGxlYWRbImFu
c3dlcnMiXSwgc3RhcnQ9MSk6CiAgICAgICAgICAgIGxpbmVzLmFwcGVuZCgKICAgICAgICAgICAg
ICAgICIlZC4gJXMg4oCUIDxiPiVzPC9iPiIKICAgICAgICAgICAgICAgICUgKGluZGV4LCBlc2Nh
cGVfaHRtbChpdGVtWyJxdWVzdGlvbiJdKSwgZXNjYXBlX2h0bWwoaXRlbVsiYW5zd2VyIl0pKQog
ICAgICAgICAgICApCgogICAgc291cmNlID0gbGVhZC5nZXQoInNvdXJjZSIpIG9yIHt9CiAgICBp
ZiBzb3VyY2U6CiAgICAgICAgbGluZXMuYXBwZW5kKCIiKQogICAgICAgIGNhbXBhaWduID0gIiAv
ICIuam9pbigKICAgICAgICAgICAgZXNjYXBlX2h0bWwoc291cmNlW2tleV0pCiAgICAgICAgICAg
IGZvciBrZXkgaW4gKCJ1dG1fc291cmNlIiwgInV0bV9tZWRpdW0iLCAidXRtX2NhbXBhaWduIikK
ICAgICAgICAgICAgaWYgc291cmNlLmdldChrZXkpCiAgICAgICAgKQogICAgICAgIGlmIGNhbXBh
aWduOgogICAgICAgICAgICBsaW5lcy5hcHBlbmQoItCa0LDQvNC/0LDQvdC40Y86ICVzIiAlIGNh
bXBhaWduKQogICAgICAgIGlmIHNvdXJjZS5nZXQoInV0bV90ZXJtIik6CiAgICAgICAgICAgIGxp
bmVzLmFwcGVuZCgi0JfQsNC/0YDQvtGBOiAlcyIgJSBlc2NhcGVfaHRtbChzb3VyY2VbInV0bV90
ZXJtIl0pKQogICAgICAgIGlmIHNvdXJjZS5nZXQoInJlZmVycmVyIik6CiAgICAgICAgICAgIGxp
bmVzLmFwcGVuZCgi0J/QtdGA0LXRhdC+0LQg0YE6ICVzIiAlIGVzY2FwZV9odG1sKHNvdXJjZVsi
cmVmZXJyZXIiXSkpCgogICAgbGluZXMgKz0gWyIiLCAiJXMg0JzQodCaIMK3IOKEliVzIiAlIChy
ZWNlaXZlZC5zdHJmdGltZSgiJWQuJW0uJVkgJUg6JU0iKSwgbGVhZFsiaWQiXSldCiAgICByZXR1
cm4gIlxuIi5qb2luKGxpbmVzKQoKCiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tICMKIyDQntCz0YDQsNC9
0LjRh9C10L3QuNC1INGH0LDRgdGC0L7RgtGLCiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tICMKCmNsYXNz
IFJhdGVMaW1pdGVyOgogICAgZGVmIF9faW5pdF9fKHNlbGYsIHBlcl9ob3VyKToKICAgICAgICBz
ZWxmLl9wZXJfaG91ciA9IG1heCgxLCBwZXJfaG91cikKICAgICAgICBzZWxmLl9oaXRzID0ge30K
ICAgICAgICBzZWxmLl9sb2NrID0gdGhyZWFkaW5nLkxvY2soKQoKICAgIGRlZiBhbGxvdyhzZWxm
LCBrZXkpOgogICAgICAgIG5vdyA9IHRpbWUubW9ub3RvbmljKCkKICAgICAgICBjdXRvZmYgPSBu
b3cgLSAzNjAwCiAgICAgICAgd2l0aCBzZWxmLl9sb2NrOgogICAgICAgICAgICBidWNrZXQgPSBb
dCBmb3IgdCBpbiBzZWxmLl9oaXRzLmdldChrZXksIFtdKSBpZiB0ID4gY3V0b2ZmXQogICAgICAg
ICAgICBpZiBsZW4oYnVja2V0KSA+PSBzZWxmLl9wZXJfaG91cjoKICAgICAgICAgICAgICAgIHNl
bGYuX2hpdHNba2V5XSA9IGJ1Y2tldAogICAgICAgICAgICAgICAgcmV0dXJuIEZhbHNlCiAgICAg
ICAgICAgIGJ1Y2tldC5hcHBlbmQobm93KQogICAgICAgICAgICBzZWxmLl9oaXRzW2tleV0gPSBi
dWNrZXQKICAgICAgICAgICAgaWYgbGVuKHNlbGYuX2hpdHMpID4gNTAwMDoKICAgICAgICAgICAg
ICAgIHNlbGYuX2hpdHMgPSB7CiAgICAgICAgICAgICAgICAgICAgazogdiBmb3IgaywgdiBpbiBz
ZWxmLl9oaXRzLml0ZW1zKCkgaWYgdiBhbmQgdlstMV0gPiBjdXRvZmYKICAgICAgICAgICAgICAg
IH0KICAgICAgICAgICAgcmV0dXJuIFRydWUKCgojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAjCiMg0KTQ
vtC90L7QstCw0Y8g0L/QtdGA0LXQvtGC0L/RgNCw0LLQutCwCiMgLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
ICMKCmNsYXNzIE91dGJveFdvcmtlcih0aHJlYWRpbmcuVGhyZWFkKToKICAgICIiItCg0LDQtyDQ
siDQvNC40L3Rg9GC0YMg0L/Ri9GC0LDQtdGC0YHRjyDQtNC+0YHRgtCw0LLQuNGC0Ywg0LLRgdGR
LCDRh9GC0L4g0LvQtdC20LjRgiDQsiBvdXRib3guIiIiCgogICAgZGFlbW9uID0gVHJ1ZQoKICAg
IGRlZiBfX2luaXRfXyhzZWxmLCBzdG9yZSwgdHJhbnNwb3J0LCBpbnRlcnZhbD02MC4wKToKICAg
ICAgICBzdXBlcigpLl9faW5pdF9fKG5hbWU9Im91dGJveCIpCiAgICAgICAgc2VsZi5fc3RvcmUg
PSBzdG9yZQogICAgICAgIHNlbGYuX3RyYW5zcG9ydCA9IHRyYW5zcG9ydAogICAgICAgIHNlbGYu
X2ludGVydmFsID0gaW50ZXJ2YWwKICAgICAgICBzZWxmLl93YWtlID0gdGhyZWFkaW5nLkV2ZW50
KCkKICAgICAgICBzZWxmLl9zdG9wID0gdGhyZWFkaW5nLkV2ZW50KCkKCiAgICBkZWYgcG9rZShz
ZWxmKToKICAgICAgICBzZWxmLl93YWtlLnNldCgpCgogICAgZGVmIHN0b3Aoc2VsZik6CiAgICAg
ICAgc2VsZi5fc3RvcC5zZXQoKQogICAgICAgIHNlbGYuX3dha2Uuc2V0KCkKCiAgICBkZWYgcnVu
KHNlbGYpOgogICAgICAgIHdoaWxlIG5vdCBzZWxmLl9zdG9wLmlzX3NldCgpOgogICAgICAgICAg
ICBzZWxmLl93YWtlLndhaXQoc2VsZi5faW50ZXJ2YWwpCiAgICAgICAgICAgIHNlbGYuX3dha2Uu
Y2xlYXIoKQogICAgICAgICAgICBpZiBzZWxmLl9zdG9wLmlzX3NldCgpOgogICAgICAgICAgICAg
ICAgcmV0dXJuCiAgICAgICAgICAgIHBlbmRpbmcgPSBzZWxmLl9zdG9yZS5wZW5kaW5nKCkKICAg
ICAgICAgICAgaWYgbm90IHBlbmRpbmc6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAg
ICAgICBsb2cuaW5mbygi0JIg0L7Rh9C10YDQtdC00LggJWQg0LfQsNGP0LLQvtC6LCDQv9GA0L7Q
sdGD0Y4g0L7RgtC/0YDQsNCy0LjRgtGMIiwgbGVuKHBlbmRpbmcpKQogICAgICAgICAgICBmb3Ig
bGVhZCBpbiBwZW5kaW5nOgogICAgICAgICAgICAgICAgb2ssIHJlYXNvbiA9IHNlbGYuX3RyYW5z
cG9ydC5zZW5kX21lc3NhZ2UocmVuZGVyX21lc3NhZ2UobGVhZCkpCiAgICAgICAgICAgICAgICBp
ZiBvazoKICAgICAgICAgICAgICAgICAgICBzZWxmLl9zdG9yZS5tYXJrX3NlbnQobGVhZFsiaWQi
XSkKICAgICAgICAgICAgICAgICAgICBsb2cuaW5mbygi0JfQsNGP0LLQutCwICVzINC00L7RgdGC
0LDQstC70LXQvdCwINC40Lcg0L7Rh9C10YDQtdC00LgiLCBsZWFkWyJpZCJdKQogICAgICAgICAg
ICAgICAgZWxzZToKICAgICAgICAgICAgICAgICAgICBsb2cud2FybmluZygi0JfQsNGP0LLQutCw
ICVzINCy0YHRkSDQtdGJ0ZEg0L3QtSDRg9GF0L7QtNC40YI6ICVzIiwgbGVhZFsiaWQiXSwgcmVh
c29uKQogICAgICAgICAgICAgICAgICAgIGJyZWFrICAjINGB0LzRi9GB0LvQsCDQtNC+0LvQsdC4
0YLRjCDQvtGB0YLQsNC70YzQvdGL0LUg0L3QtdGCIOKAlCDQv9GD0YLRjCDQstGB0ZEg0YDQsNCy
0L3QviDQt9Cw0LrRgNGL0YIKCgojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAjCiMgSFRUUAojIC0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLSAjCgpjbGFzcyBIYW5kbGVyKGh0dHAuc2VydmVyLkJhc2VIVFRQUmVxdWVz
dEhhbmRsZXIpOgogICAgc2VydmVyX3ZlcnNpb24gPSAiJXMvJXMiICUgKEFQUF9OQU1FLCBWRVJT
SU9OKQogICAgcHJvdG9jb2xfdmVyc2lvbiA9ICJIVFRQLzEuMSIKCiAgICAjIC0tLSDRgdC70YPQ
ttC10LHQvdC+0LUgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLSAjCgogICAgZGVmIGxvZ19tZXNzYWdlKHNlbGYsIGZtdCwgKmFyZ3MpOgog
ICAgICAgIGxvZy5pbmZvKCIlcyAlcyIsIHNlbGYuYWRkcmVzc19zdHJpbmcoKSwgZm10ICUgYXJn
cykKCiAgICBkZWYgX29yaWdpbl9oZWFkZXIoc2VsZik6CiAgICAgICAgb3JpZ2luID0gKHNlbGYu
aGVhZGVycy5nZXQoIk9yaWdpbiIpIG9yICIiKS5yc3RyaXAoIi8iKQogICAgICAgIGlmICIqIiBp
biBBTExPV0VEX09SSUdJTlM6CiAgICAgICAgICAgIHJldHVybiBvcmlnaW4gb3IgIioiCiAgICAg
ICAgaWYgb3JpZ2luIGluIEFMTE9XRURfT1JJR0lOUzoKICAgICAgICAgICAgcmV0dXJuIG9yaWdp
bgogICAgICAgIHJldHVybiAiIgoKICAgIGRlZiBfc2VuZChzZWxmLCBzdGF0dXMsIHBheWxvYWQp
OgogICAgICAgIGJvZHkgPSBqc29uLmR1bXBzKHBheWxvYWQsIGVuc3VyZV9hc2NpaT1GYWxzZSku
ZW5jb2RlKCJ1dGYtOCIpCiAgICAgICAgc2VsZi5zZW5kX3Jlc3BvbnNlKHN0YXR1cykKICAgICAg
ICBzZWxmLnNlbmRfaGVhZGVyKCJDb250ZW50LVR5cGUiLCAiYXBwbGljYXRpb24vanNvbjsgY2hh
cnNldD11dGYtOCIpCiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQ29udGVudC1MZW5ndGgiLCBz
dHIobGVuKGJvZHkpKSkKICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJDYWNoZS1Db250cm9sIiwg
Im5vLXN0b3JlIikKICAgICAgICBhbGxvdyA9IHNlbGYuX29yaWdpbl9oZWFkZXIoKQogICAgICAg
IGlmIGFsbG93OgogICAgICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJBY2Nlc3MtQ29udHJvbC1B
bGxvdy1PcmlnaW4iLCBhbGxvdykKICAgICAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiVmFyeSIs
ICJPcmlnaW4iKQogICAgICAgIHNlbGYuZW5kX2hlYWRlcnMoKQogICAgICAgIHNlbGYud2ZpbGUu
d3JpdGUoYm9keSkKCiAgICBkZWYgX2NsaWVudF9pcChzZWxmKToKICAgICAgICAiIiLQkNC00YDQ
tdGBLCDQutC+0YLQvtGA0L7QvNGDINC80L7QttC90L4g0LLQtdGA0LjRgtGMLgoKICAgICAgICBY
LUZvcndhcmRlZC1Gb3Ig0LHRgNCw0YLRjCDQn9CV0KDQktCr0Jwg0Y3Qu9C10LzQtdC90YLQvtC8
INC90LXQu9GM0LfRjzogbmdpbngg0YEKICAgICAgICAkcHJveHlfYWRkX3hfZm9yd2FyZGVkX2Zv
ciDQtNC+0L/QuNGB0YvQstCw0LXRgiDQvdCw0YHRgtC+0Y/RidC40Lkg0LDQtNGA0LXRgSDQsiDQ
mtCe0J3QldCmLCDQsCDQvdCw0YfQsNC70L4KICAgICAgICDRgdC/0LjRgdC60LAg0L/RgNC40YXQ
vtC00LjRgiDQvtGCINCx0YDQsNGD0LfQtdGA0LAg0Lgg0L/QvtC00LTQtdC70YvQstCw0LXRgtGB
0Y8g0L7QtNC90L7QuSDRgdGC0YDQvtC60L7QuSDigJQg0L7Qs9GA0LDQvdC40YfQtdC90LjQtQog
ICAgICAgINGH0LDRgdGC0L7RgtGLINC+0LHRhdC+0LTQuNC70L7RgdGMINCx0Ysg0YLRgNC40LLQ
uNCw0LvRjNC90L4uIFgtUmVhbC1JUCDRgdGC0LDQstC40YIg0YHQsNC8IG5naW54LCDQv9C+0Y3R
gtC+0LzRgwogICAgICAgINC+0L0g0LIg0L/RgNC40L7RgNC40YLQtdGC0LUsINCwINC40LcgWC1G
b3J3YXJkZWQtRm9yINCx0LXRgNGR0YLRgdGPINC/0L7RgdC70LXQtNC90LjQuSDRjdC70LXQvNC1
0L3Rgi4KICAgICAgICAiIiIKICAgICAgICBwZWVyID0gc2VsZi5jbGllbnRfYWRkcmVzc1swXQog
ICAgICAgICMg0JfQsNCz0L7Qu9C+0LLQutCw0Lwg0LLQtdGA0LjQvCwg0YLQvtC70YzQutC+INC1
0YHQu9C4INC30LDQv9GA0L7RgSDQv9GA0LjRiNGR0Lsg0L7RgiDQu9C+0LrQsNC70YzQvdC+0LPQ
viBuZ2lueC4KICAgICAgICAjINCY0L3QsNGH0LUg0LvRjtCx0L7QuSwg0LrRgtC+INC00L7RgdGC
0YPRh9C40YLRgdGPINC00L4g0L/QvtGA0YLQsCDQvdCw0L/RgNGP0LzRg9GOLCDQvdCw0LfQvtCy
0ZHRgtGB0Y8g0LrQtdC8INGD0LPQvtC00L3Qvi4KICAgICAgICBpZiBwZWVyIG5vdCBpbiBUUlVT
VEVEX1BST1hJRVM6CiAgICAgICAgICAgIHJldHVybiBwZWVyCiAgICAgICAgcmVhbCA9IChzZWxm
LmhlYWRlcnMuZ2V0KCJYLVJlYWwtSVAiKSBvciAiIikuc3RyaXAoKQogICAgICAgIGlmIHJlYWw6
CiAgICAgICAgICAgIHJldHVybiByZWFsWzo0NV0KICAgICAgICBmb3J3YXJkZWQgPSBzZWxmLmhl
YWRlcnMuZ2V0KCJYLUZvcndhcmRlZC1Gb3IiLCAiIikKICAgICAgICBpZiBmb3J3YXJkZWQ6CiAg
ICAgICAgICAgIHJldHVybiBmb3J3YXJkZWQuc3BsaXQoIiwiKVstMV0uc3RyaXAoKVs6NDVdCiAg
ICAgICAgcmV0dXJuIHBlZXIKCiAgICBkZWYgX2RyYWluKHNlbGYpOgogICAgICAgICIiItCU0L7R
h9C40YLQsNGC0Ywg0YLQtdC70L4g0LfQsNC/0YDQvtGB0LAuCgogICAgICAgINCf0YDQuCBIVFRQ
LzEuMSDRgSBrZWVwLWFsaXZlINC+0YLQstC10YIg0LHQtdC3INCy0YvRh9C40YLQsNC90L3QvtCz
0L4g0YLQtdC70LAg0L7RgdGC0LDQstC70Y/QtdGCINCx0LDQudGC0YsKICAgICAgICDQsiDRgdC+
0LrQtdGC0LUsINC4INC+0L3QuCDRgNCw0LfQsdC40YDQsNGO0YLRgdGPINC60LDQuiDQvdCw0YfQ
sNC70L4g0YHQu9C10LTRg9GO0YnQtdCz0L4g0LfQsNC/0YDQvtGB0LAg4oCUINGB0YvQv9C70Y7R
gtGB0Y8KICAgICAgICDQvdC10L7QsdGK0Y/RgdC90LjQvNGL0LUgNDAwLgogICAgICAgICIiIgog
ICAgICAgIHRyeToKICAgICAgICAgICAgbGVuZ3RoID0gaW50KHNlbGYuaGVhZGVycy5nZXQoIkNv
bnRlbnQtTGVuZ3RoIikgb3IgMCkKICAgICAgICBleGNlcHQgVmFsdWVFcnJvcjoKICAgICAgICAg
ICAgbGVuZ3RoID0gMAogICAgICAgIHJlbWFpbmluZyA9IG1pbihtYXgobGVuZ3RoLCAwKSwgTUFY
X0JPRFkgKiA0KQogICAgICAgIHdoaWxlIHJlbWFpbmluZyA+IDA6CiAgICAgICAgICAgIGNodW5r
ID0gc2VsZi5yZmlsZS5yZWFkKG1pbihyZW1haW5pbmcsIDY1NTM2KSkKICAgICAgICAgICAgaWYg
bm90IGNodW5rOgogICAgICAgICAgICAgICAgYnJlYWsKICAgICAgICAgICAgcmVtYWluaW5nIC09
IGxlbihjaHVuaykKCiAgICAjIC0tLSDQvNC10YLQvtC00YsgLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAjCgogICAgZGVmIGRvX09Q
VElPTlMoc2VsZik6ICAjIG5vcWE6IE44MDIKICAgICAgICBzZWxmLnNlbmRfcmVzcG9uc2UoMjA0
KQogICAgICAgIGFsbG93ID0gc2VsZi5fb3JpZ2luX2hlYWRlcigpCiAgICAgICAgaWYgYWxsb3c6
CiAgICAgICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkFjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdp
biIsIGFsbG93KQogICAgICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJWYXJ5IiwgIk9yaWdpbiIp
CiAgICAgICAgc2VsZi5zZW5kX2hlYWRlcigiQWNjZXNzLUNvbnRyb2wtQWxsb3ctTWV0aG9kcyIs
ICJQT1NULCBPUFRJT05TIikKICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJBY2Nlc3MtQ29udHJv
bC1BbGxvdy1IZWFkZXJzIiwgIkNvbnRlbnQtVHlwZSIpCiAgICAgICAgc2VsZi5zZW5kX2hlYWRl
cigiQWNjZXNzLUNvbnRyb2wtTWF4LUFnZSIsICI4NjQwMCIpCiAgICAgICAgc2VsZi5zZW5kX2hl
YWRlcigiQ29udGVudC1MZW5ndGgiLCAiMCIpCiAgICAgICAgc2VsZi5lbmRfaGVhZGVycygpCgog
ICAgZGVmIGRvX0dFVChzZWxmKTogICMgbm9xYTogTjgwMgogICAgICAgIGlmIHNlbGYucGF0aC5y
c3RyaXAoIi8iKSBpbiAoIi9hcGkvaGVhbHRoIiwgIi9oZWFsdGgiKToKICAgICAgICAgICAgc2Vs
Zi5fc2VuZCgKICAgICAgICAgICAgICAgIDIwMCwKICAgICAgICAgICAgICAgIHsKICAgICAgICAg
ICAgICAgICAgICAib2siOiBUcnVlLAogICAgICAgICAgICAgICAgICAgICJzZXJ2aWNlIjogQVBQ
X05BTUUsCiAgICAgICAgICAgICAgICAgICAgInZlcnNpb24iOiBWRVJTSU9OLAogICAgICAgICAg
ICAgICAgICAgICJ0ZWxlZ3JhbV9wYXRoIjogc2VsZi5zZXJ2ZXIudHJhbnNwb3J0Lndvcmtpbmdf
cGF0aCwKICAgICAgICAgICAgICAgICAgICAicGVuZGluZyI6IHNlbGYuc2VydmVyLnN0b3JlLnBl
bmRpbmdfY291bnQoKSwKICAgICAgICAgICAgICAgICAgICAiY29uZmlndXJlZCI6IGJvb2woQk9U
X1RPS0VOIGFuZCBDSEFUX0lEKSwKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICkKICAg
ICAgICAgICAgcmV0dXJuCiAgICAgICAgc2VsZi5fc2VuZCg0MDQsIHsib2siOiBGYWxzZSwgImVy
cm9yIjogIm5vdF9mb3VuZCJ9KQoKICAgIGRlZiBkb19QT1NUKHNlbGYpOiAgIyBub3FhOiBOODAy
CiAgICAgICAgaWYgc2VsZi5wYXRoLnJzdHJpcCgiLyIpIG5vdCBpbiAoIi9hcGkvbGVhZCIsICIv
bGVhZCIpOgogICAgICAgICAgICBzZWxmLl9kcmFpbigpCiAgICAgICAgICAgIHNlbGYuX3NlbmQo
NDA0LCB7Im9rIjogRmFsc2UsICJlcnJvciI6ICJub3RfZm91bmQifSkKICAgICAgICAgICAgcmV0
dXJuCgogICAgICAgIHRyeToKICAgICAgICAgICAgbGVuZ3RoID0gaW50KHNlbGYuaGVhZGVycy5n
ZXQoIkNvbnRlbnQtTGVuZ3RoIikgb3IgMCkKICAgICAgICBleGNlcHQgVmFsdWVFcnJvcjoKICAg
ICAgICAgICAgbGVuZ3RoID0gMAogICAgICAgIGlmIGxlbmd0aCA8PSAwIG9yIGxlbmd0aCA+IE1B
WF9CT0RZOgogICAgICAgICAgICBzZWxmLl9kcmFpbigpCiAgICAgICAgICAgIHNlbGYuX3NlbmQo
NDEzLCB7Im9rIjogRmFsc2UsICJlcnJvciI6ICJiYWRfc2l6ZSJ9KQogICAgICAgICAgICByZXR1
cm4KCiAgICAgICAgcmF3ID0gc2VsZi5yZmlsZS5yZWFkKGxlbmd0aCkKICAgICAgICB0cnk6CiAg
ICAgICAgICAgIHBheWxvYWQgPSBqc29uLmxvYWRzKHJhdy5kZWNvZGUoInV0Zi04IikpCiAgICAg
ICAgZXhjZXB0IChVbmljb2RlRGVjb2RlRXJyb3IsIFZhbHVlRXJyb3IpOgogICAgICAgICAgICBz
ZWxmLl9zZW5kKDQwMCwgeyJvayI6IEZhbHNlLCAiZXJyb3IiOiAiYmFkX2pzb24ifSkKICAgICAg
ICAgICAgcmV0dXJuCiAgICAgICAgaWYgbm90IGlzaW5zdGFuY2UocGF5bG9hZCwgZGljdCk6CiAg
ICAgICAgICAgIHNlbGYuX3NlbmQoNDAwLCB7Im9rIjogRmFsc2UsICJlcnJvciI6ICJiYWRfanNv
biJ9KQogICAgICAgICAgICByZXR1cm4KCiAgICAgICAgaXAgPSBzZWxmLl9jbGllbnRfaXAoKQog
ICAgICAgIGlmIG5vdCBzZWxmLnNlcnZlci5saW1pdGVyLmFsbG93KGlwKToKICAgICAgICAgICAg
bG9nLndhcm5pbmcoItCf0YDQtdCy0YvRiNC10L0g0LvQuNC80LjRgiDQt9Cw0Y/QstC+0Log0YEg
JXMiLCBpcCkKICAgICAgICAgICAgc2VsZi5fc2VuZCg0MjksIHsib2siOiBGYWxzZSwgImVycm9y
IjogInJhdGVfbGltaXRlZCJ9KQogICAgICAgICAgICByZXR1cm4KCiAgICAgICAgbGVhZCwgZXJy
b3JzID0gcGFyc2VfbGVhZChwYXlsb2FkLCBpcCwgc2VsZi5oZWFkZXJzLmdldCgiVXNlci1BZ2Vu
dCIsICIiKSkKICAgICAgICBpZiBlcnJvcnM6CiAgICAgICAgICAgIGlmIGVycm9ycy5nZXQoImNv
bXBhbnkiKToKICAgICAgICAgICAgICAgICMg0JvQvtCy0YPRiNC60LAg0YHRgNCw0LHQvtGC0LDQ
u9CwOiDQsdC+0YLRgyDQvtGC0LLQtdGH0LDQtdC8INC60LDQuiDQsdGD0LTRgtC+INCy0YHRkSDR
hdC+0YDQvtGI0L4uCiAgICAgICAgICAgICAgICBsb2cud2FybmluZygi0JvQvtCy0YPRiNC60LAg
0YHRgNCw0LHQvtGC0LDQu9CwLCDQt9Cw0Y/QstC60LAg0YEgJXMg0L7RgtCx0YDQvtGI0LXQvdCw
IiwgaXApCiAgICAgICAgICAgICAgICBzZWxmLl9zZW5kKDIwMCwgeyJvayI6IFRydWUsICJpZCI6
ICItIn0pCiAgICAgICAgICAgICAgICByZXR1cm4KICAgICAgICAgICAgc2VsZi5fc2VuZCg0MjIs
IHsib2siOiBGYWxzZSwgImVycm9yIjogImludmFsaWQiLCAiZmllbGRzIjogZXJyb3JzfSkKICAg
ICAgICAgICAgcmV0dXJuCgogICAgICAgICMg0KHQvdCw0YfQsNC70LAg0L3QsCDQtNC40YHQuiDi
gJQg0L/QvtGC0L7QvCDQstGB0ZEg0L7RgdGC0LDQu9GM0L3QvtC1LiDQl9Cw0Y/QstC60LAg0L3Q
tSDRgtC10YDRj9C10YLRgdGPLgogICAgICAgIHRyeToKICAgICAgICAgICAgc2VsZi5zZXJ2ZXIu
c3RvcmUuYXBwZW5kKGxlYWQpCiAgICAgICAgICAgIHNlbGYuc2VydmVyLnN0b3JlLmVucXVldWUo
bGVhZCkKICAgICAgICBleGNlcHQgT1NFcnJvciBhcyBleGM6CiAgICAgICAgICAgIGxvZy5leGNl
cHRpb24oItCd0LUg0YPQtNCw0LvQvtGB0Ywg0YHQvtGF0YDQsNC90LjRgtGMINC30LDRj9Cy0LrR
gzogJXMiLCBleGMpCiAgICAgICAgICAgIHNlbGYuX3NlbmQoNTAwLCB7Im9rIjogRmFsc2UsICJl
cnJvciI6ICJzdG9yYWdlIn0pCiAgICAgICAgICAgIHJldHVybgoKICAgICAgICAjINCe0YLQstC1
0YfQsNC10Lwg0YHRgNCw0LfRgy4g0J7RgtC/0YDQsNCy0LrRgyDQsiBUZWxlZ3JhbSDQtNC10LvQ
sNC10YIg0YTQvtC90L7QstGL0Lkg0L/QvtGC0L7Qujog0LXRgdC70Lgg0L7QsdCwCiAgICAgICAg
IyDQv9GD0YLQuCDQtNC+IGFwaS50ZWxlZ3JhbS5vcmcg0LvQtdC20LDRgiwg0YHQuNC90YXRgNC+
0L3QvdCw0Y8g0L7RgtC/0YDQsNCy0LrQsCDQtNC10YDQttCw0LvQsCDQsdGLCiAgICAgICAgIyDQ
v9C+0YHQtdGC0LjRgtC10LvRjyDQtNC+INC00LLRg9GFINGC0LDQudC80LDRg9GC0L7QsiDQv9C+
0LTRgNGP0LQsINCwIG5naW54INGD0YHQv9C10Lsg0LHRiyDQvtGC0LLQsNC70LjRgtGM0YHRjwog
ICAgICAgICMg0L/QviBwcm94eV9yZWFkX3RpbWVvdXQuINCX0LDRj9Cy0LrQsCDRg9C20LUg0L3Q
sCDQtNC40YHQutC1LCDRgtC10YDRj9GC0Ywg0L3QtdGH0LXQs9C+LgogICAgICAgIGxvZy5pbmZv
KCLQl9Cw0Y/QstC60LAgJXMg0L/RgNC40L3Rj9GC0LAiLCBsZWFkWyJpZCJdKQogICAgICAgIHNl
bGYuX3NlbmQoMjAwLCB7Im9rIjogVHJ1ZSwgImlkIjogbGVhZFsiaWQiXX0pCiAgICAgICAgc2Vs
Zi5zZXJ2ZXIub3V0Ym94LnBva2UoKQoKCmNsYXNzIFNlcnZlcihzb2NrZXRzZXJ2ZXIuVGhyZWFk
aW5nTWl4SW4sIGh0dHAuc2VydmVyLkhUVFBTZXJ2ZXIpOgogICAgZGFlbW9uX3RocmVhZHMgPSBU
cnVlCiAgICBhbGxvd19yZXVzZV9hZGRyZXNzID0gVHJ1ZQogICAgYWRkcmVzc19mYW1pbHkgPSBz
b2NrZXQuQUZfSU5FVDYgaWYgIjoiIGluIEJJTkQgZWxzZSBzb2NrZXQuQUZfSU5FVAoKCmRlZiBt
YWluKCk6CiAgICBpZiBub3QgQk9UX1RPS0VOIG9yIG5vdCBDSEFUX0lEOgogICAgICAgIGxvZy53
YXJuaW5nKAogICAgICAgICAgICAiQVVSRUFfS1ZJWl9CT1RfVE9LRU4g0LjQu9C4IEFVUkVBX0tW
SVpfQ0hBVF9JRCDQvdC1INC30LDQtNCw0L3Riy4gIgogICAgICAgICAgICAi0KHQtdGA0LLQuNGB
INC/0L7QtNC90LjQvNC10YLRgdGPINC4INCx0YPQtNC10YIg0YHQvtGF0YDQsNC90Y/RgtGMINC3
0LDRj9Cy0LrQuCwg0L3QviDQvtGC0L/RgNCw0LLQu9GP0YLRjCDQuNGFINC90LUg0YHQvNC+0LbQ
tdGCLiIKICAgICAgICApCgogICAgc3RvcmUgPSBMZWFkU3RvcmUoREFUQV9ESVIpCiAgICB0cmFu
c3BvcnQgPSBUZWxlZ3JhbVRyYW5zcG9ydChCT1RfVE9LRU4sIElQX0ZBTUlMWV9QUkVGKQogICAg
b3V0Ym94ID0gT3V0Ym94V29ya2VyKHN0b3JlLCB0cmFuc3BvcnQpCgogICAgIyDQodC+0LrQtdGC
INC/0L7QtNC90LjQvNCw0LXRgtGB0Y8g0J/QldCg0JLQq9CcINC00LXQu9C+0LwuINCf0YDQvtCx
0LAg0L7QsdC+0LjRhSDQv9GD0YLQtdC5INC00L4gVGVsZWdyYW0g0LfQsNC90LjQvNCw0LXRggog
ICAgIyDRgdC10LrRg9C90LTRizsg0LXRgdC70Lgg0LTQtdC70LDRgtGMINC10ZEg0LTQviBiaW5k
LCBzeXN0ZW1kINC/0YDQuCBUeXBlPXNpbXBsZSDRg9C20LUg0YHRh9C40YLQsNC10YIKICAgICMg
0YHQu9GD0LbQsdGDINC30LDQv9GD0YnQtdC90L3QvtC5LCDQsCBuZ2lueCDQsiDRjdGC0L4g0L7Q
utC90L4g0L7RgtC00LDRkdGCIDUwMi4KICAgIHNlcnZlciA9IFNlcnZlcigoQklORCwgUE9SVCks
IEhhbmRsZXIpCiAgICBzZXJ2ZXIuc3RvcmUgPSBzdG9yZQogICAgc2VydmVyLnRyYW5zcG9ydCA9
IHRyYW5zcG9ydAogICAgc2VydmVyLm91dGJveCA9IG91dGJveAogICAgc2VydmVyLmxpbWl0ZXIg
PSBSYXRlTGltaXRlcihSQVRFX1BFUl9IT1VSKQogICAgbG9nLmluZm8oIiVzICVzINGB0LvRg9GI
0LDQtdGCICVzOiVzIiwgQVBQX05BTUUsIFZFUlNJT04sIEJJTkQsIFBPUlQpCgogICAgZGVmIHdh
cm1fdXAoKToKICAgICAgICB0cmFuc3BvcnQucHJvYmUoKQogICAgICAgIG91dGJveC5wb2tlKCkK
CiAgICBvdXRib3guc3RhcnQoKQogICAgdGhyZWFkaW5nLlRocmVhZCh0YXJnZXQ9d2FybV91cCwg
bmFtZT0icHJvYmUiLCBkYWVtb249VHJ1ZSkuc3RhcnQoKQogICAgdHJ5OgogICAgICAgIHNlcnZl
ci5zZXJ2ZV9mb3JldmVyKCkKICAgIGV4Y2VwdCBLZXlib2FyZEludGVycnVwdDoKICAgICAgICBw
YXNzCiAgICBmaW5hbGx5OgogICAgICAgIG91dGJveC5zdG9wKCkKICAgICAgICBzZXJ2ZXIuc2Vy
dmVyX2Nsb3NlKCkKICAgICAgICBsb2cuaW5mbygi0J7RgdGC0LDQvdC+0LLQu9C10L0iKQoKCmlm
IF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBtYWluKCkK
AUREA_KVIZ_APP_B64
python3 -m py_compile "$TMP_APP" || die "код службы не компилируется — установка прервана"
if [ -f "$APP_DIR/app.py" ] && cmp -s "$TMP_APP" "$APP_DIR/app.py"; then
  ok "app.py не изменился"
else
  install -m 0644 -o root -g root "$TMP_APP" "$APP_DIR/app.py"
  CHANGED=1
  ok "app.py установлен"
fi
rm -f "$TMP_APP"
find "$APP_DIR" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

# ===========================================================================
step "5. Файл настроек с токеном"
# ===========================================================================
# Существующие значения не переписываются: владелец мог поправить их руками.
# Дописываются только недостающие ключи.
if [ ! -f "$ENV_FILE" ]; then
  umask 077
  printf '%s\n' \
    "# AUREA · настройки приёмника заявок. Права 600, читает systemd под root." \
    "# Впишите токен бота и id получателя, потом: systemctl restart $SVC" \
    "" > "$ENV_FILE"
  warn "создан пустой $ENV_FILE"
else
  ok "$ENV_FILE уже есть — существующие значения не трогаю"
fi

add_key() {
  grep -q "^$1=" "$ENV_FILE" || { printf '%s=%s\n' "$1" "$2" >> "$ENV_FILE"; ok "дописан $1"; }
}
add_key AUREA_KVIZ_BOT_TOKEN ""
add_key AUREA_KVIZ_CHAT_ID ""
add_key AUREA_KVIZ_BIND "127.0.0.1"
add_key AUREA_KVIZ_PORT "$PORT"
add_key AUREA_KVIZ_DATA_DIR "$DATA_DIR"
add_key AUREA_KVIZ_ALLOWED_ORIGINS "$ORIGINS"
add_key AUREA_KVIZ_IP_FAMILY "auto"
add_key AUREA_KVIZ_RATE_PER_HOUR "8"
chmod 0600 "$ENV_FILE"; chown root:root "$ENV_FILE"

CUR_ORIGINS=$(sed -n 's/^AUREA_KVIZ_ALLOWED_ORIGINS=//p' "$ENV_FILE" | head -1)
if [ "$CUR_ORIGINS" != "$ORIGINS" ]; then
  warn "в настройках AUREA_KVIZ_ALLOWED_ORIGINS = $CUR_ORIGINS"
  warn "а ожидался $ORIGINS — если адрес сайта сменился, поправьте вручную"
fi

# ===========================================================================
step "6. Служба systemd"
# ===========================================================================
NEW_UNIT=$(mktemp)
base64 -d > "$NEW_UNIT" <<'AUREA_KVIZ_UNIT_B64'
IyDQldC00LjQvdGB0YLQstC10L3QvdC+0LUg0L7Qv9C40YHQsNC90LjQtSDRgdC70YPQttCx0Ysu
INCSINGD0YHRgtCw0L3QvtCy0YnQuNC6INC+0L3QviDQv9C+0L/QsNC00LDQtdGCINGG0LXQu9C4
0LrQvtC8CiMgKHNjcmlwdHMvYnVpbGQtaW5zdGFsbGVyLnNoKSwg0L/QvtGN0YLQvtC80YMg0YDQ
sNC30L7QudGC0LjRgdGMINC60L7Qv9C40Y/QvCDQvdC10L7RgtC60YPQtNCwLgpbVW5pdF0KRGVz
Y3JpcHRpb249QVVSRUEgwrcg0L/RgNC40ZHQvNC90LjQuiDQt9Cw0Y/QstC+0Log0YEg0LrQstC4
0Lct0LvQtdC90LTQuNC90LPQsApEb2N1bWVudGF0aW9uPWh0dHBzOi8vZ2l0aHViLmNvbS9raXJp
bGwtZGVzaWduMzY3L2t2aXoKQWZ0ZXI9bmV0d29yay1vbmxpbmUudGFyZ2V0CldhbnRzPW5ldHdv
cmstb25saW5lLnRhcmdldAojINCY0L3QsNGH0LUg0YHQtdGA0LjRjyDQsdGL0YHRgtGA0YvRhSDQ
v9Cw0LTQtdC90LjQuSDQt9Cw0LPQvtC90Y/QtdGCINGO0L3QuNGCINCyIGZhaWxlZCDQvdCw0YHQ
vtCy0YHQtdC8LAojINC4INGB0LXRgNCy0LjRgSDQvdC1INC/0L7QtNC90LjQvNC10YLRgdGPINC0
0LDQttC1INC/0L7RgdC70LUg0YLQvtCz0L4sINC60LDQuiDQv9GA0LjRh9C40L3QsCDRg9GB0YLR
gNCw0L3QtdC90LAuClN0YXJ0TGltaXRJbnRlcnZhbFNlYz0wCgpbU2VydmljZV0KVHlwZT1zaW1w
bGUKVXNlcj1hdXJlYWt2aXoKR3JvdXA9YXVyZWFrdml6CldvcmtpbmdEaXJlY3Rvcnk9L29wdC9h
dXJlYS1rdml6CkV4ZWNTdGFydD0vdXNyL2Jpbi9lbnYgcHl0aG9uMyAvb3B0L2F1cmVhLWt2aXov
YXBwLnB5CkVudmlyb25tZW50RmlsZT0vZXRjL2F1cmVhLWt2aXova3Zpei5lbnYKUmVzdGFydD1h
bHdheXMKUmVzdGFydFNlYz0zClN5c2xvZ0lkZW50aWZpZXI9YXVyZWEta3ZpegoKIyDQmNC30L7Q
u9GP0YbQuNGPOiDRgdC70YPQttCx0LUg0L3Rg9C20LXQvSDRgtC+0LvRjNC60L4g0YHQstC+0Lkg
0LrQsNGC0LDQu9C+0LMg0LTQsNC90L3Ri9GFINC4INGB0LXRgtGMLgpOb05ld1ByaXZpbGVnZXM9
dHJ1ZQpQcml2YXRlVG1wPXRydWUKUHJpdmF0ZURldmljZXM9dHJ1ZQpQcm90ZWN0U3lzdGVtPXN0
cmljdApQcm90ZWN0SG9tZT10cnVlClByb3RlY3RLZXJuZWxUdW5hYmxlcz10cnVlClByb3RlY3RL
ZXJuZWxNb2R1bGVzPXRydWUKUHJvdGVjdENvbnRyb2xHcm91cHM9dHJ1ZQpQcm90ZWN0SG9zdG5h
bWU9dHJ1ZQpQcm90ZWN0Q2xvY2s9dHJ1ZQpSZXN0cmljdFNVSURTR0lEPXRydWUKUmVzdHJpY3RS
ZWFsdGltZT10cnVlClJlc3RyaWN0TmFtZXNwYWNlcz10cnVlCkxvY2tQZXJzb25hbGl0eT10cnVl
Ck1lbW9yeURlbnlXcml0ZUV4ZWN1dGU9dHJ1ZQpSZW1vdmVJUEM9dHJ1ZQpSZWFkV3JpdGVQYXRo
cz0vdmFyL2xpYi9hdXJlYS1rdml6CiMgQUZfVU5JWCDQvtCx0Y/Qt9Cw0YLQtdC70LXQvTog0LHQ
tdC3INC90LXQs9C+INC70L7QvNCw0LXRgtGB0Y8g0YDQtdC30L7Qu9Cy0LXRgCwg0LAg0LLRi9Cz
0LvRj9C00LjRgiDRjdGC0L4g0LrQsNC6IMKr0L3QtdGCINGB0LXRgtC4wrsuClJlc3RyaWN0QWRk
cmVzc0ZhbWlsaWVzPUFGX0lORVQgQUZfSU5FVDYgQUZfVU5JWApDYXBhYmlsaXR5Qm91bmRpbmdT
ZXQ9CkFtYmllbnRDYXBhYmlsaXRpZXM9CgpbSW5zdGFsbF0KV2FudGVkQnk9bXVsdGktdXNlci50
YXJnZXQK
AUREA_KVIZ_UNIT_B64
if [ -f "$UNIT" ] && cmp -s "$NEW_UNIT" "$UNIT"; then
  ok "описание службы не изменилось"
else
  install -m 0644 "$NEW_UNIT" "$UNIT"
  CHANGED=1
  ok "описание службы записано в $UNIT"
fi
rm -f "$NEW_UNIT"

systemctl daemon-reload
systemctl enable "$SVC" >/dev/null 2>&1 || true
# Перезапуск только по делу: лишний рестарт роняет соединения на ровном месте.
if [ "$CHANGED" = "1" ] || ! systemctl is-active --quiet "$SVC"; then
  systemctl restart "$SVC"
  sleep 2
  ok "служба перезапущена"
else
  ok "служба уже работает и не менялась — не трогаю"
fi

if ! systemctl is-active --quiet "$SVC"; then
  warn "служба не поднялась, последние строки журнала:"
  journalctl -u "$SVC" -n 25 --no-pager | sed 's/^/      /'
  die "разберитесь с журналом и запустите скрипт заново"
fi
ok "служба $SVC работает"

# ===========================================================================
step "7. Отдельный конфиг nginx"
# ===========================================================================
NGINX_DONE=0
SITE=""
if have nginx; then
  if [ -d /etc/nginx/sites-available ] && nginx -T 2>/dev/null | grep -q 'sites-enabled'; then
    SITE=/etc/nginx/sites-available/$SVC.conf
    LINK=/etc/nginx/sites-enabled/$SVC.conf
  else
    SITE=/etc/nginx/conf.d/$SVC.conf
    LINK=""
  fi

  if [ -f "$SITE" ] && ! head -3 "$SITE" | grep -q 'managed-by: aurea-kviz'; then
    die "файл $SITE существует и создан не нами. Ничего не меняю."
  fi

  # Точное совпадение server_name, а не grep -w: точки в шаблоне это «любой
  # символ», и sub.kviz.aureadesign.ru давал бы ложный конфликт.
  CONFLICT=$(nginx -T 2>/dev/null \
    | grep -E '^[[:space:]]*server_name' \
    | tr -s ' ' | sed 's/^ *server_name //; s/;$//' \
    | tr ' ' '\n' \
    | grep -Fxq "$DOMAIN" && echo yes || echo no)
  OURS_ALREADY=$([ -f "$SITE" ] && echo yes || echo no)

  if [ "$CONFLICT" = "yes" ] && [ "$OURS_ALREADY" = "no" ]; then
    warn "домен $DOMAIN уже объявлен в чужом конфиге nginx."
    warn "Конфиг пропущен, чтобы ничего не сломать. Настройте проксирование сами:"
    warn "  proxy_pass http://127.0.0.1:$PORT;"
  else
    # nginx до 1.25.1 не понимает отдельную директиву «http2 on».
    NGINX_VER=$(nginx -v 2>&1 | sed 's/.*\///; s/[^0-9.].*//')
    if printf '%s\n1.25.1\n' "$NGINX_VER" | sort -V | head -1 | grep -qx "1.25.1"; then
      HTTP2_LINE="    http2 on;"
      SSL_LISTEN_4="    listen 443 ssl;"
      SSL_LISTEN_6="    listen [::]:443 ssl;"
    else
      HTTP2_LINE=""
      SSL_LISTEN_4="    listen 443 ssl http2;"
      SSL_LISTEN_6="    listen [::]:443 ssl http2;"
    fi
    ok "nginx $NGINX_VER — директива http2 подобрана под версию"

    HAS_CERT=no
    [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ] && HAS_CERT=yes

    # Конфиг генерируется целиком, а не дописывается: дописывание ломается,
    # если файл когда-нибудь правили руками.
    write_site() {
      cat <<SITEEOF
$MARKER — файл принадлежит только квиз-лендингу.
# Другие сайты этого сервера он не затрагивает.
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    location ^~ /.well-known/acme-challenge/ {
        root $ACME_DIR;
        default_type "text/plain";
    }

$(if [ "$1" = "yes" ]; then
cat <<REDIR
    location / {
        return 301 https://\$host\$request_uri;
    }
REDIR
else
cat <<PROXY
    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
        client_max_body_size 32k;
    }
PROXY
fi)
}
$(if [ "$1" = "yes" ]; then
cat <<TLSEOF

server {
$SSL_LISTEN_4
$SSL_LISTEN_6
$HTTP2_LINE
    server_name $DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:AureaKviz:1m;

    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
        client_max_body_size 32k;
    }
}
TLSEOF
fi)
SITEEOF
    }

    apply_site() {
      local want_tls="$1" tmp backup
      tmp=$(mktemp)
      write_site "$want_tls" > "$tmp"
      if [ -f "$SITE" ] && cmp -s "$tmp" "$SITE"; then
        rm -f "$tmp"; ok "конфиг nginx не изменился"; NGINX_DONE=1; return 0
      fi
      backup=""
      if [ -f "$SITE" ]; then backup=$(mktemp); cp "$SITE" "$backup"; fi
      install -m 0644 "$tmp" "$SITE"; rm -f "$tmp"
      [ -n "$LINK" ] && ln -sfn "$SITE" "$LINK"
      if nginx -t >/dev/null 2>&1; then
        systemctl reload nginx && ok "nginx перечитал конфигурацию"
        [ -n "$backup" ] && rm -f "$backup"
        NGINX_DONE=1
        return 0
      fi
      warn "nginx -t ругается, откатываю только свой файл:"
      nginx -t 2>&1 | sed 's/^/      /'
      if [ -n "$backup" ]; then install -m 0644 "$backup" "$SITE"; rm -f "$backup";
      else rm -f "$SITE"; [ -n "$LINK" ] && rm -f "$LINK"; fi
      nginx -t >/dev/null 2>&1 && systemctl reload nginx
      return 1
    }

    apply_site "$HAS_CERT" || warn "конфиг nginx не применён"
  fi

  if have getenforce && [ "$(getenforce 2>/dev/null)" = "Enforcing" ]; then
    if [ "$ALLOW_SELINUX" = "1" ]; then
      setsebool -P httpd_can_network_connect 1 && ok "SELinux: разрешил nginx ходить по сети"
    else
      warn "SELinux в режиме Enforcing. Чтобы nginx смог проксировать, нужна команда:"
      warn "  setsebool -P httpd_can_network_connect 1"
      warn "Она действует на ВСЕ httpd-процессы сервера, поэтому сама не выполняется."
      warn "Разрешить: перезапустите скрипт с AUREA_KVIZ_ALLOW_SELINUX=1"
    fi
  fi
else
  warn "nginx не найден — проксирование настройте сами на http://127.0.0.1:$PORT"
fi

# ===========================================================================
step "8. Сертификат Let's Encrypt"
# ===========================================================================
CERT_DIR="/etc/letsencrypt/live/$DOMAIN"
if [ "$SKIP_TLS" = "1" ]; then
  warn "выпуск сертификата пропущен по AUREA_KVIZ_SKIP_TLS=1"
elif [ "$NGINX_DONE" != "1" ]; then
  warn "nginx не настроен — сертификат пропущен"
elif [ -f "$CERT_DIR/fullchain.pem" ] \
     && openssl x509 -checkend 2592000 -noout -in "$CERT_DIR/fullchain.pem" >/dev/null 2>&1; then
  # Повторные обращения к Let's Encrypt быстро упираются в лимит: пять
  # одинаковых сертификатов в неделю — и домен закрыт на неделю.
  ok "сертификат для $DOMAIN есть и действует ещё больше месяца"
else
  if ! have certbot; then
    if [ "$ALLOW_APT" = "1" ]; then
      if have apt-get; then
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq certbot >/dev/null 2>&1 || true
      elif have dnf; then dnf install -y -q certbot >/dev/null 2>&1 || true
      elif have yum; then yum install -y -q certbot >/dev/null 2>&1 || true
      fi
    else
      warn "certbot не установлен. Ставить пакеты на чужой сервер сам не буду."
      warn "Поставьте вручную:  apt-get install -y certbot"
      warn "или перезапустите скрипт с AUREA_KVIZ_ALLOW_APT=1"
    fi
  fi
  if have certbot; then
    RESOLVED=$(getent ahosts "$DOMAIN" 2>/dev/null | head -1 | awk '{print $1}')
    if [ -z "$RESOLVED" ]; then
      warn "$DOMAIN не резолвится. Заведите записи A и AAAA и запустите скрипт заново."
    else
      ok "$DOMAIN резолвится в $RESOLVED"
      CB="certonly --webroot -w $ACME_DIR -d $DOMAIN --agree-tos --non-interactive --keep-until-expiring"
      if [ -n "$LE_EMAIL" ]; then CB="$CB -m $LE_EMAIL"; else CB="$CB --register-unsafely-without-email"; fi
      if certbot $CB; then
        ok "сертификат выпущен"
        apply_site yes || warn "не удалось включить https"
      else
        warn "certbot не справился — сайт останется на http"
      fi
    fi
  fi
fi

# ===========================================================================
step "9. Проверка"
# ===========================================================================
HEALTH=$(curl -s --max-time 5 "http://127.0.0.1:$PORT/api/health" || true)
if [ -n "$HEALTH" ]; then ok "служба отвечает: $HEALTH"; else warn "служба не ответила на /api/health"; fi

echo "  Путь до Telegram по журналу:"
journalctl -u "$SVC" -n 60 --no-pager 2>/dev/null | grep -i 'telegram' | tail -4 | sed 's/^/      /' || true

if grep -q '^AUREA_KVIZ_BOT_TOKEN=$' "$ENV_FILE" 2>/dev/null; then
  warn "токен ещё не заполнен — заявки будут копиться в очереди"
fi

echo
printf '%sГотово.%s\n\n' "$BLD" "$RST"
cat <<SUMEOF
  Служба:     systemctl status $SVC
  Журнал:     journalctl -u $SVC -f
  Настройки:  $ENV_FILE   (права 600)
  Данные:     $DATA_DIR/leads.jsonl   — все заявки
              $DATA_DIR/outbox/       — не ушедшие в Telegram
  Локально:   http://127.0.0.1:$PORT/api/health
  Снаружи:    https://$DOMAIN/api/lead

  Дальше:
    1. Впишите токен и chat_id:    nano $ENV_FILE
    2. Перезапустите:              systemctl restart $SVC
    3. Проверьте путь до Telegram: journalctl -u $SVC -n 30 --no-pager | grep -i telegram
SUMEOF
