#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# AUREA · установка приёмника заявок с квиз-лендинга.
#
# Запуск под root:   bash install.sh
# Повторный запуск безопасен.
#
# Что делает:
#   1. осматривает сервер и печатает, что на нём стоит;
#   2. проверяет, не займёт ли он чужое (порт, имя юнита, конфиг nginx, домен);
#   3. ставит службу в СВОЙ каталог, под СВОИМ пользователем, СВОЕЙ службой,
#      СО СВОИМ отдельным файлом конфигурации nginx.
#
# Чего НЕ делает:
#   * не трогает существующие сайты, конфиги nginx, юниты systemd и их данные;
#   * не переписывает уже существующий файл настроек — только дописывает
#     недостающие строки;
#   * не ставит пакеты и не меняет политику SELinux без явного разрешения;
#   * не печатает токен ни в лог, ни на экран.
#
# Настройки через переменные окружения (все необязательны):
#   AUREA_KVIZ_DOMAIN     домен приёма заявок  (по умолчанию kviz.aureadesign.ru)
#   AUREA_KVIZ_ORIGINS    разрешённые Origin через запятую
#   AUREA_KVIZ_PORT       локальный порт       (по умолчанию 8787)
#   AUREA_KVIZ_EMAIL      почта для Let's Encrypt
#   AUREA_KVIZ_SKIP_TLS=1 не выпускать сертификат
#   AUREA_KVIZ_ALLOW_APT=1 разрешить установку certbot через пакетный менеджер
#   AUREA_KVIZ_ALLOW_SELINUX=1 разрешить setsebool httpd_can_network_connect
# ---------------------------------------------------------------------------
set -euo pipefail

SVC=aurea-kviz
SVC_USER=aureakviz
APP_DIR=/opt/$SVC
CFG_DIR=/etc/$SVC
DATA_DIR=/var/lib/$SVC
ACME_DIR=/var/www/$SVC-acme
UNIT=/etc/systemd/system/$SVC.service
ENV_FILE=$CFG_DIR/kviz.env
MARKER="# managed-by: aurea-kviz installer"

DOMAIN="${AUREA_KVIZ_DOMAIN:-kviz.aureadesign.ru}"
ORIGINS="${AUREA_KVIZ_ORIGINS:-https://kirill-design367.github.io}"
LE_EMAIL="${AUREA_KVIZ_EMAIL:-}"
SKIP_TLS="${AUREA_KVIZ_SKIP_TLS:-0}"
ALLOW_APT="${AUREA_KVIZ_ALLOW_APT:-0}"
ALLOW_SELINUX="${AUREA_KVIZ_ALLOW_SELINUX:-0}"

RED=$'\033[31m'; GRN=$'\033[32m'; YEL=$'\033[33m'; BLD=$'\033[1m'; RST=$'\033[0m'
step() { printf '\n%s── %s ──────────────────────────%s\n' "$BLD" "$1" "$RST"; }
ok()   { printf '  %s✓%s %s\n' "$GRN" "$RST" "$1"; }
warn() { printf '  %s!%s %s\n' "$YEL" "$RST" "$1"; }
die()  { printf '\n%sОстановлено:%s %s\n' "$RED" "$RST" "$1" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

[ "$(id -u)" = "0" ] || die "нужен root. Запустите: sudo bash $0"
have systemctl || die "нет systemd — этот установщик рассчитан на systemd"

# Порт: сначала то, что уже записано в настройках, потом переменная, потом
# значение по умолчанию. Иначе автоподбор при каждом запуске давал бы новый
# порт, и nginx проксировал бы в пустоту.
PORT_FROM_ENV=""
[ -f "$ENV_FILE" ] && PORT_FROM_ENV=$(sed -n 's/^AUREA_KVIZ_PORT=\([0-9]\+\).*/\1/p' "$ENV_FILE" | head -1)
PORT="${PORT_FROM_ENV:-${AUREA_KVIZ_PORT:-8787}}"

# ===========================================================================
step "1. Что стоит на сервере"
# ===========================================================================
[ -r /etc/os-release ] && . /etc/os-release || true
echo "  ОС:            ${PRETTY_NAME:-неизвестно}"
echo "  Ядро:          $(uname -r)"
echo "  Python:        $(python3 -V 2>&1 || echo 'НЕТ')"
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 7) else 1)' 2>/dev/null \
  || die "нужен Python 3.7 или новее"

echo "  Веб-серверы:"
FOUND_WEB=0
for s in nginx apache2 httpd caddy angie; do
  if have "$s"; then echo "                 $s  ($("$s" -v 2>&1 | head -1))"; FOUND_WEB=1; fi
done
[ "$FOUND_WEB" = "1" ] || echo "                 не найдены"

echo "  Панели управления хостингом:"
PANEL=""
for p in /usr/local/mgr5:ISPmanager /usr/local/fastpanel2:FASTPANEL \
         /opt/psa:Plesk /usr/local/hestia:HestiaCP /usr/local/cpanel:cPanel \
         /usr/local/vesta:VestaCP /opt/cloudpanel:CloudPanel; do
  if [ -d "${p%%:*}" ]; then PANEL="${p##*:}"; echo "                 НАЙДЕНА: $PANEL"; fi
done
[ -n "$PANEL" ] || echo "                 не найдены"

echo "  Работающие службы (без системных):"
systemctl list-units --type=service --state=running --no-legend --no-pager 2>/dev/null \
  | awk '{print $1}' \
  | grep -Ev '^(systemd-|dbus|cron|rsyslog|ssh|polkit|getty|user@|networkd|resolved|udev|logind|timesyncd|accounts-daemon|unattended|snapd)' \
  | sed 's/^/                 /' || true

if have nginx; then
  echo "  Сайты в nginx (server_name):"
  nginx -T 2>/dev/null | grep -E '^[[:space:]]*server_name' | tr -s ' ' | sed 's/^ *//; s/;$//' \
    | sort -u | sed 's/^/                 /' || true
  echo "  Файлы конфигурации nginx:"
  nginx -T 2>/dev/null | grep -E '^# configuration file' | sed 's/^# configuration file //; s/:$//' \
    | sed 's/^/                 /' || true
fi

echo "  Занятые порты:"
have ss && ss -tlnpH 2>/dev/null | awk '{print $4"  "$6}' | sed 's/^/                 /' | head -30

echo "  Адреса:"
ip -4 addr show scope global 2>/dev/null | awk '/inet /{print "                 IPv4 "$2}'
ip -6 addr show scope global 2>/dev/null | awk '/inet6 /{print "                 IPv6 "$2}'
V6ROUTE=$(ip -6 route show default 2>/dev/null | head -1)
echo "                 маршрут IPv6 по умолчанию: ${V6ROUTE:-НЕТ}"
V6DISABLED=$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null || echo '?')
echo "                 net.ipv6.conf.all.disable_ipv6 = $V6DISABLED"

echo "  Доступность api.telegram.org (полный HTTPS-запрос, не только TCP):"
TG_V4=нет; TG_V6=нет
if have curl; then
  c4=$(curl -4 -s -o /dev/null -w '%{http_code}' --max-time 8 https://api.telegram.org/ 2>/dev/null || true)
  c6=$(curl -6 -s -o /dev/null -w '%{http_code}' --max-time 8 https://api.telegram.org/ 2>/dev/null || true)
  [ -n "${c4:-}" ] && [ "$c4" != "000" ] && TG_V4="да (HTTP $c4)"
  [ -n "${c6:-}" ] && [ "$c6" != "000" ] && TG_V6="да (HTTP $c6)"
fi
echo "                 по IPv4: $TG_V4"
echo "                 по IPv6: $TG_V6"
if [ "$TG_V4" = "нет" ] && [ "$TG_V6" = "нет" ]; then
  warn "Ни один путь до Telegram сейчас не отвечает. Служба всё равно поставится:"
  warn "заявки будут сохраняться на диск и уйдут, как только связь появится."
fi

have getenforce && echo "  SELinux:       $(getenforce 2>/dev/null)"

# ===========================================================================
step "2. Проверка, что ничего чужого не будет затронуто"
# ===========================================================================
if [ -f "$UNIT" ] && ! grep -q "SyslogIdentifier=$SVC" "$UNIT"; then
  die "файл $UNIT существует и создан не нами. Разбирайтесь вручную."
fi

# Владелец порта определяется по cgroup процесса, а не по имени: чужой
# telegram-бот почти наверняка тоже на python3, и совпадение по имени
# означало бы попытку встать поверх него.
port_owner_is_ours() {
  local pid
  pid=$(ss -tlnpH 2>/dev/null | awk -v p=":$PORT\$" '$4 ~ p {print $0}' \
        | grep -o 'pid=[0-9]*' | head -1 | cut -d= -f2)
  [ -n "$pid" ] || return 1
  grep -qs "$SVC" "/proc/$pid/cgroup"
}

if have ss && ss -tlnH 2>/dev/null | awk -v p=":$PORT\$" '$4 ~ p' | grep -q .; then
  if port_owner_is_ours; then
    ok "порт $PORT занят нашей же службой — это перезапуск"
  elif [ -n "$PORT_FROM_ENV" ]; then
    die "порт $PORT записан в $ENV_FILE, но занят чужим процессом. Освободите его или укажите другой в файле настроек."
  else
    warn "порт $PORT занят кем-то другим:"
    ss -tlnpH 2>/dev/null | awk -v p=":$PORT\$" '$4 ~ p' | sed 's/^/      /'
    for try in $(seq $((PORT + 1)) $((PORT + 20))); do
      if ! ss -tlnH 2>/dev/null | awk -v p=":$try\$" '$4 ~ p' | grep -q .; then PORT=$try; break; fi
    done
    ok "выбран свободный порт $PORT"
  fi
else
  ok "порт $PORT свободен"
fi

for p in "$APP_DIR" "$DATA_DIR"; do
  if [ -e "$p" ] && [ ! -e "$p/.aurea-kviz" ] && [ -n "$(ls -A "$p" 2>/dev/null)" ]; then
    die "каталог $p существует, не пуст и не наш. Остановился."
  fi
done
ok "чужих файлов на пути установки нет"

if [ -n "$PANEL" ]; then
  warn "На сервере стоит $PANEL. Панели перегенерируют конфиги nginx из шаблонов"
  warn "и могут снести добавленный вручную файл. Если после действий в панели"
  warn "форма перестанет отправляться — заведите поддомен $DOMAIN средствами"
  warn "панели и пропишите проксирование на http://127.0.0.1:$PORT"
fi

# ===========================================================================
step "3. Пользователь и каталоги"
# ===========================================================================
if id "$SVC_USER" >/dev/null 2>&1; then
  ok "пользователь $SVC_USER уже есть"
else
  useradd --system --no-create-home --shell /usr/sbin/nologin --home-dir "$APP_DIR" "$SVC_USER" 2>/dev/null \
    || useradd --system --no-create-home --shell /sbin/nologin --home-dir "$APP_DIR" "$SVC_USER"
  ok "создан системный пользователь $SVC_USER"
fi

install -d -m 0755 -o root -g root "$APP_DIR"
install -d -m 0750 -o root -g "$SVC_USER" "$CFG_DIR"
install -d -m 0750 -o "$SVC_USER" -g "$SVC_USER" "$DATA_DIR"
install -d -m 0750 -o "$SVC_USER" -g "$SVC_USER" "$DATA_DIR/outbox"
install -d -m 0750 -o "$SVC_USER" -g "$SVC_USER" "$DATA_DIR/sent"
install -d -m 0755 -o root -g root "$ACME_DIR"
: > "$APP_DIR/.aurea-kviz"
: > "$DATA_DIR/.aurea-kviz"
chown "$SVC_USER:$SVC_USER" "$DATA_DIR/.aurea-kviz"
ok "каталоги на месте: $APP_DIR, $CFG_DIR, $DATA_DIR"

# ===========================================================================
step "4. Код службы"
# ===========================================================================
CHANGED=0
TMP_APP=$(mktemp)
base64 -d > "$TMP_APP" <<'AUREA_KVIZ_APP_B64'
IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwojIC0qLSBjb2Rpbmc6IHV0Zi04IC0qLQoiIiIKQVVSRUEg
wrcg0L/RgNC40ZHQvNC90LjQuiDQt9Cw0Y/QstC+0Log0YEg0LrQstC40Lct0LvQtdC90LTQuNC9
0LPQsC4KCtCi0L7Qu9GM0LrQviDRgdGC0LDQvdC00LDRgNGC0L3QsNGPINCx0LjQsdC70LjQvtGC
0LXQutCwIFB5dGhvbiAzIOKAlCDQvdCwINGB0LXRgNCy0LXRgNC1INC90LjRh9C10LPQviDQvdC1
INGB0YLQsNCy0LjRgtGB0Y8g0YfQtdGA0LXQtyBwaXAuCtCh0LvRg9GI0LDQtdGCIDEyNy4wLjAu
MSwg0L3QsNGA0YPQttGDINCy0YvRgdGC0LDQstC70Y/QtdGC0YHRjyDRh9C10YDQtdC3INC+0YLQ
tNC10LvRjNC90YvQuSDQutC+0L3RhNC40LMgbmdpbnguCgrQk9C70LDQstC90YvQtSDRgdCy0L7Q
udGB0YLQstCwOgogICog0LfQsNGP0LLQutCwINC/0LjRiNC10YLRgdGPINC90LAg0LTQuNGB0Log
0YEgZnN5bmMg0JTQniDQvtGC0LLQtdGC0LAg0LHRgNCw0YPQt9C10YDRgyDigJQg0L7QvdCwINC9
0LUg0YLQtdGA0Y/QtdGC0YHRjywKICAgINC00LDQttC1INC10YHQu9C4IFRlbGVncmFtINC90LXQ
tNC+0YHRgtGD0L/QtdC9OwogICogYXBpLnRlbGVncmFtLm9yZyDQsiDQoNC+0YHRgdC40Lgg0L3Q
tSDQvtGC0LLQtdGH0LDQtdGCINC/0L4gSVB2NCwg0L3QviDQvtGC0LLQtdGH0LDQtdGCINC/0L4g
SVB2NiDigJQKICAgINGB0LXRgNCy0LjRgSDQv9GA0L7QsdGD0LXRgiDQvtCx0LAg0L/Rg9GC0Lgs
INC30LDQv9C+0LzQuNC90LDQtdGCINGA0LDQsdC+0YfQuNC5INC4INC/0LXRgNC40L7QtNC40YfQ
tdGB0LrQuCDQv9C10YDQtdC/0YDQvtCy0LXRgNGP0LXRgjsKICAqINC90LUg0YPRiNC10LTRiNC4
0LUg0YHQvtC+0LHRidC10L3QuNGPINGB0LrQu9Cw0LTRi9Cy0LDRjtGC0YHRjyDQsiBvdXRib3gg
0Lgg0L/QtdGA0LXQvtGC0L/RgNCw0LLQu9GP0Y7RgtGB0Y8g0YEg0L/QsNGD0LfQsNC80LguCgrQ
n9C10YDQtdC80LXQvdC90YvQtSDQvtC60YDRg9C20LXQvdC40Y8gKNGE0LDQudC7IC9ldGMvYXVy
ZWEta3Zpei9rdml6LmVudiwg0L/RgNCw0LLQsCA2MDAsINGH0LjRgtCw0LXRgiBzeXN0ZW1kKToK
ICBBVVJFQV9LVklaX0JPVF9UT0tFTiAgICAgICAg0YLQvtC60LXQvSDQsdC+0YLQsCAgICAgICAg
ICAgICAgICjQvtCx0Y/Qt9Cw0YLQtdC70YzQvdC+KQogIEFVUkVBX0tWSVpfQ0hBVF9JRCAgICAg
ICAgICBpZCDQv9C+0LvRg9GH0LDRgtC10LvRjyAgICAgICAgICAgICjQvtCx0Y/Qt9Cw0YLQtdC7
0YzQvdC+KQogIEFVUkVBX0tWSVpfQklORCAgICAgICAgICAgICDQsNC00YDQtdGBLCDQv9C+INGD
0LzQvtC70YfQsNC90LjRjiAxMjcuMC4wLjEKICBBVVJFQV9LVklaX1BPUlQgICAgICAgICAgICAg
0L/QvtGA0YIsINC/0L4g0YPQvNC+0LvRh9Cw0L3QuNGOIDg3ODcKICBBVVJFQV9LVklaX0RBVEFf
RElSICAgICAgICAg0LrQsNGC0LDQu9C+0LMg0LTQsNC90L3Ri9GFLCDQv9C+INGD0LzQvtC70YfQ
sNC90LjRjiAvdmFyL2xpYi9hdXJlYS1rdml6CiAgQVVSRUFfS1ZJWl9BTExPV0VEX09SSUdJTlMg
INGB0L/QuNGB0L7QuiBPcmlnaW4g0YfQtdGA0LXQtyDQt9Cw0L/Rj9GC0YPRjiwg0L/QviDRg9C8
0L7Qu9GH0LDQvdC40Y4gKgogIEFVUkVBX0tWSVpfSVBfRkFNSUxZICAgICAgICBhdXRvIHwgaXB2
NiB8IGlwdjQsINC/0L4g0YPQvNC+0LvRh9Cw0L3QuNGOIGF1dG8KICBBVVJFQV9LVklaX1JBVEVf
UEVSX0hPVVIgICAg0LfQsNGP0LLQvtC6INGBINC+0LTQvdC+0LPQviDQsNC00YDQtdGB0LAg0LIg
0YfQsNGBLCDQv9C+INGD0LzQvtC70YfQsNC90LjRjiA4CiIiIgoKaW1wb3J0IGh0dHAuY2xpZW50
CmltcG9ydCBodHRwLnNlcnZlcgppbXBvcnQganNvbgppbXBvcnQgbG9nZ2luZwppbXBvcnQgb3MK
aW1wb3J0IHJlCmltcG9ydCBzb2NrZXQKaW1wb3J0IHNvY2tldHNlcnZlcgppbXBvcnQgc3NsCmlt
cG9ydCBzeXMKaW1wb3J0IHRocmVhZGluZwppbXBvcnQgdGltZQppbXBvcnQgdXVpZApmcm9tIGRh
dGV0aW1lIGltcG9ydCBkYXRldGltZSwgdGltZWRlbHRhLCB0aW1lem9uZQoKIyAtLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0gIwojINCa0L7QvdGE0LjQs9GD0YDQsNGG0LjRjwojIC0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LSAjCgpBUFBfTkFNRSA9ICJhdXJlYS1rdml6IgpWRVJTSU9OID0gIjEuMC4wIgoKQk9UX1RPS0VO
ID0gb3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfQk9UX1RPS0VOIiwgIiIpLnN0cmlwKCkKQ0hB
VF9JRCA9IG9zLmVudmlyb24uZ2V0KCJBVVJFQV9LVklaX0NIQVRfSUQiLCAiIikuc3RyaXAoKQpC
SU5EID0gb3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfQklORCIsICIxMjcuMC4wLjEiKS5zdHJp
cCgpClBPUlQgPSBpbnQob3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfUE9SVCIsICI4Nzg3Iikp
CkRBVEFfRElSID0gb3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfREFUQV9ESVIiLCAiL3Zhci9s
aWIvYXVyZWEta3ZpeiIpCkFMTE9XRURfT1JJR0lOUyA9IFsKICAgIG8uc3RyaXAoKS5yc3RyaXAo
Ii8iKQogICAgZm9yIG8gaW4gb3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfQUxMT1dFRF9PUklH
SU5TIiwgIioiKS5zcGxpdCgiLCIpCiAgICBpZiBvLnN0cmlwKCkKXQpJUF9GQU1JTFlfUFJFRiA9
IG9zLmVudmlyb24uZ2V0KCJBVVJFQV9LVklaX0lQX0ZBTUlMWSIsICJhdXRvIikuc3RyaXAoKS5s
b3dlcigpClJBVEVfUEVSX0hPVVIgPSBpbnQob3MuZW52aXJvbi5nZXQoIkFVUkVBX0tWSVpfUkFU
RV9QRVJfSE9VUiIsICI4IikpCgpURUxFR1JBTV9IT1NUID0gImFwaS50ZWxlZ3JhbS5vcmciCkxF
QURTX0xPRyA9IG9zLnBhdGguam9pbihEQVRBX0RJUiwgImxlYWRzLmpzb25sIikKT1VUQk9YX0RJ
UiA9IG9zLnBhdGguam9pbihEQVRBX0RJUiwgIm91dGJveCIpClNFTlRfRElSID0gb3MucGF0aC5q
b2luKERBVEFfRElSLCAic2VudCIpCk1BWF9CT0RZID0gMTYgKiAxMDI0Ck1TSyA9IHRpbWV6b25l
KHRpbWVkZWx0YShob3Vycz0zKSkKIyDQkNC00YDQtdGB0LAsINC+0YIg0LrQvtGC0L7RgNGL0YUg
0L/RgNC40L3QuNC80LDRjtGC0YHRjyDQt9Cw0LPQvtC70L7QstC60LggWC1SZWFsLUlQINC4IFgt
Rm9yd2FyZGVkLUZvci4KIyDQn9C+INGD0LzQvtC70YfQsNC90LjRjiDRgtC+0LvRjNC60L4g0LvQ
vtC60LDQu9GM0L3QsNGPINC/0LXRgtC70Y86INGB0LXRgNCy0LjRgSDRgdC70YPRiNCw0LXRgiAx
MjcuMC4wLjEg0Lgg0YHRgtC+0LjRgiDQt9CwIG5naW54LgpUUlVTVEVEX1BST1hJRVMgPSB7CiAg
ICBhLnN0cmlwKCkKICAgIGZvciBhIGluIG9zLmVudmlyb24uZ2V0KCJBVVJFQV9LVklaX1RSVVNU
RURfUFJPWElFUyIsICIxMjcuMC4wLjEsOjoxIikuc3BsaXQoIiwiKQogICAgaWYgYS5zdHJpcCgp
Cn0KCmxvZ2dpbmcuYmFzaWNDb25maWcoCiAgICBsZXZlbD1sb2dnaW5nLklORk8sCiAgICBmb3Jt
YXQ9IiUoYXNjdGltZSlzICUobGV2ZWxuYW1lKXMgJShtZXNzYWdlKXMiLAogICAgc3RyZWFtPXN5
cy5zdGRvdXQsCikKbG9nID0gbG9nZ2luZy5nZXRMb2dnZXIoQVBQX05BTUUpCgoKIyAtLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0gIwojINCi0YDQsNC90YHQv9C+0YDRgiDQtNC+IFRlbGVncmFtOiDQv9GA0LjQ
vdGD0LTQuNGC0LXQu9GM0L3Ri9C5INCy0YvQsdC+0YAgSVB2NiAvIElQdjQKIyAtLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0gIwoKY2xhc3MgRmFtaWx5SFRUUFNDb25uZWN0aW9uKGh0dHAuY2xpZW50LkhUVFBT
Q29ubmVjdGlvbik6CiAgICAiIiJIVFRQUy3RgdC+0LXQtNC40L3QtdC90LjQtSwg0LrQvtGC0L7R
gNC+0LUg0YXQvtC00LjRgiDRgdGC0YDQvtCz0L4g0L/QviDRg9C60LDQt9Cw0L3QvdC+0LzRgyDR
gdC10LzQtdC50YHRgtCy0YMg0LDQtNGA0LXRgdC+0LIuCgogICAg0JIg0YjRgtCw0YLQvdC+0Lkg
0LHQuNCx0LvQuNC+0YLQtdC60LUg0L3QtdGCINGB0L/QvtGB0L7QsdCwINGB0LrQsNC30LDRgtGM
IMKr0YLQvtC70YzQutC+IElQdjbCuzogc29ja2V0LmNyZWF0ZV9jb25uZWN0aW9uCiAgICDQv9C1
0YDQtdCx0LjRgNCw0LXRgiDQsNC00YDQtdGB0LAg0LIg0L/QvtGA0Y/QtNC60LUgZ2V0YWRkcmlu
Zm8g0Lgg0L3QsCDRgdC10YDQstC10YDQsNGFINCyINCg0KQg0L/QtdGA0LLRi9C8INC+0LHRi9GH
0L3QviDQuNC00ZHRggogICAgSVB2NC3QsNC00YDQtdGBIGFwaS50ZWxlZ3JhbS5vcmcsINC60L7R
gtC+0YDRi9C5INC90LUg0L7RgtCy0LXRh9Cw0LXRgi4g0KHQvtC10LTQuNC90LXQvdC40LUg0LLQ
uNGB0LjRgiDQtNC+INGC0LDQudC80LDRg9GC0LAsCiAgICDQuCDQsdC+0YIg0LLRi9Cz0LvRj9C0
0LjRgiDRgdC70L7QvNCw0L3QvdGL0LwuINCX0LTQtdGB0Ywg0YHQtdC80LXQudGB0YLQstC+INC3
0LDQtNCw0ZHRgtGB0Y8g0Y/QstC90L4uCiAgICAiIiIKCiAgICBkZWYgX19pbml0X18oc2VsZiwg
aG9zdCwgZmFtaWx5LCB0aW1lb3V0LCBjb250ZXh0KToKICAgICAgICBzdXBlcigpLl9faW5pdF9f
KGhvc3QsIHRpbWVvdXQ9dGltZW91dCwgY29udGV4dD1jb250ZXh0KQogICAgICAgIHNlbGYuX2Zh
bWlseSA9IGZhbWlseQoKICAgIGRlZiBjb25uZWN0KHNlbGYpOgogICAgICAgIGxhc3RfZXJyb3Ig
PSBOb25lCiAgICAgICAgdHJ5OgogICAgICAgICAgICBpbmZvcyA9IHNvY2tldC5nZXRhZGRyaW5m
byhzZWxmLmhvc3QsIHNlbGYucG9ydCwgc2VsZi5fZmFtaWx5LCBzb2NrZXQuU09DS19TVFJFQU0p
CiAgICAgICAgZXhjZXB0IE9TRXJyb3IgYXMgZXhjOgogICAgICAgICAgICByYWlzZSBPU0Vycm9y
KCLQvdC1INGA0LDQt9GA0LXRiNCw0LXRgtGB0Y8gJXM6ICVzIiAlIChzZWxmLmhvc3QsIGV4Yykp
CiAgICAgICAgaWYgbm90IGluZm9zOgogICAgICAgICAgICByYWlzZSBPU0Vycm9yKCLQvdC10YIg
0LDQtNGA0LXRgdC+0LIg0LTQu9GPINGB0LXQvNC10LnRgdGC0LLQsCAlcyIgJSBzZWxmLl9mYW1p
bHkpCiAgICAgICAgZm9yIGFmLCBzb2NrdHlwZSwgcHJvdG8sIF9jYW5vbiwgc2EgaW4gaW5mb3M6
CiAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHNvY2sgPSBzb2NrZXQuc29ja2V0KGFm
LCBzb2NrdHlwZSwgcHJvdG8pCiAgICAgICAgICAgIGV4Y2VwdCBPU0Vycm9yIGFzIGV4YzoKICAg
ICAgICAgICAgICAgIGxhc3RfZXJyb3IgPSBleGMKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAg
ICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgIHNvY2suc2V0dGltZW91dChzZWxmLnRpbWVv
dXQpCiAgICAgICAgICAgICAgICBzb2NrLmNvbm5lY3Qoc2EpCiAgICAgICAgICAgIGV4Y2VwdCBP
U0Vycm9yIGFzIGV4YzoKICAgICAgICAgICAgICAgIGxhc3RfZXJyb3IgPSBleGMKICAgICAgICAg
ICAgICAgIHNvY2suY2xvc2UoKQogICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAg
c2VsZi5zb2NrID0gc2VsZi5fY29udGV4dC53cmFwX3NvY2tldChzb2NrLCBzZXJ2ZXJfaG9zdG5h
bWU9c2VsZi5ob3N0KQogICAgICAgICAgICByZXR1cm4KICAgICAgICByYWlzZSBsYXN0X2Vycm9y
IGlmIGxhc3RfZXJyb3IgZWxzZSBPU0Vycm9yKCLQvdC1INGD0LTQsNC70L7RgdGMINC/0L7QtNC6
0LvRjtGH0LjRgtGM0YHRjyIpCgoKY2xhc3MgVGVsZWdyYW1UcmFuc3BvcnQ6CiAgICAiIiLQl9C9
0LDQtdGCLCDQv9C+INC60LDQutC+0LzRgyDRgdC10LzQtdC50YHRgtCy0YMg0LDQtNGA0LXRgdC+
0LIgVGVsZWdyYW0g0L7RgtCy0LXRh9Cw0LXRgiwg0Lgg0L/QvtC80L3QuNGCINGN0YLQvi4iIiIK
CiAgICBPUkRFUiA9IHsKICAgICAgICAiYXV0byI6IFtzb2NrZXQuQUZfSU5FVDYsIHNvY2tldC5B
Rl9JTkVUXSwKICAgICAgICAiaXB2NiI6IFtzb2NrZXQuQUZfSU5FVDZdLAogICAgICAgICJpcHY0
IjogW3NvY2tldC5BRl9JTkVUXSwKICAgIH0KICAgIE5BTUVTID0ge3NvY2tldC5BRl9JTkVUNjog
IklQdjYiLCBzb2NrZXQuQUZfSU5FVDogIklQdjQifQoKICAgIGRlZiBfX2luaXRfXyhzZWxmLCB0
b2tlbiwgcHJlZmVyZW5jZT0iYXV0byIsIHRpbWVvdXQ9MTIuMCk6CiAgICAgICAgc2VsZi5fdG9r
ZW4gPSB0b2tlbgogICAgICAgIHNlbGYuX2NhbmRpZGF0ZXMgPSBzZWxmLk9SREVSLmdldChwcmVm
ZXJlbmNlLCBzZWxmLk9SREVSWyJhdXRvIl0pCiAgICAgICAgc2VsZi5fdGltZW91dCA9IHRpbWVv
dXQKICAgICAgICBzZWxmLl9wcmVmZXJyZWQgPSBOb25lCiAgICAgICAgc2VsZi5fc3NsID0gc3Ns
LmNyZWF0ZV9kZWZhdWx0X2NvbnRleHQoKQogICAgICAgIHNlbGYuX2xvY2sgPSB0aHJlYWRpbmcu
TG9jaygpCgogICAgQHByb3BlcnR5CiAgICBkZWYgd29ya2luZ19wYXRoKHNlbGYpOgogICAgICAg
IGlmIHNlbGYuX3ByZWZlcnJlZCBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4gItC90LXQuNC3
0LLQtdGB0YLQvdC+IgogICAgICAgIHJldHVybiBzZWxmLk5BTUVTLmdldChzZWxmLl9wcmVmZXJy
ZWQsICLQvdC10LjQt9Cy0LXRgdGC0L3QviIpCgogICAgZGVmIHByb2JlKHNlbGYpOgogICAgICAg
ICIiItCf0YDQvtCy0LXRgNGP0LXRgiDQvtCx0LAg0L/Rg9GC0Lgg0Lgg0L/QuNGI0LXRgiDQsiDQ
u9C+0LMsINC60LDQutC+0Lkg0L7RgtCy0LXRh9Cw0LXRgi4g0JLRi9C30YvQstCw0LXRgtGB0Y8g
0L/RgNC4INGB0YLQsNGA0YLQtS4iIiIKICAgICAgICByZXN1bHRzID0ge30KICAgICAgICBmb3Ig
ZmFtaWx5IGluIChzb2NrZXQuQUZfSU5FVDYsIHNvY2tldC5BRl9JTkVUKToKICAgICAgICAgICAg
bmFtZSA9IHNlbGYuTkFNRVNbZmFtaWx5XQogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAg
ICBpbmZvcyA9IHNvY2tldC5nZXRhZGRyaW5mbyhURUxFR1JBTV9IT1NULCA0NDMsIGZhbWlseSwg
c29ja2V0LlNPQ0tfU1RSRUFNKQogICAgICAgICAgICBleGNlcHQgT1NFcnJvciBhcyBleGM6CiAg
ICAgICAgICAgICAgICByZXN1bHRzW25hbWVdID0gItC90LXRgiDQsNC00YDQtdGB0LAgKCVzKSIg
JSBleGMKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGlmIG5vdCBpbmZvczoK
ICAgICAgICAgICAgICAgIHJlc3VsdHNbbmFtZV0gPSAi0L3QtdGCINCw0LTRgNC10YHQsCIKICAg
ICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGFkZHJlc3MgPSBpbmZvc1swXVs0XVsw
XQogICAgICAgICAgICBzdGFydGVkID0gdGltZS5tb25vdG9uaWMoKQogICAgICAgICAgICBjb25u
ID0gTm9uZQogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAjINCf0YDQvtCy0LXRgNGP
0LXQvCDQv9C+0LvQvdC+0YbQtdC90L3Ri9C5IEhUVFBTLdC30LDQv9GA0L7RgSwg0LAg0L3QtSDR
gtC+0LvRjNC60L4gVENQLWNvbm5lY3QuCiAgICAgICAgICAgICAgICAjINCk0LjQu9GM0YLRgNCw
0YbQuNGPINGD0LzQtdC10YIg0L/RgNC40L3Rj9GC0YwgVENQINC4INC+0LHQvtGA0LLQsNGC0Ywg
0YHQvtC10LTQuNC90LXQvdC40LUg0YPQttC1CiAgICAgICAgICAgICAgICAjINC90LAgVExTOiDR
h9C40YHRgtGL0LkgY29ubmVjdCgpINC00LDQuyDQsdGLINC70L7QttC90L7QtSDCq9GA0LDQsdC+
0YLQsNC10YLCuy4KICAgICAgICAgICAgICAgIGNvbm4gPSBGYW1pbHlIVFRQU0Nvbm5lY3Rpb24o
VEVMRUdSQU1fSE9TVCwgZmFtaWx5LCA4LjAsIHNlbGYuX3NzbCkKICAgICAgICAgICAgICAgIGNv
bm4ucmVxdWVzdCgiR0VUIiwgIi8iLCBoZWFkZXJzPXsiVXNlci1BZ2VudCI6ICIlcy8lcyIgJSAo
QVBQX05BTUUsIFZFUlNJT04pfSkKICAgICAgICAgICAgICAgIHN0YXR1cyA9IGNvbm4uZ2V0cmVz
cG9uc2UoKS5zdGF0dXMKICAgICAgICAgICAgICAgIHJlc3VsdHNbbmFtZV0gPSAi0L7RgtCy0LXR
h9Cw0LXRgiDQt9CwICVkINC80YEgKCVzLCBIVFRQICVzKSIgJSAoCiAgICAgICAgICAgICAgICAg
ICAgaW50KCh0aW1lLm1vbm90b25pYygpIC0gc3RhcnRlZCkgKiAxMDAwKSwKICAgICAgICAgICAg
ICAgICAgICBhZGRyZXNzLAogICAgICAgICAgICAgICAgICAgIHN0YXR1cywKICAgICAgICAgICAg
ICAgICkKICAgICAgICAgICAgICAgIHdpdGggc2VsZi5fbG9jazoKICAgICAgICAgICAgICAgICAg
ICBpZiBzZWxmLl9wcmVmZXJyZWQgaXMgTm9uZSBhbmQgZmFtaWx5IGluIHNlbGYuX2NhbmRpZGF0
ZXM6CiAgICAgICAgICAgICAgICAgICAgICAgIHNlbGYuX3ByZWZlcnJlZCA9IGZhbWlseQogICAg
ICAgICAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGV4YzogICMgbm9xYTogQkxFMDAxCiAgICAgICAg
ICAgICAgICByZXN1bHRzW25hbWVdID0gItC90LUg0L7RgtCy0LXRh9Cw0LXRgiAoJXMpIiAlIGV4
YwogICAgICAgICAgICBmaW5hbGx5OgogICAgICAgICAgICAgICAgaWYgY29ubiBpcyBub3QgTm9u
ZToKICAgICAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgICAgIGNvbm4u
Y2xvc2UoKQogICAgICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb246ICAjIG5vcWE6IEJM
RTAwMQogICAgICAgICAgICAgICAgICAgICAgICBwYXNzCiAgICAgICAgZm9yIG5hbWUsIHZlcmRp
Y3QgaW4gcmVzdWx0cy5pdGVtcygpOgogICAgICAgICAgICBsb2cuaW5mbygiVGVsZWdyYW0g0L/Q
viAlczogJXMiLCBuYW1lLCB2ZXJkaWN0KQogICAgICAgIGlmIHNlbGYuX3ByZWZlcnJlZCBpcyBO
b25lOgogICAgICAgICAgICBsb2cud2FybmluZygKICAgICAgICAgICAgICAgICLQndC4INC+0LTQ
uNC9INC/0YPRgtGMINC00L4gJXMg0L3QtSDQvtGC0LLQtdGC0LjQuyDQv9GA0Lgg0YHRgtCw0YDR
gtC1LiAiCiAgICAgICAgICAgICAgICAi0JfQsNGP0LLQutC4INCx0YPQtNGD0YIg0YHQvtGF0YDQ
sNC90Y/RgtGM0YHRjyDQsiBvdXRib3gg0Lgg0L/QtdGA0LXQvtGC0L/RgNCw0LLQu9GP0YLRjNGB
0Y8uIiwKICAgICAgICAgICAgICAgIFRFTEVHUkFNX0hPU1QsCiAgICAgICAgICAgICkKICAgICAg
ICBlbHNlOgogICAgICAgICAgICBsb2cuaW5mbygi0JLRi9Cx0YDQsNC9INC/0YPRgtGMINC00L4g
VGVsZWdyYW06ICVzIiwgc2VsZi53b3JraW5nX3BhdGgpCiAgICAgICAgcmV0dXJuIHJlc3VsdHMK
CiAgICBkZWYgX29yZGVyKHNlbGYpOgogICAgICAgIHdpdGggc2VsZi5fbG9jazoKICAgICAgICAg
ICAgcHJlZmVycmVkID0gc2VsZi5fcHJlZmVycmVkCiAgICAgICAgaWYgcHJlZmVycmVkIGlzIE5v
bmU6CiAgICAgICAgICAgIHJldHVybiBsaXN0KHNlbGYuX2NhbmRpZGF0ZXMpCiAgICAgICAgcmV0
dXJuIFtwcmVmZXJyZWRdICsgW2YgZm9yIGYgaW4gc2VsZi5fY2FuZGlkYXRlcyBpZiBmICE9IHBy
ZWZlcnJlZF0KCiAgICBkZWYgc2VuZF9tZXNzYWdlKHNlbGYsIHRleHQpOgogICAgICAgICIiItCS
0L7Qt9Cy0YDQsNGJ0LDQtdGCIChUcnVlLCBOb25lKSDQu9C40LHQviAoRmFsc2UsICfQv9GA0LjR
h9C40L3QsCcpLiIiIgogICAgICAgIGlmIG5vdCBzZWxmLl90b2tlbiBvciBub3QgQ0hBVF9JRDoK
ICAgICAgICAgICAgcmV0dXJuIEZhbHNlLCAi0L3QtSDQt9Cw0LTQsNC90YsgQVVSRUFfS1ZJWl9C
T1RfVE9LRU4g0LjQu9C4IEFVUkVBX0tWSVpfQ0hBVF9JRCIKCiAgICAgICAgcGF5bG9hZCA9IGpz
b24uZHVtcHMoCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJjaGF0X2lkIjogQ0hBVF9J
RCwKICAgICAgICAgICAgICAgICJ0ZXh0IjogdGV4dCwKICAgICAgICAgICAgICAgICJwYXJzZV9t
b2RlIjogIkhUTUwiLAogICAgICAgICAgICAgICAgImRpc2FibGVfd2ViX3BhZ2VfcHJldmlldyI6
IFRydWUsCiAgICAgICAgICAgIH0KICAgICAgICApLmVuY29kZSgidXRmLTgiKQoKICAgICAgICBl
cnJvcnMgPSBbXQogICAgICAgIGZvciBmYW1pbHkgaW4gc2VsZi5fb3JkZXIoKToKICAgICAgICAg
ICAgbmFtZSA9IHNlbGYuTkFNRVNbZmFtaWx5XQogICAgICAgICAgICBjb25uID0gTm9uZQogICAg
ICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICBjb25uID0gRmFtaWx5SFRUUFNDb25uZWN0aW9u
KAogICAgICAgICAgICAgICAgICAgIFRFTEVHUkFNX0hPU1QsIGZhbWlseSwgc2VsZi5fdGltZW91
dCwgc2VsZi5fc3NsCiAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICBjb25uLnJlcXVl
c3QoCiAgICAgICAgICAgICAgICAgICAgIlBPU1QiLAogICAgICAgICAgICAgICAgICAgICIvYm90
JXMvc2VuZE1lc3NhZ2UiICUgc2VsZi5fdG9rZW4sCiAgICAgICAgICAgICAgICAgICAgYm9keT1w
YXlsb2FkLAogICAgICAgICAgICAgICAgICAgIGhlYWRlcnM9ewogICAgICAgICAgICAgICAgICAg
ICAgICAiQ29udGVudC1UeXBlIjogImFwcGxpY2F0aW9uL2pzb24iLAogICAgICAgICAgICAgICAg
ICAgICAgICAiQ29udGVudC1MZW5ndGgiOiBzdHIobGVuKHBheWxvYWQpKSwKICAgICAgICAgICAg
ICAgICAgICAgICAgIlVzZXItQWdlbnQiOiAiJXMvJXMiICUgKEFQUF9OQU1FLCBWRVJTSU9OKSwK
ICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAg
cmVzcG9uc2UgPSBjb25uLmdldHJlc3BvbnNlKCkKICAgICAgICAgICAgICAgIHJhdyA9IHJlc3Bv
bnNlLnJlYWQoNjQgKiAxMDI0KQogICAgICAgICAgICAgICAgaWYgcmVzcG9uc2Uuc3RhdHVzID09
IDIwMDoKICAgICAgICAgICAgICAgICAgICB3aXRoIHNlbGYuX2xvY2s6CiAgICAgICAgICAgICAg
ICAgICAgICAgIHNlbGYuX3ByZWZlcnJlZCA9IGZhbWlseQogICAgICAgICAgICAgICAgICAgIHJl
dHVybiBUcnVlLCBOb25lCiAgICAgICAgICAgICAgICAjINCi0L7QutC10L0v0YfQsNGCINC90LXQ
stC10YDQvdGLIOKAlCDQv9C10YDQtdCx0LjRgNCw0YLRjCDRgdC10LzQtdC50YHRgtCy0LAg0LHQ
tdGB0YHQvNGL0YHQu9C10L3QvdC+LgogICAgICAgICAgICAgICAgZGV0YWlsID0gX2Rlc2NyaWJl
X3RlbGVncmFtX2Vycm9yKHJlc3BvbnNlLnN0YXR1cywgcmF3KQogICAgICAgICAgICAgICAgZXJy
b3JzLmFwcGVuZCgiJXM6ICVzIiAlIChuYW1lLCBkZXRhaWwpKQogICAgICAgICAgICAgICAgaWYg
cmVzcG9uc2Uuc3RhdHVzIGluICg0MDAsIDQwMSwgNDAzLCA0MDQpOgogICAgICAgICAgICAgICAg
ICAgIGJyZWFrCiAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZXhjOiAgIyBub3FhOiBC
TEUwMDEg4oCUINC90LDRgNGD0LbRgyDRg9GF0L7QtNC40YIg0YLQtdC60YHRgtC+0Lwg0LIg0LvQ
vtCzCiAgICAgICAgICAgICAgICBlcnJvcnMuYXBwZW5kKCIlczogJXMiICUgKG5hbWUsIGV4Yykp
CiAgICAgICAgICAgIGZpbmFsbHk6CiAgICAgICAgICAgICAgICBpZiBjb25uIGlzIG5vdCBOb25l
OgogICAgICAgICAgICAgICAgICAgIHRyeToKICAgICAgICAgICAgICAgICAgICAgICAgY29ubi5j
bG9zZSgpCiAgICAgICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbjogICMgbm9xYTogQkxF
MDAxCiAgICAgICAgICAgICAgICAgICAgICAgIHBhc3MKICAgICAgICB3aXRoIHNlbGYuX2xvY2s6
CiAgICAgICAgICAgIHNlbGYuX3ByZWZlcnJlZCA9IE5vbmUKICAgICAgICByZXR1cm4gRmFsc2Us
ICI7ICIuam9pbihlcnJvcnMpIG9yICLQvdC10LjQt9Cy0LXRgdGC0L3QsNGPINC+0YjQuNCx0LrQ
sCIKCgpkZWYgX2Rlc2NyaWJlX3RlbGVncmFtX2Vycm9yKHN0YXR1cywgcmF3KToKICAgIHRyeToK
ICAgICAgICBkYXRhID0ganNvbi5sb2FkcyhyYXcuZGVjb2RlKCJ1dGYtOCIsICJyZXBsYWNlIikp
CiAgICAgICAgcmV0dXJuICJIVFRQICVzICVzIiAlIChzdGF0dXMsIGRhdGEuZ2V0KCJkZXNjcmlw
dGlvbiIsICIiKSkKICAgIGV4Y2VwdCBFeGNlcHRpb246ICAjIG5vcWE6IEJMRTAwMQogICAgICAg
IHJldHVybiAiSFRUUCAlcyIgJSBzdGF0dXMKCgojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAjCiMg0KXR
gNCw0L3QuNC70LjRidC1INC30LDRj9Cy0L7QugojIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAjCgpkZWYg
X2ZzeW5jX2RpcihwYXRoKToKICAgIHRyeToKICAgICAgICBmZCA9IG9zLm9wZW4ocGF0aCwgb3Mu
T19ESVJFQ1RPUlkpCiAgICBleGNlcHQgKEF0dHJpYnV0ZUVycm9yLCBPU0Vycm9yKToKICAgICAg
ICByZXR1cm4KICAgIHRyeToKICAgICAgICBvcy5mc3luYyhmZCkKICAgIGZpbmFsbHk6CiAgICAg
ICAgb3MuY2xvc2UoZmQpCgoKY2xhc3MgTGVhZFN0b3JlOgogICAgIiIi0JbRg9GA0L3QsNC7INCy
0YHQtdGFINC30LDRj9Cy0L7QuiArINC+0YfQtdGA0LXQtNGMINC90LXQvtGC0L/RgNCw0LLQu9C1
0L3QvdGL0YUuCgogICAgbGVhZHMuanNvbmwg4oCUINCy0LXRh9C90YvQuSDQttGD0YDQvdCw0Lss
INGC0YPQtNCwINC/0LjRiNC10YLRgdGPINC60LDQttC00LDRjyDQt9Cw0Y/QstC60LAuCiAgICBv
dXRib3gvICAgICDigJQg0L/QviDRhNCw0LnQu9GDINC90LAg0L3QtdC+0YLQv9GA0LDQstC70LXQ
vdC90YPRjiDQt9Cw0Y/QstC60YMuCiAgICBzZW50LyAgICAgICDigJQg0YLQviwg0YfRgtC+INCy
INC40YLQvtCz0LUg0YPRiNC70L4gKNGH0YLQvtCx0Ysgb3V0Ym94INC90LUg0YDQvtGBINC4INCx
0YvQu9C+INCy0LjQtNC90L4g0LjRgdGC0L7RgNC40Y4pLgogICAgIiIiCgogICAgZGVmIF9faW5p
dF9fKHNlbGYsIGRhdGFfZGlyKToKICAgICAgICBzZWxmLmRhdGFfZGlyID0gZGF0YV9kaXIKICAg
ICAgICBzZWxmLl9sb2NrID0gdGhyZWFkaW5nLkxvY2soKQogICAgICAgIGZvciBwYXRoIGluIChk
YXRhX2RpciwgT1VUQk9YX0RJUiwgU0VOVF9ESVIpOgogICAgICAgICAgICBvcy5tYWtlZGlycyhw
YXRoLCBleGlzdF9vaz1UcnVlKQoKICAgIGRlZiBhcHBlbmQoc2VsZiwgbGVhZCk6CiAgICAgICAg
bGluZSA9IGpzb24uZHVtcHMobGVhZCwgZW5zdXJlX2FzY2lpPUZhbHNlKSArICJcbiIKICAgICAg
ICB3aXRoIHNlbGYuX2xvY2s6CiAgICAgICAgICAgIHdpdGggb3BlbihMRUFEU19MT0csICJhIiwg
ZW5jb2Rpbmc9InV0Zi04IikgYXMgaGFuZGxlOgogICAgICAgICAgICAgICAgaGFuZGxlLndyaXRl
KGxpbmUpCiAgICAgICAgICAgICAgICBoYW5kbGUuZmx1c2goKQogICAgICAgICAgICAgICAgb3Mu
ZnN5bmMoaGFuZGxlLmZpbGVubygpKQoKICAgIGRlZiBlbnF1ZXVlKHNlbGYsIGxlYWQpOgogICAg
ICAgIHBhdGggPSBvcy5wYXRoLmpvaW4oT1VUQk9YX0RJUiwgIiVzLmpzb24iICUgbGVhZFsiaWQi
XSkKICAgICAgICB0bXAgPSBwYXRoICsgIi50bXAiCiAgICAgICAgd2l0aCBvcGVuKHRtcCwgInci
LCBlbmNvZGluZz0idXRmLTgiKSBhcyBoYW5kbGU6CiAgICAgICAgICAgIGpzb24uZHVtcChsZWFk
LCBoYW5kbGUsIGVuc3VyZV9hc2NpaT1GYWxzZSwgaW5kZW50PTEpCiAgICAgICAgICAgIGhhbmRs
ZS5mbHVzaCgpCiAgICAgICAgICAgIG9zLmZzeW5jKGhhbmRsZS5maWxlbm8oKSkKICAgICAgICBv
cy5yZXBsYWNlKHRtcCwgcGF0aCkKICAgICAgICBfZnN5bmNfZGlyKE9VVEJPWF9ESVIpCgogICAg
ZGVmIHBlbmRpbmcoc2VsZik6CiAgICAgICAgdHJ5OgogICAgICAgICAgICBuYW1lcyA9IHNvcnRl
ZChuIGZvciBuIGluIG9zLmxpc3RkaXIoT1VUQk9YX0RJUikgaWYgbi5lbmRzd2l0aCgiLmpzb24i
KSkKICAgICAgICBleGNlcHQgRmlsZU5vdEZvdW5kRXJyb3I6CiAgICAgICAgICAgIHJldHVybiBb
XQogICAgICAgIG91dCA9IFtdCiAgICAgICAgZm9yIG5hbWUgaW4gbmFtZXM6CiAgICAgICAgICAg
IHRyeToKICAgICAgICAgICAgICAgIHdpdGggb3Blbihvcy5wYXRoLmpvaW4oT1VUQk9YX0RJUiwg
bmFtZSksIGVuY29kaW5nPSJ1dGYtOCIpIGFzIGhhbmRsZToKICAgICAgICAgICAgICAgICAgICBv
dXQuYXBwZW5kKGpzb24ubG9hZChoYW5kbGUpKQogICAgICAgICAgICBleGNlcHQgKE9TRXJyb3Is
IFZhbHVlRXJyb3IpIGFzIGV4YzoKICAgICAgICAgICAgICAgIGxvZy5lcnJvcigi0J3QtSDRh9C4
0YLQsNC10YLRgdGPICVzOiAlcyIsIG5hbWUsIGV4YykKICAgICAgICByZXR1cm4gb3V0CgogICAg
ZGVmIG1hcmtfc2VudChzZWxmLCBsZWFkX2lkKToKICAgICAgICBzcmMgPSBvcy5wYXRoLmpvaW4o
T1VUQk9YX0RJUiwgIiVzLmpzb24iICUgbGVhZF9pZCkKICAgICAgICBkc3QgPSBvcy5wYXRoLmpv
aW4oU0VOVF9ESVIsICIlcy5qc29uIiAlIGxlYWRfaWQpCiAgICAgICAgdHJ5OgogICAgICAgICAg
ICBvcy5yZXBsYWNlKHNyYywgZHN0KQogICAgICAgIGV4Y2VwdCBGaWxlTm90Rm91bmRFcnJvcjoK
ICAgICAgICAgICAgcGFzcwoKICAgIGRlZiBwZW5kaW5nX2NvdW50KHNlbGYpOgogICAgICAgIHRy
eToKICAgICAgICAgICAgcmV0dXJuIHN1bSgxIGZvciBuIGluIG9zLmxpc3RkaXIoT1VUQk9YX0RJ
UikgaWYgbi5lbmRzd2l0aCgiLmpzb24iKSkKICAgICAgICBleGNlcHQgRmlsZU5vdEZvdW5kRXJy
b3I6CiAgICAgICAgICAgIHJldHVybiAwCgoKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gIwojINCg0LDQ
t9Cx0L7RgCDQuCDQv9GA0L7QstC10YDQutCwINC30LDRj9Cy0LrQuAojIC0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLSAjCgpQSE9ORV9ESUdJVFMgPSByZS5jb21waWxlKHIiXGQiKQpOQU1FX09LID0gcmUuY29t
cGlsZShyIl5bXHdcc1wtJ+KAmS5dezIsNjB9JCIsIHJlLlVOSUNPREUpCkNIQU5ORUxTID0geyJ0
ZWxlZ3JhbSI6ICJUZWxlZ3JhbSIsICJjYWxsIjogItCX0LLQvtC90L7QuiJ9CgoKUEhPTkVfQUxM
T1dFRCA9IHJlLmNvbXBpbGUociJeW1xkXHMrKClcLS5dKyQiKQoKCmRlZiBhY2NlcHRfcGhvbmUo
cmF3KToKICAgICIiItCf0YDQuNC90LjQvNCw0LXRgiDQvdC+0LzQtdGAINGA0L7QstC90L4g0LIg
0YLQvtC8INCy0LjQtNC1LCDQsiDQutCw0LrQvtC8INC10LPQviDQvdCw0L/QtdGH0LDRgtCw0LvQ
uC4KCiAgICDQndC40YfQtdCz0L4g0L3QtSDQv9C10YDQtdGB0YLQsNCy0LvRj9C10Lwg0Lgg0L3Q
tSDQtNC+0L/QuNGB0YvQstCw0LXQvDog0YfQtdC70L7QstC10Log0LLQstGR0Lsg0LrQsNC6INC1
0LzRgyDRg9C00L7QsdC90L4sCiAgICDQuCDQsiDQt9Cw0Y/QstC60LUg0LLQu9Cw0LTQtdC70LXR
hiDRg9Cy0LjQtNC40YIg0LXQs9C+INC20LUg0LfQsNC/0LjRgdGMLiDQn9GA0L7QstC10YDRj9C1
0Lwg0YLQvtC70YzQutC+LCDRh9GC0L4g0Y3RgtC+CiAgICDQstC+0L7QsdGJ0LUg0L/QvtGF0L7Q
ttC1INC90LAg0L3QvtC80LXRgCDigJQg0L7RgiDQtNC10YHRj9GC0Lgg0LTQviDQv9GP0YLQvdCw
0LTRhtCw0YLQuCDRhtC40YTRgCDQuCDQsdC10Lcg0LHRg9C60LIuCiAgICDQktC+0LfQstGA0LDR
idCw0LXRgiAo0LrQsNC6X9C90LDQv9C10YfQsNGC0LDQvdC+LCDRgtC+0LvRjNC60L5f0YbQuNGE
0YDRiykg0LvQuNCx0L4gKE5vbmUsIE5vbmUpLgogICAgIiIiCiAgICB2YWx1ZSA9IChyYXcgb3Ig
IiIpLnN0cmlwKCkKICAgIGlmIG5vdCB2YWx1ZSBvciBsZW4odmFsdWUpID4gNDA6CiAgICAgICAg
cmV0dXJuIE5vbmUsIE5vbmUKICAgIGlmIG5vdCBQSE9ORV9BTExPV0VELm1hdGNoKHZhbHVlKToK
ICAgICAgICByZXR1cm4gTm9uZSwgTm9uZQogICAgZGlnaXRzID0gIiIuam9pbihQSE9ORV9ESUdJ
VFMuZmluZGFsbCh2YWx1ZSkpCiAgICBpZiBub3QgMTAgPD0gbGVuKGRpZ2l0cykgPD0gMTU6CiAg
ICAgICAgcmV0dXJuIE5vbmUsIE5vbmUKICAgIHJldHVybiB2YWx1ZSwgZGlnaXRzCgoKZGVmIGNs
ZWFuX3RleHQodmFsdWUsIGxpbWl0KToKICAgIGlmIG5vdCBpc2luc3RhbmNlKHZhbHVlLCBzdHIp
OgogICAgICAgIHJldHVybiAiIgogICAgcmV0dXJuIHZhbHVlLnJlcGxhY2UoIlxyIiwgIiAiKS5y
ZXBsYWNlKCJcbiIsICIgIikuc3RyaXAoKVs6bGltaXRdCgoKZGVmIHBhcnNlX2xlYWQocGF5bG9h
ZCwgcmVtb3RlX2lwLCB1c2VyX2FnZW50KToKICAgIGVycm9ycyA9IHt9CgogICAgbmFtZSA9IGNs
ZWFuX3RleHQocGF5bG9hZC5nZXQoIm5hbWUiKSwgNjApCiAgICBpZiBsZW4obmFtZSkgPCAyIG9y
IG5vdCBOQU1FX09LLm1hdGNoKG5hbWUpOgogICAgICAgIGVycm9yc1sibmFtZSJdID0gItCY0LzR
jyDQvdC1INC/0L7RhdC+0LbQtSDQvdCwINC40LzRjyIKCiAgICBwaG9uZSwgcGhvbmVfZGlnaXRz
ID0gYWNjZXB0X3Bob25lKHBheWxvYWQuZ2V0KCJwaG9uZSIpKQogICAgaWYgbm90IHBob25lOgog
ICAgICAgIGVycm9yc1sicGhvbmUiXSA9ICLQrdGC0L4g0L3QtSDQv9C+0YXQvtC20LUg0L3QsCDQ
vdC+0LzQtdGAINGC0LXQu9C10YTQvtC90LAiCgogICAgY2hhbm5lbCA9IHBheWxvYWQuZ2V0KCJj
aGFubmVsIikKICAgIGlmIGNoYW5uZWwgbm90IGluIENIQU5ORUxTOgogICAgICAgIGVycm9yc1si
Y2hhbm5lbCJdID0gItCd0LXQuNC30LLQtdGB0YLQvdGL0Lkg0YHQv9C+0YHQvtCxINGB0LLRj9C3
0LgiCgogICAgaWYgY2xlYW5fdGV4dChwYXlsb2FkLmdldCgiY29tcGFueSIpLCAxMDApOgogICAg
ICAgICMg0JvQvtCy0YPRiNC60LAg0LTQu9GPINCx0L7RgtC+0LI6INC/0L7Qu9C1INGB0LrRgNGL
0YLQviDQvtGCINGH0LXQu9C+0LLQtdC60LAg0Lgg0LLRgdC10LPQtNCwINC00L7Qu9C20L3QviDQ
sdGL0YLRjCDQv9GD0YHRgtGL0LwuCiAgICAgICAgZXJyb3JzWyJjb21wYW55Il0gPSAic3BhbSIK
CiAgICBhbnN3ZXJzID0gcGF5bG9hZC5nZXQoImFuc3dlcnMiKQogICAgaWYgbm90IGlzaW5zdGFu
Y2UoYW5zd2VycywgbGlzdCk6CiAgICAgICAgYW5zd2VycyA9IFtdCiAgICBzYWZlX2Fuc3dlcnMg
PSBbXQogICAgZm9yIGl0ZW0gaW4gYW5zd2Vyc1s6MTJdOgogICAgICAgIGlmIG5vdCBpc2luc3Rh
bmNlKGl0ZW0sIGRpY3QpOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIHNhZmVfYW5zd2Vy
cy5hcHBlbmQoCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJxdWVzdGlvbiI6IGNsZWFu
X3RleHQoaXRlbS5nZXQoInF1ZXN0aW9uIiksIDEyMCksCiAgICAgICAgICAgICAgICAiYW5zd2Vy
IjogY2xlYW5fdGV4dChpdGVtLmdldCgiYW5zd2VyIiksIDEyMCksCiAgICAgICAgICAgIH0KICAg
ICAgICApCgogICAgcHJpY2UgPSBwYXlsb2FkLmdldCgicHJpY2UiKSBpZiBpc2luc3RhbmNlKHBh
eWxvYWQuZ2V0KCJwcmljZSIpLCBkaWN0KSBlbHNlIHt9CiAgICBsb3cgPSBwcmljZS5nZXQoImxv
dyIpCiAgICBoaWdoID0gcHJpY2UuZ2V0KCJoaWdoIikKICAgIGlmIG5vdCBpc2luc3RhbmNlKGxv
dywgKGludCwgZmxvYXQpKSBvciBub3QgMCA8PSBsb3cgPD0gMTBfMDAwXzAwMDoKICAgICAgICBs
b3cgPSBOb25lCiAgICBpZiBub3QgaXNpbnN0YW5jZShoaWdoLCAoaW50LCBmbG9hdCkpIG9yIG5v
dCAwIDw9IGhpZ2ggPD0gMTBfMDAwXzAwMDoKICAgICAgICBoaWdoID0gTm9uZQoKICAgIHNvdXJj
ZSA9IHBheWxvYWQuZ2V0KCJzb3VyY2UiKSBpZiBpc2luc3RhbmNlKHBheWxvYWQuZ2V0KCJzb3Vy
Y2UiKSwgZGljdCkgZWxzZSB7fQogICAgc2FmZV9zb3VyY2UgPSB7CiAgICAgICAga2V5OiBjbGVh
bl90ZXh0KHNvdXJjZS5nZXQoa2V5KSwgMTIwKQogICAgICAgIGZvciBrZXkgaW4gKCJ1dG1fc291
cmNlIiwgInV0bV9tZWRpdW0iLCAidXRtX2NhbXBhaWduIiwgInV0bV90ZXJtIiwgInV0bV9jb250
ZW50IiwgInJlZmVycmVyIiwgInBhZ2UiKQogICAgICAgIGlmIHNvdXJjZS5nZXQoa2V5KQogICAg
fQoKICAgIGxlYWQgPSB7CiAgICAgICAgImlkIjogdXVpZC51dWlkNCgpLmhleFs6MTJdLAogICAg
ICAgICJyZWNlaXZlZF9hdCI6IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLmlzb2Zvcm1hdCh0
aW1lc3BlYz0ic2Vjb25kcyIpLAogICAgICAgICJuYW1lIjogbmFtZSwKICAgICAgICAjINCg0L7Q
stC90L4g0YLQviwg0YfRgtC+INC90LDQv9C10YfQsNGC0LDQuyDRh9C10LvQvtCy0LXQui4KICAg
ICAgICAicGhvbmUiOiBwaG9uZSwKICAgICAgICAjINCi0L7Qu9GM0LrQviDRhtC40YTRgNGLIOKA
lCDQvdGD0LbQvdGLINC00LvRjyDRgdGB0YvQu9C60Lgg0LIgVGVsZWdyYW0sINCyINGB0L7QvtCx
0YnQtdC90LjQuCDQvdC1INC/0L7QutCw0LfRi9Cy0LDRjtGC0YHRjy4KICAgICAgICAicGhvbmVf
ZGlnaXRzIjogcGhvbmVfZGlnaXRzLAogICAgICAgICJjaGFubmVsIjogY2hhbm5lbCwKICAgICAg
ICAiY2hhbm5lbF9sYWJlbCI6IENIQU5ORUxTLmdldChjaGFubmVsLCAi4oCUIiksCiAgICAgICAg
ImFuc3dlcnMiOiBzYWZlX2Fuc3dlcnMsCiAgICAgICAgInByaWNlIjogeyJsb3ciOiBsb3csICJo
aWdoIjogaGlnaH0sCiAgICAgICAgInNvdXJjZSI6IHNhZmVfc291cmNlLAogICAgICAgICJjbGll
bnRfaWQiOiBjbGVhbl90ZXh0KHBheWxvYWQuZ2V0KCJjbGllbnRJZCIpLCA2NCksCiAgICAgICAg
InJlbW90ZV9pcCI6IHJlbW90ZV9pcCwKICAgICAgICAidXNlcl9hZ2VudCI6IGNsZWFuX3RleHQo
dXNlcl9hZ2VudCwgMjAwKSwKICAgIH0KICAgIHJldHVybiBsZWFkLCBlcnJvcnMKCgpkZWYgZXNj
YXBlX2h0bWwodmFsdWUpOgogICAgcmV0dXJuICgKICAgICAgICBzdHIodmFsdWUpCiAgICAgICAg
LnJlcGxhY2UoIiYiLCAiJmFtcDsiKQogICAgICAgIC5yZXBsYWNlKCI8IiwgIiZsdDsiKQogICAg
ICAgIC5yZXBsYWNlKCI+IiwgIiZndDsiKQogICAgKQoKCmRlZiBmb3JtYXRfbW9uZXkodmFsdWUp
OgogICAgaWYgdmFsdWUgaXMgTm9uZToKICAgICAgICByZXR1cm4gIuKAlCIKICAgIHJldHVybiAi
ezosfSIuZm9ybWF0KGludChyb3VuZCh2YWx1ZSkpKS5yZXBsYWNlKCIsIiwgIiAiKSArICIg4oK9
IgoKCmRlZiByZW5kZXJfbWVzc2FnZShsZWFkKToKICAgIHJlY2VpdmVkID0gZGF0ZXRpbWUuZnJv
bWlzb2Zvcm1hdChsZWFkWyJyZWNlaXZlZF9hdCJdKS5hc3RpbWV6b25lKE1TSykKICAgIGxpbmVz
ID0gWwogICAgICAgICI8Yj7Ql9Cw0Y/QstC60LAg0YEg0LrQstC40LfQsDwvYj4iLAogICAgICAg
ICIiLAogICAgICAgICI8Yj4lczwvYj4iICUgZXNjYXBlX2h0bWwobGVhZFsibmFtZSJdKSwKICAg
ICAgICAiJXMgwrcgJXMiICUgKGVzY2FwZV9odG1sKGxlYWRbInBob25lIl0pLCBlc2NhcGVfaHRt
bChsZWFkWyJjaGFubmVsX2xhYmVsIl0pKSwKICAgIF0KICAgIGlmIGxlYWRbImNoYW5uZWwiXSA9
PSAidGVsZWdyYW0iIGFuZCBsZWFkLmdldCgicGhvbmVfZGlnaXRzIik6CiAgICAgICAgbGluZXMu
YXBwZW5kKCLQndCw0L/QuNGB0LDRgtGMOiBodHRwczovL3QubWUvKyVzIiAlIGxlYWRbInBob25l
X2RpZ2l0cyJdKQoKICAgIGxvdyA9IGxlYWRbInByaWNlIl0uZ2V0KCJsb3ciKQogICAgaGlnaCA9
IGxlYWRbInByaWNlIl0uZ2V0KCJoaWdoIikKICAgIGlmIGxvdyBhbmQgaGlnaDoKICAgICAgICBs
aW5lcyArPSBbIiIsICLQktC40LvQutCwINC90LAg0Y3QutGA0LDQvdC1OiA8Yj4lcyDigJQgJXM8
L2I+IiAlIChmb3JtYXRfbW9uZXkobG93KSwgZm9ybWF0X21vbmV5KGhpZ2gpKV0KCiAgICBpZiBs
ZWFkWyJhbnN3ZXJzIl06CiAgICAgICAgbGluZXMuYXBwZW5kKCIiKQogICAgICAgIGZvciBpbmRl
eCwgaXRlbSBpbiBlbnVtZXJhdGUobGVhZFsiYW5zd2VycyJdLCBzdGFydD0xKToKICAgICAgICAg
ICAgbGluZXMuYXBwZW5kKAogICAgICAgICAgICAgICAgIiVkLiAlcyDigJQgPGI+JXM8L2I+Igog
ICAgICAgICAgICAgICAgJSAoaW5kZXgsIGVzY2FwZV9odG1sKGl0ZW1bInF1ZXN0aW9uIl0pLCBl
c2NhcGVfaHRtbChpdGVtWyJhbnN3ZXIiXSkpCiAgICAgICAgICAgICkKCiAgICBzb3VyY2UgPSBs
ZWFkLmdldCgic291cmNlIikgb3Ige30KICAgIGlmIHNvdXJjZToKICAgICAgICBsaW5lcy5hcHBl
bmQoIiIpCiAgICAgICAgY2FtcGFpZ24gPSAiIC8gIi5qb2luKAogICAgICAgICAgICBlc2NhcGVf
aHRtbChzb3VyY2Vba2V5XSkKICAgICAgICAgICAgZm9yIGtleSBpbiAoInV0bV9zb3VyY2UiLCAi
dXRtX21lZGl1bSIsICJ1dG1fY2FtcGFpZ24iKQogICAgICAgICAgICBpZiBzb3VyY2UuZ2V0KGtl
eSkKICAgICAgICApCiAgICAgICAgaWYgY2FtcGFpZ246CiAgICAgICAgICAgIGxpbmVzLmFwcGVu
ZCgi0JrQsNC80L/QsNC90LjRjzogJXMiICUgY2FtcGFpZ24pCiAgICAgICAgaWYgc291cmNlLmdl
dCgidXRtX3Rlcm0iKToKICAgICAgICAgICAgbGluZXMuYXBwZW5kKCLQl9Cw0L/RgNC+0YE6ICVz
IiAlIGVzY2FwZV9odG1sKHNvdXJjZVsidXRtX3Rlcm0iXSkpCiAgICAgICAgaWYgc291cmNlLmdl
dCgicmVmZXJyZXIiKToKICAgICAgICAgICAgbGluZXMuYXBwZW5kKCLQn9C10YDQtdGF0L7QtCDR
gTogJXMiICUgZXNjYXBlX2h0bWwoc291cmNlWyJyZWZlcnJlciJdKSkKCiAgICBsaW5lcyArPSBb
IiIsICIlcyDQnNCh0Jogwrcg4oSWJXMiICUgKHJlY2VpdmVkLnN0cmZ0aW1lKCIlZC4lbS4lWSAl
SDolTSIpLCBsZWFkWyJpZCJdKV0KICAgIHJldHVybiAiXG4iLmpvaW4obGluZXMpCgoKIyAtLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0gIwojINCe0LPRgNCw0L3QuNGH0LXQvdC40LUg0YfQsNGB0YLQvtGC0YsK
IyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0gIwoKY2xhc3MgUmF0ZUxpbWl0ZXI6CiAgICBkZWYgX19pbml0
X18oc2VsZiwgcGVyX2hvdXIpOgogICAgICAgIHNlbGYuX3Blcl9ob3VyID0gbWF4KDEsIHBlcl9o
b3VyKQogICAgICAgIHNlbGYuX2hpdHMgPSB7fQogICAgICAgIHNlbGYuX2xvY2sgPSB0aHJlYWRp
bmcuTG9jaygpCgogICAgZGVmIGFsbG93KHNlbGYsIGtleSk6CiAgICAgICAgbm93ID0gdGltZS5t
b25vdG9uaWMoKQogICAgICAgIGN1dG9mZiA9IG5vdyAtIDM2MDAKICAgICAgICB3aXRoIHNlbGYu
X2xvY2s6CiAgICAgICAgICAgIGJ1Y2tldCA9IFt0IGZvciB0IGluIHNlbGYuX2hpdHMuZ2V0KGtl
eSwgW10pIGlmIHQgPiBjdXRvZmZdCiAgICAgICAgICAgIGlmIGxlbihidWNrZXQpID49IHNlbGYu
X3Blcl9ob3VyOgogICAgICAgICAgICAgICAgc2VsZi5faGl0c1trZXldID0gYnVja2V0CiAgICAg
ICAgICAgICAgICByZXR1cm4gRmFsc2UKICAgICAgICAgICAgYnVja2V0LmFwcGVuZChub3cpCiAg
ICAgICAgICAgIHNlbGYuX2hpdHNba2V5XSA9IGJ1Y2tldAogICAgICAgICAgICBpZiBsZW4oc2Vs
Zi5faGl0cykgPiA1MDAwOgogICAgICAgICAgICAgICAgc2VsZi5faGl0cyA9IHsKICAgICAgICAg
ICAgICAgICAgICBrOiB2IGZvciBrLCB2IGluIHNlbGYuX2hpdHMuaXRlbXMoKSBpZiB2IGFuZCB2
Wy0xXSA+IGN1dG9mZgogICAgICAgICAgICAgICAgfQogICAgICAgICAgICByZXR1cm4gVHJ1ZQoK
CiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tICMKIyDQpNC+0L3QvtCy0LDRjyDQv9C10YDQtdC+0YLQv9GA
0LDQstC60LAKIyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gIwoKY2xhc3MgT3V0Ym94V29ya2VyKHRocmVh
ZGluZy5UaHJlYWQpOgogICAgIiIi0KDQsNC3INCyINC80LjQvdGD0YLRgyDQv9GL0YLQsNC10YLR
gdGPINC00L7RgdGC0LDQstC40YLRjCDQstGB0ZEsINGH0YLQviDQu9C10LbQuNGCINCyIG91dGJv
eC4iIiIKCiAgICBkYWVtb24gPSBUcnVlCgogICAgZGVmIF9faW5pdF9fKHNlbGYsIHN0b3JlLCB0
cmFuc3BvcnQsIGludGVydmFsPTYwLjApOgogICAgICAgIHN1cGVyKCkuX19pbml0X18obmFtZT0i
b3V0Ym94IikKICAgICAgICBzZWxmLl9zdG9yZSA9IHN0b3JlCiAgICAgICAgc2VsZi5fdHJhbnNw
b3J0ID0gdHJhbnNwb3J0CiAgICAgICAgc2VsZi5faW50ZXJ2YWwgPSBpbnRlcnZhbAogICAgICAg
IHNlbGYuX3dha2UgPSB0aHJlYWRpbmcuRXZlbnQoKQogICAgICAgIHNlbGYuX3N0b3AgPSB0aHJl
YWRpbmcuRXZlbnQoKQoKICAgIGRlZiBwb2tlKHNlbGYpOgogICAgICAgIHNlbGYuX3dha2Uuc2V0
KCkKCiAgICBkZWYgc3RvcChzZWxmKToKICAgICAgICBzZWxmLl9zdG9wLnNldCgpCiAgICAgICAg
c2VsZi5fd2FrZS5zZXQoKQoKICAgIGRlZiBydW4oc2VsZik6CiAgICAgICAgd2hpbGUgbm90IHNl
bGYuX3N0b3AuaXNfc2V0KCk6CiAgICAgICAgICAgIHNlbGYuX3dha2Uud2FpdChzZWxmLl9pbnRl
cnZhbCkKICAgICAgICAgICAgc2VsZi5fd2FrZS5jbGVhcigpCiAgICAgICAgICAgIGlmIHNlbGYu
X3N0b3AuaXNfc2V0KCk6CiAgICAgICAgICAgICAgICByZXR1cm4KICAgICAgICAgICAgcGVuZGlu
ZyA9IHNlbGYuX3N0b3JlLnBlbmRpbmcoKQogICAgICAgICAgICBpZiBub3QgcGVuZGluZzoKICAg
ICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIGxvZy5pbmZvKCLQkiDQvtGH0LXRgNC1
0LTQuCAlZCDQt9Cw0Y/QstC+0LosINC/0YDQvtCx0YPRjiDQvtGC0L/RgNCw0LLQuNGC0YwiLCBs
ZW4ocGVuZGluZykpCiAgICAgICAgICAgIGZvciBsZWFkIGluIHBlbmRpbmc6CiAgICAgICAgICAg
ICAgICBvaywgcmVhc29uID0gc2VsZi5fdHJhbnNwb3J0LnNlbmRfbWVzc2FnZShyZW5kZXJfbWVz
c2FnZShsZWFkKSkKICAgICAgICAgICAgICAgIGlmIG9rOgogICAgICAgICAgICAgICAgICAgIHNl
bGYuX3N0b3JlLm1hcmtfc2VudChsZWFkWyJpZCJdKQogICAgICAgICAgICAgICAgICAgIGxvZy5p
bmZvKCLQl9Cw0Y/QstC60LAgJXMg0LTQvtGB0YLQsNCy0LvQtdC90LAg0LjQtyDQvtGH0LXRgNC1
0LTQuCIsIGxlYWRbImlkIl0pCiAgICAgICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAg
ICAgIGxvZy53YXJuaW5nKCLQl9Cw0Y/QstC60LAgJXMg0LLRgdGRINC10YnRkSDQvdC1INGD0YXQ
vtC00LjRgjogJXMiLCBsZWFkWyJpZCJdLCByZWFzb24pCiAgICAgICAgICAgICAgICAgICAgYnJl
YWsgICMg0YHQvNGL0YHQu9CwINC00L7Qu9Cx0LjRgtGMINC+0YHRgtCw0LvRjNC90YvQtSDQvdC1
0YIg4oCUINC/0YPRgtGMINCy0YHRkSDRgNCw0LLQvdC+INC30LDQutGA0YvRggoKCiMgLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tICMKIyBIVFRQCiMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tICMKCmNsYXNzIEhhbmRs
ZXIoaHR0cC5zZXJ2ZXIuQmFzZUhUVFBSZXF1ZXN0SGFuZGxlcik6CiAgICBzZXJ2ZXJfdmVyc2lv
biA9ICIlcy8lcyIgJSAoQVBQX05BTUUsIFZFUlNJT04pCiAgICBwcm90b2NvbF92ZXJzaW9uID0g
IkhUVFAvMS4xIgoKICAgICMgLS0tINGB0LvRg9C20LXQsdC90L7QtSAtLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tICMKCiAgICBkZWYgbG9n
X21lc3NhZ2Uoc2VsZiwgZm10LCAqYXJncyk6CiAgICAgICAgbG9nLmluZm8oIiVzICVzIiwgc2Vs
Zi5hZGRyZXNzX3N0cmluZygpLCBmbXQgJSBhcmdzKQoKICAgIGRlZiBfb3JpZ2luX2hlYWRlcihz
ZWxmKToKICAgICAgICBvcmlnaW4gPSAoc2VsZi5oZWFkZXJzLmdldCgiT3JpZ2luIikgb3IgIiIp
LnJzdHJpcCgiLyIpCiAgICAgICAgaWYgIioiIGluIEFMTE9XRURfT1JJR0lOUzoKICAgICAgICAg
ICAgcmV0dXJuIG9yaWdpbiBvciAiKiIKICAgICAgICBpZiBvcmlnaW4gaW4gQUxMT1dFRF9PUklH
SU5TOgogICAgICAgICAgICByZXR1cm4gb3JpZ2luCiAgICAgICAgcmV0dXJuICIiCgogICAgZGVm
IF9zZW5kKHNlbGYsIHN0YXR1cywgcGF5bG9hZCk6CiAgICAgICAgYm9keSA9IGpzb24uZHVtcHMo
cGF5bG9hZCwgZW5zdXJlX2FzY2lpPUZhbHNlKS5lbmNvZGUoInV0Zi04IikKICAgICAgICBzZWxm
LnNlbmRfcmVzcG9uc2Uoc3RhdHVzKQogICAgICAgIHNlbGYuc2VuZF9oZWFkZXIoIkNvbnRlbnQt
VHlwZSIsICJhcHBsaWNhdGlvbi9qc29uOyBjaGFyc2V0PXV0Zi04IikKICAgICAgICBzZWxmLnNl
bmRfaGVhZGVyKCJDb250ZW50LUxlbmd0aCIsIHN0cihsZW4oYm9keSkpKQogICAgICAgIHNlbGYu
c2VuZF9oZWFkZXIoIkNhY2hlLUNvbnRyb2wiLCAibm8tc3RvcmUiKQogICAgICAgIGFsbG93ID0g
c2VsZi5fb3JpZ2luX2hlYWRlcigpCiAgICAgICAgaWYgYWxsb3c6CiAgICAgICAgICAgIHNlbGYu
c2VuZF9oZWFkZXIoIkFjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdpbiIsIGFsbG93KQogICAgICAg
ICAgICBzZWxmLnNlbmRfaGVhZGVyKCJWYXJ5IiwgIk9yaWdpbiIpCiAgICAgICAgc2VsZi5lbmRf
aGVhZGVycygpCiAgICAgICAgc2VsZi53ZmlsZS53cml0ZShib2R5KQoKICAgIGRlZiBfY2xpZW50
X2lwKHNlbGYpOgogICAgICAgICIiItCQ0LTRgNC10YEsINC60L7RgtC+0YDQvtC80YMg0LzQvtC2
0L3QviDQstC10YDQuNGC0YwuCgogICAgICAgIFgtRm9yd2FyZGVkLUZvciDQsdGA0LDRgtGMINCf
0JXQoNCS0KvQnCDRjdC70LXQvNC10L3RgtC+0Lwg0L3QtdC70YzQt9GPOiBuZ2lueCDRgQogICAg
ICAgICRwcm94eV9hZGRfeF9mb3J3YXJkZWRfZm9yINC00L7Qv9C40YHRi9Cy0LDQtdGCINC90LDR
gdGC0L7Rj9GJ0LjQuSDQsNC00YDQtdGBINCyINCa0J7QndCV0KYsINCwINC90LDRh9Cw0LvQvgog
ICAgICAgINGB0L/QuNGB0LrQsCDQv9GA0LjRhdC+0LTQuNGCINC+0YIg0LHRgNCw0YPQt9C10YDQ
sCDQuCDQv9C+0LTQtNC10LvRi9Cy0LDQtdGC0YHRjyDQvtC00L3QvtC5INGB0YLRgNC+0LrQvtC5
IOKAlCDQvtCz0YDQsNC90LjRh9C10L3QuNC1CiAgICAgICAg0YfQsNGB0YLQvtGC0Ysg0L7QsdGF
0L7QtNC40LvQvtGB0Ywg0LHRiyDRgtGA0LjQstC40LDQu9GM0L3Qvi4gWC1SZWFsLUlQINGB0YLQ
sNCy0LjRgiDRgdCw0LwgbmdpbngsINC/0L7RjdGC0L7QvNGDCiAgICAgICAg0L7QvSDQsiDQv9GA
0LjQvtGA0LjRgtC10YLQtSwg0LAg0LjQtyBYLUZvcndhcmRlZC1Gb3Ig0LHQtdGA0ZHRgtGB0Y8g
0L/QvtGB0LvQtdC00L3QuNC5INGN0LvQtdC80LXQvdGCLgogICAgICAgICIiIgogICAgICAgIHBl
ZXIgPSBzZWxmLmNsaWVudF9hZGRyZXNzWzBdCiAgICAgICAgIyDQl9Cw0LPQvtC70L7QstC60LDQ
vCDQstC10YDQuNC8LCDRgtC+0LvRjNC60L4g0LXRgdC70Lgg0LfQsNC/0YDQvtGBINC/0YDQuNGI
0ZHQuyDQvtGCINC70L7QutCw0LvRjNC90L7Qs9C+IG5naW54LgogICAgICAgICMg0JjQvdCw0YfQ
tSDQu9GO0LHQvtC5LCDQutGC0L4g0LTQvtGB0YLRg9GH0LjRgtGB0Y8g0LTQviDQv9C+0YDRgtCw
INC90LDQv9GA0Y/QvNGD0Y4sINC90LDQt9C+0LLRkdGC0YHRjyDQutC10Lwg0YPQs9C+0LTQvdC+
LgogICAgICAgIGlmIHBlZXIgbm90IGluIFRSVVNURURfUFJPWElFUzoKICAgICAgICAgICAgcmV0
dXJuIHBlZXIKICAgICAgICByZWFsID0gKHNlbGYuaGVhZGVycy5nZXQoIlgtUmVhbC1JUCIpIG9y
ICIiKS5zdHJpcCgpCiAgICAgICAgaWYgcmVhbDoKICAgICAgICAgICAgcmV0dXJuIHJlYWxbOjQ1
XQogICAgICAgIGZvcndhcmRlZCA9IHNlbGYuaGVhZGVycy5nZXQoIlgtRm9yd2FyZGVkLUZvciIs
ICIiKQogICAgICAgIGlmIGZvcndhcmRlZDoKICAgICAgICAgICAgcmV0dXJuIGZvcndhcmRlZC5z
cGxpdCgiLCIpWy0xXS5zdHJpcCgpWzo0NV0KICAgICAgICByZXR1cm4gcGVlcgoKICAgIGRlZiBf
ZHJhaW4oc2VsZik6CiAgICAgICAgIiIi0JTQvtGH0LjRgtCw0YLRjCDRgtC10LvQviDQt9Cw0L/R
gNC+0YHQsC4KCiAgICAgICAg0J/RgNC4IEhUVFAvMS4xINGBIGtlZXAtYWxpdmUg0L7RgtCy0LXR
giDQsdC10Lcg0LLRi9GH0LjRgtCw0L3QvdC+0LPQviDRgtC10LvQsCDQvtGB0YLQsNCy0LvRj9C1
0YIg0LHQsNC50YLRiwogICAgICAgINCyINGB0L7QutC10YLQtSwg0Lgg0L7QvdC4INGA0LDQt9Cx
0LjRgNCw0Y7RgtGB0Y8g0LrQsNC6INC90LDRh9Cw0LvQviDRgdC70LXQtNGD0Y7RidC10LPQviDQ
t9Cw0L/RgNC+0YHQsCDigJQg0YHRi9C/0LvRjtGC0YHRjwogICAgICAgINC90LXQvtCx0YrRj9GB
0L3QuNC80YvQtSA0MDAuCiAgICAgICAgIiIiCiAgICAgICAgdHJ5OgogICAgICAgICAgICBsZW5n
dGggPSBpbnQoc2VsZi5oZWFkZXJzLmdldCgiQ29udGVudC1MZW5ndGgiKSBvciAwKQogICAgICAg
IGV4Y2VwdCBWYWx1ZUVycm9yOgogICAgICAgICAgICBsZW5ndGggPSAwCiAgICAgICAgcmVtYWlu
aW5nID0gbWluKG1heChsZW5ndGgsIDApLCBNQVhfQk9EWSAqIDQpCiAgICAgICAgd2hpbGUgcmVt
YWluaW5nID4gMDoKICAgICAgICAgICAgY2h1bmsgPSBzZWxmLnJmaWxlLnJlYWQobWluKHJlbWFp
bmluZywgNjU1MzYpKQogICAgICAgICAgICBpZiBub3QgY2h1bms6CiAgICAgICAgICAgICAgICBi
cmVhawogICAgICAgICAgICByZW1haW5pbmcgLT0gbGVuKGNodW5rKQoKICAgICMgLS0tINC80LXR
gtC+0LTRiyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
LS0tLS0tLS0tLS0tICMKCiAgICBkZWYgZG9fT1BUSU9OUyhzZWxmKTogICMgbm9xYTogTjgwMgog
ICAgICAgIHNlbGYuc2VuZF9yZXNwb25zZSgyMDQpCiAgICAgICAgYWxsb3cgPSBzZWxmLl9vcmln
aW5faGVhZGVyKCkKICAgICAgICBpZiBhbGxvdzoKICAgICAgICAgICAgc2VsZi5zZW5kX2hlYWRl
cigiQWNjZXNzLUNvbnRyb2wtQWxsb3ctT3JpZ2luIiwgYWxsb3cpCiAgICAgICAgICAgIHNlbGYu
c2VuZF9oZWFkZXIoIlZhcnkiLCAiT3JpZ2luIikKICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJB
Y2Nlc3MtQ29udHJvbC1BbGxvdy1NZXRob2RzIiwgIlBPU1QsIE9QVElPTlMiKQogICAgICAgIHNl
bGYuc2VuZF9oZWFkZXIoIkFjY2Vzcy1Db250cm9sLUFsbG93LUhlYWRlcnMiLCAiQ29udGVudC1U
eXBlIikKICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJBY2Nlc3MtQ29udHJvbC1NYXgtQWdlIiwg
Ijg2NDAwIikKICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJDb250ZW50LUxlbmd0aCIsICIwIikK
ICAgICAgICBzZWxmLmVuZF9oZWFkZXJzKCkKCiAgICBkZWYgZG9fR0VUKHNlbGYpOiAgIyBub3Fh
OiBOODAyCiAgICAgICAgaWYgc2VsZi5wYXRoLnJzdHJpcCgiLyIpIGluICgiL2FwaS9oZWFsdGgi
LCAiL2hlYWx0aCIpOgogICAgICAgICAgICBzZWxmLl9zZW5kKAogICAgICAgICAgICAgICAgMjAw
LAogICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICJvayI6IFRydWUsCiAgICAg
ICAgICAgICAgICAgICAgInNlcnZpY2UiOiBBUFBfTkFNRSwKICAgICAgICAgICAgICAgICAgICAi
dmVyc2lvbiI6IFZFUlNJT04sCiAgICAgICAgICAgICAgICAgICAgInRlbGVncmFtX3BhdGgiOiBz
ZWxmLnNlcnZlci50cmFuc3BvcnQud29ya2luZ19wYXRoLAogICAgICAgICAgICAgICAgICAgICJw
ZW5kaW5nIjogc2VsZi5zZXJ2ZXIuc3RvcmUucGVuZGluZ19jb3VudCgpLAogICAgICAgICAgICAg
ICAgICAgICJjb25maWd1cmVkIjogYm9vbChCT1RfVE9LRU4gYW5kIENIQVRfSUQpLAogICAgICAg
ICAgICAgICAgfSwKICAgICAgICAgICAgKQogICAgICAgICAgICByZXR1cm4KICAgICAgICBzZWxm
Ll9zZW5kKDQwNCwgeyJvayI6IEZhbHNlLCAiZXJyb3IiOiAibm90X2ZvdW5kIn0pCgogICAgZGVm
IGRvX1BPU1Qoc2VsZik6ICAjIG5vcWE6IE44MDIKICAgICAgICBpZiBzZWxmLnBhdGgucnN0cmlw
KCIvIikgbm90IGluICgiL2FwaS9sZWFkIiwgIi9sZWFkIik6CiAgICAgICAgICAgIHNlbGYuX2Ry
YWluKCkKICAgICAgICAgICAgc2VsZi5fc2VuZCg0MDQsIHsib2siOiBGYWxzZSwgImVycm9yIjog
Im5vdF9mb3VuZCJ9KQogICAgICAgICAgICByZXR1cm4KCiAgICAgICAgdHJ5OgogICAgICAgICAg
ICBsZW5ndGggPSBpbnQoc2VsZi5oZWFkZXJzLmdldCgiQ29udGVudC1MZW5ndGgiKSBvciAwKQog
ICAgICAgIGV4Y2VwdCBWYWx1ZUVycm9yOgogICAgICAgICAgICBsZW5ndGggPSAwCiAgICAgICAg
aWYgbGVuZ3RoIDw9IDAgb3IgbGVuZ3RoID4gTUFYX0JPRFk6CiAgICAgICAgICAgIHNlbGYuX2Ry
YWluKCkKICAgICAgICAgICAgc2VsZi5fc2VuZCg0MTMsIHsib2siOiBGYWxzZSwgImVycm9yIjog
ImJhZF9zaXplIn0pCiAgICAgICAgICAgIHJldHVybgoKICAgICAgICByYXcgPSBzZWxmLnJmaWxl
LnJlYWQobGVuZ3RoKQogICAgICAgIHRyeToKICAgICAgICAgICAgcGF5bG9hZCA9IGpzb24ubG9h
ZHMocmF3LmRlY29kZSgidXRmLTgiKSkKICAgICAgICBleGNlcHQgKFVuaWNvZGVEZWNvZGVFcnJv
ciwgVmFsdWVFcnJvcik6CiAgICAgICAgICAgIHNlbGYuX3NlbmQoNDAwLCB7Im9rIjogRmFsc2Us
ICJlcnJvciI6ICJiYWRfanNvbiJ9KQogICAgICAgICAgICByZXR1cm4KICAgICAgICBpZiBub3Qg
aXNpbnN0YW5jZShwYXlsb2FkLCBkaWN0KToKICAgICAgICAgICAgc2VsZi5fc2VuZCg0MDAsIHsi
b2siOiBGYWxzZSwgImVycm9yIjogImJhZF9qc29uIn0pCiAgICAgICAgICAgIHJldHVybgoKICAg
ICAgICBpcCA9IHNlbGYuX2NsaWVudF9pcCgpCiAgICAgICAgaWYgbm90IHNlbGYuc2VydmVyLmxp
bWl0ZXIuYWxsb3coaXApOgogICAgICAgICAgICBsb2cud2FybmluZygi0J/RgNC10LLRi9GI0LXQ
vSDQu9C40LzQuNGCINC30LDRj9Cy0L7QuiDRgSAlcyIsIGlwKQogICAgICAgICAgICBzZWxmLl9z
ZW5kKDQyOSwgeyJvayI6IEZhbHNlLCAiZXJyb3IiOiAicmF0ZV9saW1pdGVkIn0pCiAgICAgICAg
ICAgIHJldHVybgoKICAgICAgICBsZWFkLCBlcnJvcnMgPSBwYXJzZV9sZWFkKHBheWxvYWQsIGlw
LCBzZWxmLmhlYWRlcnMuZ2V0KCJVc2VyLUFnZW50IiwgIiIpKQogICAgICAgIGlmIGVycm9yczoK
ICAgICAgICAgICAgaWYgZXJyb3JzLmdldCgiY29tcGFueSIpOgogICAgICAgICAgICAgICAgIyDQ
m9C+0LLRg9GI0LrQsCDRgdGA0LDQsdC+0YLQsNC70LA6INCx0L7RgtGDINC+0YLQstC10YfQsNC1
0Lwg0LrQsNC6INCx0YPQtNGC0L4g0LLRgdGRINGF0L7RgNC+0YjQvi4KICAgICAgICAgICAgICAg
IGxvZy53YXJuaW5nKCLQm9C+0LLRg9GI0LrQsCDRgdGA0LDQsdC+0YLQsNC70LAsINC30LDRj9Cy
0LrQsCDRgSAlcyDQvtGC0LHRgNC+0YjQtdC90LAiLCBpcCkKICAgICAgICAgICAgICAgIHNlbGYu
X3NlbmQoMjAwLCB7Im9rIjogVHJ1ZSwgImlkIjogIi0ifSkKICAgICAgICAgICAgICAgIHJldHVy
bgogICAgICAgICAgICBzZWxmLl9zZW5kKDQyMiwgeyJvayI6IEZhbHNlLCAiZXJyb3IiOiAiaW52
YWxpZCIsICJmaWVsZHMiOiBlcnJvcnN9KQogICAgICAgICAgICByZXR1cm4KCiAgICAgICAgIyDQ
odC90LDRh9Cw0LvQsCDQvdCwINC00LjRgdC6IOKAlCDQv9C+0YLQvtC8INCy0YHRkSDQvtGB0YLQ
sNC70YzQvdC+0LUuINCX0LDRj9Cy0LrQsCDQvdC1INGC0LXRgNGP0LXRgtGB0Y8uCiAgICAgICAg
dHJ5OgogICAgICAgICAgICBzZWxmLnNlcnZlci5zdG9yZS5hcHBlbmQobGVhZCkKICAgICAgICAg
ICAgc2VsZi5zZXJ2ZXIuc3RvcmUuZW5xdWV1ZShsZWFkKQogICAgICAgIGV4Y2VwdCBPU0Vycm9y
IGFzIGV4YzoKICAgICAgICAgICAgbG9nLmV4Y2VwdGlvbigi0J3QtSDRg9C00LDQu9C+0YHRjCDR
gdC+0YXRgNCw0L3QuNGC0Ywg0LfQsNGP0LLQutGDOiAlcyIsIGV4YykKICAgICAgICAgICAgc2Vs
Zi5fc2VuZCg1MDAsIHsib2siOiBGYWxzZSwgImVycm9yIjogInN0b3JhZ2UifSkKICAgICAgICAg
ICAgcmV0dXJuCgogICAgICAgICMg0J7RgtCy0LXRh9Cw0LXQvCDRgdGA0LDQt9GDLiDQntGC0L/R
gNCw0LLQutGDINCyIFRlbGVncmFtINC00LXQu9Cw0LXRgiDRhNC+0L3QvtCy0YvQuSDQv9C+0YLQ
vtC6OiDQtdGB0LvQuCDQvtCx0LAKICAgICAgICAjINC/0YPRgtC4INC00L4gYXBpLnRlbGVncmFt
Lm9yZyDQu9C10LbQsNGCLCDRgdC40L3RhdGA0L7QvdC90LDRjyDQvtGC0L/RgNCw0LLQutCwINC0
0LXRgNC20LDQu9CwINCx0YsKICAgICAgICAjINC/0L7RgdC10YLQuNGC0LXQu9GPINC00L4g0LTQ
stGD0YUg0YLQsNC50LzQsNGD0YLQvtCyINC/0L7QtNGA0Y/QtCwg0LAgbmdpbngg0YPRgdC/0LXQ
uyDQsdGLINC+0YLQstCw0LvQuNGC0YzRgdGPCiAgICAgICAgIyDQv9C+IHByb3h5X3JlYWRfdGlt
ZW91dC4g0JfQsNGP0LLQutCwINGD0LbQtSDQvdCwINC00LjRgdC60LUsINGC0LXRgNGP0YLRjCDQ
vdC10YfQtdCz0L4uCiAgICAgICAgbG9nLmluZm8oItCX0LDRj9Cy0LrQsCAlcyDQv9GA0LjQvdGP
0YLQsCIsIGxlYWRbImlkIl0pCiAgICAgICAgc2VsZi5fc2VuZCgyMDAsIHsib2siOiBUcnVlLCAi
aWQiOiBsZWFkWyJpZCJdfSkKICAgICAgICBzZWxmLnNlcnZlci5vdXRib3gucG9rZSgpCgoKY2xh
c3MgU2VydmVyKHNvY2tldHNlcnZlci5UaHJlYWRpbmdNaXhJbiwgaHR0cC5zZXJ2ZXIuSFRUUFNl
cnZlcik6CiAgICBkYWVtb25fdGhyZWFkcyA9IFRydWUKICAgIGFsbG93X3JldXNlX2FkZHJlc3Mg
PSBUcnVlCiAgICBhZGRyZXNzX2ZhbWlseSA9IHNvY2tldC5BRl9JTkVUNiBpZiAiOiIgaW4gQklO
RCBlbHNlIHNvY2tldC5BRl9JTkVUCgoKZGVmIG1haW4oKToKICAgIGlmIG5vdCBCT1RfVE9LRU4g
b3Igbm90IENIQVRfSUQ6CiAgICAgICAgbG9nLndhcm5pbmcoCiAgICAgICAgICAgICJBVVJFQV9L
VklaX0JPVF9UT0tFTiDQuNC70LggQVVSRUFfS1ZJWl9DSEFUX0lEINC90LUg0LfQsNC00LDQvdGL
LiAiCiAgICAgICAgICAgICLQodC10YDQstC40YEg0L/QvtC00L3QuNC80LXRgtGB0Y8g0Lgg0LHR
g9C00LXRgiDRgdC+0YXRgNCw0L3Rj9GC0Ywg0LfQsNGP0LLQutC4LCDQvdC+INC+0YLQv9GA0LDQ
stC70Y/RgtGMINC40YUg0L3QtSDRgdC80L7QttC10YIuIgogICAgICAgICkKCiAgICBzdG9yZSA9
IExlYWRTdG9yZShEQVRBX0RJUikKICAgIHRyYW5zcG9ydCA9IFRlbGVncmFtVHJhbnNwb3J0KEJP
VF9UT0tFTiwgSVBfRkFNSUxZX1BSRUYpCiAgICBvdXRib3ggPSBPdXRib3hXb3JrZXIoc3RvcmUs
IHRyYW5zcG9ydCkKCiAgICAjINCh0L7QutC10YIg0L/QvtC00L3QuNC80LDQtdGC0YHRjyDQn9CV
0KDQktCr0Jwg0LTQtdC70L7QvC4g0J/RgNC+0LHQsCDQvtCx0L7QuNGFINC/0YPRgtC10Lkg0LTQ
viBUZWxlZ3JhbSDQt9Cw0L3QuNC80LDQtdGCCiAgICAjINGB0LXQutGD0L3QtNGLOyDQtdGB0LvQ
uCDQtNC10LvQsNGC0Ywg0LXRkSDQtNC+IGJpbmQsIHN5c3RlbWQg0L/RgNC4IFR5cGU9c2ltcGxl
INGD0LbQtSDRgdGH0LjRgtCw0LXRggogICAgIyDRgdC70YPQttCx0YMg0LfQsNC/0YPRidC10L3Q
vdC+0LksINCwIG5naW54INCyINGN0YLQviDQvtC60L3QviDQvtGC0LTQsNGR0YIgNTAyLgogICAg
c2VydmVyID0gU2VydmVyKChCSU5ELCBQT1JUKSwgSGFuZGxlcikKICAgIHNlcnZlci5zdG9yZSA9
IHN0b3JlCiAgICBzZXJ2ZXIudHJhbnNwb3J0ID0gdHJhbnNwb3J0CiAgICBzZXJ2ZXIub3V0Ym94
ID0gb3V0Ym94CiAgICBzZXJ2ZXIubGltaXRlciA9IFJhdGVMaW1pdGVyKFJBVEVfUEVSX0hPVVIp
CiAgICBsb2cuaW5mbygiJXMgJXMg0YHQu9GD0YjQsNC10YIgJXM6JXMiLCBBUFBfTkFNRSwgVkVS
U0lPTiwgQklORCwgUE9SVCkKCiAgICBkZWYgd2FybV91cCgpOgogICAgICAgIHRyYW5zcG9ydC5w
cm9iZSgpCiAgICAgICAgb3V0Ym94LnBva2UoKQoKICAgIG91dGJveC5zdGFydCgpCiAgICB0aHJl
YWRpbmcuVGhyZWFkKHRhcmdldD13YXJtX3VwLCBuYW1lPSJwcm9iZSIsIGRhZW1vbj1UcnVlKS5z
dGFydCgpCiAgICB0cnk6CiAgICAgICAgc2VydmVyLnNlcnZlX2ZvcmV2ZXIoKQogICAgZXhjZXB0
IEtleWJvYXJkSW50ZXJydXB0OgogICAgICAgIHBhc3MKICAgIGZpbmFsbHk6CiAgICAgICAgb3V0
Ym94LnN0b3AoKQogICAgICAgIHNlcnZlci5zZXJ2ZXJfY2xvc2UoKQogICAgICAgIGxvZy5pbmZv
KCLQntGB0YLQsNC90L7QstC70LXQvSIpCgoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAg
IG1haW4oKQo=
AUREA_KVIZ_APP_B64
python3 -m py_compile "$TMP_APP" || die "код службы не компилируется — установка прервана"
if [ -f "$APP_DIR/app.py" ] && cmp -s "$TMP_APP" "$APP_DIR/app.py"; then
  ok "app.py не изменился"
else
  install -m 0644 -o root -g root "$TMP_APP" "$APP_DIR/app.py"
  CHANGED=1
  ok "app.py установлен"
fi
rm -f "$TMP_APP"
find "$APP_DIR" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

# ===========================================================================
step "5. Файл настроек с токеном"
# ===========================================================================
# Существующие значения не переписываются: владелец мог поправить их руками.
# Дописываются только недостающие ключи.
if [ ! -f "$ENV_FILE" ]; then
  umask 077
  printf '%s\n' \
    "# AUREA · настройки приёмника заявок. Права 600, читает systemd под root." \
    "# Впишите токен бота и id получателя, потом: systemctl restart $SVC" \
    "" > "$ENV_FILE"
  warn "создан пустой $ENV_FILE"
else
  ok "$ENV_FILE уже есть — существующие значения не трогаю"
fi

add_key() {
  grep -q "^$1=" "$ENV_FILE" || { printf '%s=%s\n' "$1" "$2" >> "$ENV_FILE"; ok "дописан $1"; }
}
add_key AUREA_KVIZ_BOT_TOKEN ""
add_key AUREA_KVIZ_CHAT_ID ""
add_key AUREA_KVIZ_BIND "127.0.0.1"
add_key AUREA_KVIZ_PORT "$PORT"
add_key AUREA_KVIZ_DATA_DIR "$DATA_DIR"
add_key AUREA_KVIZ_ALLOWED_ORIGINS "$ORIGINS"
add_key AUREA_KVIZ_IP_FAMILY "auto"
add_key AUREA_KVIZ_RATE_PER_HOUR "8"
chmod 0600 "$ENV_FILE"; chown root:root "$ENV_FILE"

CUR_ORIGINS=$(sed -n 's/^AUREA_KVIZ_ALLOWED_ORIGINS=//p' "$ENV_FILE" | head -1)
if [ "$CUR_ORIGINS" != "$ORIGINS" ]; then
  warn "в настройках AUREA_KVIZ_ALLOWED_ORIGINS = $CUR_ORIGINS"
  warn "а ожидался $ORIGINS — если адрес сайта сменился, поправьте вручную"
fi

# ===========================================================================
step "6. Служба systemd"
# ===========================================================================
NEW_UNIT=$(mktemp)
base64 -d > "$NEW_UNIT" <<'AUREA_KVIZ_UNIT_B64'
IyDQldC00LjQvdGB0YLQstC10L3QvdC+0LUg0L7Qv9C40YHQsNC90LjQtSDRgdC70YPQttCx0Ysu
INCSINGD0YHRgtCw0L3QvtCy0YnQuNC6INC+0L3QviDQv9C+0L/QsNC00LDQtdGCINGG0LXQu9C4
0LrQvtC8CiMgKHNjcmlwdHMvYnVpbGQtaW5zdGFsbGVyLnNoKSwg0L/QvtGN0YLQvtC80YMg0YDQ
sNC30L7QudGC0LjRgdGMINC60L7Qv9C40Y/QvCDQvdC10L7RgtC60YPQtNCwLgpbVW5pdF0KRGVz
Y3JpcHRpb249QVVSRUEgwrcg0L/RgNC40ZHQvNC90LjQuiDQt9Cw0Y/QstC+0Log0YEg0LrQstC4
0Lct0LvQtdC90LTQuNC90LPQsApEb2N1bWVudGF0aW9uPWh0dHBzOi8vZ2l0aHViLmNvbS9raXJp
bGwtZGVzaWduMzY3L2t2aXoKQWZ0ZXI9bmV0d29yay1vbmxpbmUudGFyZ2V0CldhbnRzPW5ldHdv
cmstb25saW5lLnRhcmdldAojINCY0L3QsNGH0LUg0YHQtdGA0LjRjyDQsdGL0YHRgtGA0YvRhSDQ
v9Cw0LTQtdC90LjQuSDQt9Cw0LPQvtC90Y/QtdGCINGO0L3QuNGCINCyIGZhaWxlZCDQvdCw0YHQ
vtCy0YHQtdC8LAojINC4INGB0LXRgNCy0LjRgSDQvdC1INC/0L7QtNC90LjQvNC10YLRgdGPINC0
0LDQttC1INC/0L7RgdC70LUg0YLQvtCz0L4sINC60LDQuiDQv9GA0LjRh9C40L3QsCDRg9GB0YLR
gNCw0L3QtdC90LAuClN0YXJ0TGltaXRJbnRlcnZhbFNlYz0wCgpbU2VydmljZV0KVHlwZT1zaW1w
bGUKVXNlcj1hdXJlYWt2aXoKR3JvdXA9YXVyZWFrdml6CldvcmtpbmdEaXJlY3Rvcnk9L29wdC9h
dXJlYS1rdml6CkV4ZWNTdGFydD0vdXNyL2Jpbi9lbnYgcHl0aG9uMyAvb3B0L2F1cmVhLWt2aXov
YXBwLnB5CkVudmlyb25tZW50RmlsZT0vZXRjL2F1cmVhLWt2aXova3Zpei5lbnYKUmVzdGFydD1h
bHdheXMKUmVzdGFydFNlYz0zClN5c2xvZ0lkZW50aWZpZXI9YXVyZWEta3ZpegoKIyDQmNC30L7Q
u9GP0YbQuNGPOiDRgdC70YPQttCx0LUg0L3Rg9C20LXQvSDRgtC+0LvRjNC60L4g0YHQstC+0Lkg
0LrQsNGC0LDQu9C+0LMg0LTQsNC90L3Ri9GFINC4INGB0LXRgtGMLgpOb05ld1ByaXZpbGVnZXM9
dHJ1ZQpQcml2YXRlVG1wPXRydWUKUHJpdmF0ZURldmljZXM9dHJ1ZQpQcm90ZWN0U3lzdGVtPXN0
cmljdApQcm90ZWN0SG9tZT10cnVlClByb3RlY3RLZXJuZWxUdW5hYmxlcz10cnVlClByb3RlY3RL
ZXJuZWxNb2R1bGVzPXRydWUKUHJvdGVjdENvbnRyb2xHcm91cHM9dHJ1ZQpQcm90ZWN0SG9zdG5h
bWU9dHJ1ZQpQcm90ZWN0Q2xvY2s9dHJ1ZQpSZXN0cmljdFNVSURTR0lEPXRydWUKUmVzdHJpY3RS
ZWFsdGltZT10cnVlClJlc3RyaWN0TmFtZXNwYWNlcz10cnVlCkxvY2tQZXJzb25hbGl0eT10cnVl
Ck1lbW9yeURlbnlXcml0ZUV4ZWN1dGU9dHJ1ZQpSZW1vdmVJUEM9dHJ1ZQpSZWFkV3JpdGVQYXRo
cz0vdmFyL2xpYi9hdXJlYS1rdml6CiMgQUZfVU5JWCDQvtCx0Y/Qt9Cw0YLQtdC70LXQvTog0LHQ
tdC3INC90LXQs9C+INC70L7QvNCw0LXRgtGB0Y8g0YDQtdC30L7Qu9Cy0LXRgCwg0LAg0LLRi9Cz
0LvRj9C00LjRgiDRjdGC0L4g0LrQsNC6IMKr0L3QtdGCINGB0LXRgtC4wrsuClJlc3RyaWN0QWRk
cmVzc0ZhbWlsaWVzPUFGX0lORVQgQUZfSU5FVDYgQUZfVU5JWApDYXBhYmlsaXR5Qm91bmRpbmdT
ZXQ9CkFtYmllbnRDYXBhYmlsaXRpZXM9CgpbSW5zdGFsbF0KV2FudGVkQnk9bXVsdGktdXNlci50
YXJnZXQK
AUREA_KVIZ_UNIT_B64
if [ -f "$UNIT" ] && cmp -s "$NEW_UNIT" "$UNIT"; then
  ok "описание службы не изменилось"
else
  install -m 0644 "$NEW_UNIT" "$UNIT"
  CHANGED=1
  ok "описание службы записано в $UNIT"
fi
rm -f "$NEW_UNIT"

systemctl daemon-reload
systemctl enable "$SVC" >/dev/null 2>&1 || true
# Перезапуск только по делу: лишний рестарт роняет соединения на ровном месте.
if [ "$CHANGED" = "1" ] || ! systemctl is-active --quiet "$SVC"; then
  systemctl restart "$SVC"
  sleep 2
  ok "служба перезапущена"
else
  ok "служба уже работает и не менялась — не трогаю"
fi

if ! systemctl is-active --quiet "$SVC"; then
  warn "служба не поднялась, последние строки журнала:"
  journalctl -u "$SVC" -n 25 --no-pager | sed 's/^/      /'
  die "разберитесь с журналом и запустите скрипт заново"
fi
ok "служба $SVC работает"

# ===========================================================================
step "7. Отдельный конфиг nginx"
# ===========================================================================
NGINX_DONE=0
SITE=""
if have nginx; then
  if [ -d /etc/nginx/sites-available ] && nginx -T 2>/dev/null | grep -q 'sites-enabled'; then
    SITE=/etc/nginx/sites-available/$SVC.conf
    LINK=/etc/nginx/sites-enabled/$SVC.conf
  else
    SITE=/etc/nginx/conf.d/$SVC.conf
    LINK=""
  fi

  if [ -f "$SITE" ] && ! head -3 "$SITE" | grep -q 'managed-by: aurea-kviz'; then
    die "файл $SITE существует и создан не нами. Ничего не меняю."
  fi

  # Точное совпадение server_name, а не grep -w: точки в шаблоне это «любой
  # символ», и sub.kviz.aureadesign.ru давал бы ложный конфликт.
  CONFLICT=$(nginx -T 2>/dev/null \
    | grep -E '^[[:space:]]*server_name' \
    | tr -s ' ' | sed 's/^ *server_name //; s/;$//' \
    | tr ' ' '\n' \
    | grep -Fxq "$DOMAIN" && echo yes || echo no)
  OURS_ALREADY=$([ -f "$SITE" ] && echo yes || echo no)

  if [ "$CONFLICT" = "yes" ] && [ "$OURS_ALREADY" = "no" ]; then
    warn "домен $DOMAIN уже объявлен в чужом конфиге nginx."
    warn "Конфиг пропущен, чтобы ничего не сломать. Настройте проксирование сами:"
    warn "  proxy_pass http://127.0.0.1:$PORT;"
  else
    # nginx до 1.25.1 не понимает отдельную директиву «http2 on».
    NGINX_VER=$(nginx -v 2>&1 | sed 's/.*\///; s/[^0-9.].*//')
    if printf '%s\n1.25.1\n' "$NGINX_VER" | sort -V | head -1 | grep -qx "1.25.1"; then
      HTTP2_LINE="    http2 on;"
      SSL_LISTEN_4="    listen 443 ssl;"
      SSL_LISTEN_6="    listen [::]:443 ssl;"
    else
      HTTP2_LINE=""
      SSL_LISTEN_4="    listen 443 ssl http2;"
      SSL_LISTEN_6="    listen [::]:443 ssl http2;"
    fi
    ok "nginx $NGINX_VER — директива http2 подобрана под версию"

    HAS_CERT=no
    [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ] && HAS_CERT=yes

    # Конфиг генерируется целиком, а не дописывается: дописывание ломается,
    # если файл когда-нибудь правили руками.
    write_site() {
      cat <<SITEEOF
$MARKER — файл принадлежит только квиз-лендингу.
# Другие сайты этого сервера он не затрагивает.
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    location ^~ /.well-known/acme-challenge/ {
        root $ACME_DIR;
        default_type "text/plain";
    }

$(if [ "$1" = "yes" ]; then
cat <<REDIR
    location / {
        return 301 https://\$host\$request_uri;
    }
REDIR
else
cat <<PROXY
    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
        client_max_body_size 32k;
    }
PROXY
fi)
}
$(if [ "$1" = "yes" ]; then
cat <<TLSEOF

server {
$SSL_LISTEN_4
$SSL_LISTEN_6
$HTTP2_LINE
    server_name $DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:AureaKviz:1m;

    location / {
        proxy_pass http://127.0.0.1:$PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
        client_max_body_size 32k;
    }
}
TLSEOF
fi)
SITEEOF
    }

    apply_site() {
      local want_tls="$1" tmp backup
      tmp=$(mktemp)
      write_site "$want_tls" > "$tmp"
      if [ -f "$SITE" ] && cmp -s "$tmp" "$SITE"; then
        rm -f "$tmp"; ok "конфиг nginx не изменился"; NGINX_DONE=1; return 0
      fi
      backup=""
      if [ -f "$SITE" ]; then backup=$(mktemp); cp "$SITE" "$backup"; fi
      install -m 0644 "$tmp" "$SITE"; rm -f "$tmp"
      [ -n "$LINK" ] && ln -sfn "$SITE" "$LINK"
      if nginx -t >/dev/null 2>&1; then
        systemctl reload nginx && ok "nginx перечитал конфигурацию"
        [ -n "$backup" ] && rm -f "$backup"
        NGINX_DONE=1
        return 0
      fi
      warn "nginx -t ругается, откатываю только свой файл:"
      nginx -t 2>&1 | sed 's/^/      /'
      if [ -n "$backup" ]; then install -m 0644 "$backup" "$SITE"; rm -f "$backup";
      else rm -f "$SITE"; [ -n "$LINK" ] && rm -f "$LINK"; fi
      nginx -t >/dev/null 2>&1 && systemctl reload nginx
      return 1
    }

    apply_site "$HAS_CERT" || warn "конфиг nginx не применён"
  fi

  if have getenforce && [ "$(getenforce 2>/dev/null)" = "Enforcing" ]; then
    if [ "$ALLOW_SELINUX" = "1" ]; then
      setsebool -P httpd_can_network_connect 1 && ok "SELinux: разрешил nginx ходить по сети"
    else
      warn "SELinux в режиме Enforcing. Чтобы nginx смог проксировать, нужна команда:"
      warn "  setsebool -P httpd_can_network_connect 1"
      warn "Она действует на ВСЕ httpd-процессы сервера, поэтому сама не выполняется."
      warn "Разрешить: перезапустите скрипт с AUREA_KVIZ_ALLOW_SELINUX=1"
    fi
  fi
else
  warn "nginx не найден — проксирование настройте сами на http://127.0.0.1:$PORT"
fi

# ===========================================================================
step "8. Сертификат Let's Encrypt"
# ===========================================================================
CERT_DIR="/etc/letsencrypt/live/$DOMAIN"
if [ "$SKIP_TLS" = "1" ]; then
  warn "выпуск сертификата пропущен по AUREA_KVIZ_SKIP_TLS=1"
elif [ "$NGINX_DONE" != "1" ]; then
  warn "nginx не настроен — сертификат пропущен"
elif [ -f "$CERT_DIR/fullchain.pem" ] \
     && openssl x509 -checkend 2592000 -noout -in "$CERT_DIR/fullchain.pem" >/dev/null 2>&1; then
  # Повторные обращения к Let's Encrypt быстро упираются в лимит: пять
  # одинаковых сертификатов в неделю — и домен закрыт на неделю.
  ok "сертификат для $DOMAIN есть и действует ещё больше месяца"
else
  if ! have certbot; then
    if [ "$ALLOW_APT" = "1" ]; then
      if have apt-get; then
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq certbot >/dev/null 2>&1 || true
      elif have dnf; then dnf install -y -q certbot >/dev/null 2>&1 || true
      elif have yum; then yum install -y -q certbot >/dev/null 2>&1 || true
      fi
    else
      warn "certbot не установлен. Ставить пакеты на чужой сервер сам не буду."
      warn "Поставьте вручную:  apt-get install -y certbot"
      warn "или перезапустите скрипт с AUREA_KVIZ_ALLOW_APT=1"
    fi
  fi
  if have certbot; then
    RESOLVED=$(getent ahosts "$DOMAIN" 2>/dev/null | head -1 | awk '{print $1}')
    if [ -z "$RESOLVED" ]; then
      warn "$DOMAIN не резолвится. Заведите записи A и AAAA и запустите скрипт заново."
    else
      ok "$DOMAIN резолвится в $RESOLVED"
      CB="certonly --webroot -w $ACME_DIR -d $DOMAIN --agree-tos --non-interactive --keep-until-expiring"
      if [ -n "$LE_EMAIL" ]; then CB="$CB -m $LE_EMAIL"; else CB="$CB --register-unsafely-without-email"; fi
      if certbot $CB; then
        ok "сертификат выпущен"
        apply_site yes || warn "не удалось включить https"
      else
        warn "certbot не справился — сайт останется на http"
      fi
    fi
  fi
fi

# ===========================================================================
step "9. Проверка"
# ===========================================================================
HEALTH=$(curl -s --max-time 5 "http://127.0.0.1:$PORT/api/health" || true)
if [ -n "$HEALTH" ]; then ok "служба отвечает: $HEALTH"; else warn "служба не ответила на /api/health"; fi

echo "  Путь до Telegram по журналу:"
journalctl -u "$SVC" -n 60 --no-pager 2>/dev/null | grep -i 'telegram' | tail -4 | sed 's/^/      /' || true

if grep -q '^AUREA_KVIZ_BOT_TOKEN=$' "$ENV_FILE" 2>/dev/null; then
  warn "токен ещё не заполнен — заявки будут копиться в очереди"
fi

echo
printf '%sГотово.%s\n\n' "$BLD" "$RST"
cat <<SUMEOF
  Служба:     systemctl status $SVC
  Журнал:     journalctl -u $SVC -f
  Настройки:  $ENV_FILE   (права 600)
  Данные:     $DATA_DIR/leads.jsonl   — все заявки
              $DATA_DIR/outbox/       — не ушедшие в Telegram
  Локально:   http://127.0.0.1:$PORT/api/health
  Снаружи:    https://$DOMAIN/api/lead

  Дальше:
    1. Впишите токен и chat_id:    nano $ENV_FILE
    2. Перезапустите:              systemctl restart $SVC
    3. Проверьте путь до Telegram: journalctl -u $SVC -n 30 --no-pager | grep -i telegram
SUMEOF
